// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { AddGroupMemberRequest } from "../../types/group/AddGroupMemberRequest";
import type { GroupMemberResponse } from "../../types/group/GroupMemberResponse";
import type { SetGroupMemberRoleRequest } from "../../types/group/SetGroupMemberRoleRequest";
import type { Uid } from "../../types/primitives/Uid";

export const groupMember = {
  /**
   * Add an existing user to the group with a role.
   *
   * Requires `AddMembers` in the group itself — a row platform staff alone hold — plus a role there able to manage the one being assigned; a user already in the group is a conflict, and a user who does not exist yet is invited, not added. Group administrators onboard through an invitation instead.
   */
  add: Tapi.post<{ path: { group_uid: Uid }; body: AddGroupMemberRequest; response: null }>()({
    endpoint: "/group/:group_uid/member",
  }),
  /**
   * List the group's members, each carrying the identity fields that name the person behind the membership.
   *
   * Requires `ViewMembers` in the group itself.
   */
  list: Tapi.get<{ path: { group_uid: Uid }; response: Array<GroupMemberResponse> }>()({
    endpoint: "/group/:group_uid/member",
  }),
  /**
   * Remove a member from the group; the user itself and every other membership they hold are untouched.
   *
   * Requires `RemoveMembers` in the group itself, and the caller's role there must be able to manage the member's current role; the caller can never remove their own membership, and a user who is not a member of this group reads as not found.
   */
  remove: Tapi.delete<{ path: { group_uid: Uid; user_uid: Uid }; response: null }>()({
    endpoint: "/group/:group_uid/member/:user_uid",
  }),
  /**
   * Replace a member's role in the group.
   *
   * Requires `SetMemberRole` in the group itself, and the caller's role there must be able to manage both the role being replaced and the one replacing it; the caller can never re-role their own membership, and a user who is not a member of this group reads as not found.
   */
  setRole: Tapi.put<{ path: { group_uid: Uid; user_uid: Uid }; body: SetGroupMemberRoleRequest; response: null }>()({
    endpoint: "/group/:group_uid/member/:user_uid",
  }),
};
