// This file was generated by tapir. Do not edit this file manually.

/**
 * A metric's value: most metrics report a number; breakdown metrics report
 * an object of numbers per dimension (e.g. reactions by type). Metrics
 * whose reported value fits neither shape — including a missing value —
 * are dropped at fetch time; nothing raw is passed through.
 */
export type InsightValue = number | {
  [key in string]: number
};
