// This file was generated by tapir. Do not edit this file manually.
import type { InsightValue } from "./InsightValue";

/**
 * One metric value returned by an insights read: the most recent value the
 * platform reported for the metric.
 */
export type Insight = {
  name: string,
  period: string | null,
  value: InsightValue,
};
