// This file was generated by tapir. Do not edit this file manually.
import type { InstagramMedia } from "./InstagramMedia";

/**
 * An Instagram post. All media URLs must be publicly reachable — Meta's
 * servers fetch them. Video-backed media (reels, video stories, video
 * carousel items) process asynchronously on Meta's side.
 */
export type InstagramPostContent = {
  media: InstagramMedia,
  caption: string | null,
  /**
   * Instagram location id (from Meta's location search) to tag.
   */
  location_id: string | null,
  /**
   * Usernames invited as collaborators (public professional accounts).
   */
  collaborators: Array<string>,
};
