// This file was generated by tapir. Do not edit this file manually.
import type { InstagramCarouselItem } from "./InstagramCarouselItem";
import type { InstagramUserTag } from "./InstagramUserTag";

export type InstagramMedia = {
  "kind": "image",
  image_url: string,
  user_tags: Array<InstagramUserTag>,
  alt_text: string | null,
} | {
  "kind": "carousel",
  items: Array<InstagramCarouselItem>,
} | {
  "kind": "reel",
  video_url: string,
  /**
   * Also show the reel in the profile feed grid (defaults to Meta's own
   * default when omitted).
   */
  share_to_feed: boolean | null,
  /**
   * Public URL of a custom cover image.
   */
  cover_url: string | null,
} | {
  "kind": "story",
  image_url: string | null,
  video_url: string | null,
};
