// This file was generated by tapir. Do not edit this file manually.
import type { InstagramUserTag } from "./InstagramUserTag";

/**
 * One carousel item: exactly one of `image_url` / `video_url`.
 */
export type InstagramCarouselItem = {
  image_url: string | null,
  video_url: string | null,
  user_tags: Array<InstagramUserTag>,
};
