// This file was generated by tapir. Do not edit this file manually.

/**
 * Messaging tags that lift the standard 24h response window (Send API `tag`
 * parameter). Only `HumanAgent` survives in 2026 (7-day window for human
 * replies; the app must hold the `human_agent` permission).
 */
export type MessageTag = "human_agent";

/** Every `MessageTag`, in declaration order. */
export const MESSAGE_TAG = ["human_agent"] as const satisfies readonly MessageTag[];
