// This file was generated by tapir. Do not edit this file manually.

/**
 * Conversation presence signals (Send API `sender_action` parameter).
 * WhatsApp rides its own read-receipt + typing-indicator call instead:
 * `mark_seen`/`typing_on` map onto it and there is no `typing_off`
 * (indicators auto-dismiss).
 */
export type SenderAction = "mark_seen" | "typing_on" | "typing_off";

/** Every `SenderAction`, in declaration order. */
export const SENDER_ACTION = ["mark_seen", "typing_on", "typing_off"] as const satisfies readonly SenderAction[];
