// This file was generated by tapir. Do not edit this file manually.

/**
 * What the template is for. Meta prices and rate-limits by category, and a
 * template's category is fixed at approval.
 */
export type WhatsappTemplateCategory = "utility" | "marketing" | "authentication";

/** Every `WhatsappTemplateCategory`, in declaration order. */
export const WHATSAPP_TEMPLATE_CATEGORY = ["utility", "marketing", "authentication"] as const satisfies readonly WhatsappTemplateCategory[];
