// This file was generated by tapir. Do not edit this file manually.

export type WhatsappTemplateDateTime = {
  /**
   * Meta localizes only what it can parse; everything else renders verbatim,
   * so the caller always supplies the text it wants shown.
   */
  fallback_value: string,
};
