// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappTemplateButtonSubType } from "./WhatsappTemplateButtonSubType";
import type { WhatsappTemplateParameter } from "./WhatsappTemplateParameter";

/**
 * One substitution block of a template *send* — the values that fill an
 * approved template's placeholders. Serializes straight to the Cloud API
 * shape: Meta spells these lowercase already, so no boundary translation.
 */
export type WhatsappTemplateSendComponent = {
  "type": "header",
  parameters: Array<WhatsappTemplateParameter>,
} | {
  "type": "body",
  parameters: Array<WhatsappTemplateParameter>,
} | {
  "type": "button",
  sub_type: WhatsappTemplateButtonSubType,
  index: string,
  parameters: Array<WhatsappTemplateParameter>,
};
