// This file was generated by tapir. Do not edit this file manually.

export type WhatsappTemplateCurrency = {
  /**
   * Rendered as-is if the recipient's locale is unsupported.
   */
  fallback_value: string,
  /**
   * ISO 4217, e.g. `BRL`.
   */
  code: string,
  /**
   * The amount multiplied by 1000 — Meta's integer money representation.
   */
  amount_1000: number,
};
