// This file was generated by tapir. Do not edit this file manually.

/**
 * A button on a template definition. WhatsApp allows up to ten, and mixing
 * kinds is constrained by Meta's own rules (validated on submit).
 */
export type WhatsappTemplateButton = {
  "type": "quick_reply",
  text: string,
} | {
  "type": "url",
  text: string,
  url: string,
  example: Array<string> | null,
} | {
  "type": "phone_number",
  text: string,
  phone_number: string,
} | {
  "type": "copy_code",
  example: string,
} | {
  "type": "unsupported"
};
