// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappTemplateButton } from "./WhatsappTemplateButton";

/**
 * One block of a template *definition* — the shape Meta stores for an
 * approved template and the shape a create request submits.
 *
 * The hub's own vocabulary, snake_case like every other enum on the surface;
 * Meta spells these uppercase, and that spelling lives at the boundary rather
 * than on the contract.
 */
export type WhatsappTemplateComponent = {
  "type": "header",
} & ({
  "format": "text",
  text: string,
  /**
   * One sample per placeholder. A header takes at most one.
   */
  example: Array<string> | null,
} | {
  "format": "image",
  example: Array<string> | null,
} | {
  "format": "video",
  example: Array<string> | null,
} | {
  "format": "document",
  example: Array<string> | null,
} | {
  "format": "location"
}) | {
  "type": "body",
  text: string,
  example: Array<string> | null,
} | {
  "type": "footer",
  text: string,
} | {
  "type": "buttons",
  buttons: Array<WhatsappTemplateButton>,
} | {
  "type": "unsupported"
};
