// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappTemplateCurrency } from "./WhatsappTemplateCurrency";
import type { WhatsappTemplateDateTime } from "./WhatsappTemplateDateTime";
import type { WhatsappTemplateMedia } from "./WhatsappTemplateMedia";

/**
 * One placeholder value. Media parameters carry a public URL, matching the
 * rest of the send surface (the hub never sends media ids).
 */
export type WhatsappTemplateParameter = {
  "type": "text",
  text: string,
} | {
  "type": "currency",
  currency: WhatsappTemplateCurrency,
} | {
  "type": "date_time",
  date_time: WhatsappTemplateDateTime,
} | {
  "type": "image",
  image: WhatsappTemplateMedia,
} | {
  "type": "video",
  video: WhatsappTemplateMedia,
} | {
  "type": "document",
  document: WhatsappTemplateMedia,
} | {
  "type": "payload",
  payload: string,
};
