// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ListUserSessionsQuery } from "../../types/user_session/ListUserSessionsQuery";
import type { Uid } from "../../types/primitives/Uid";
import type { UserSessionLoginRequest } from "../../types/user_session/UserSessionLoginRequest";
import type { UserSessionLoginResponse } from "../../types/user_session/UserSessionLoginResponse";
import type { UserSessionLogoutAllResponse } from "../../types/user_session/UserSessionLogoutAllResponse";
import type { UserSessionRow } from "../../types/user_session/UserSessionRow";

export const userSession = {
  /**
   * List active sessions for the caller or, when a user is specified, for another user.
   *
   * Any authenticated user for their own sessions; naming another user requires `ViewUserSessions`, which only platform staff hold.
   */
  list: Tapi.get<{ query: ListUserSessionsQuery; response: Array<UserSessionRow> }>()({
    endpoint: "/user-session",
  }),
  /**
   * Authenticate with email and password, returning a session token or an MFA/enrollment challenge.
   *
   * Public — no authentication required; the caller proves identity with the supplied email and password. Rejected before the password is checked when the caller trips either the per-IP or the per-email login throttle.
   */
  login: Tapi.post<{ body: UserSessionLoginRequest; response: UserSessionLoginResponse }>()({
    endpoint: "/user-session/login",
  }),
  /**
   * Invalidate the caller's current session and clear the session cookie.
   *
   * Authenticated user acting on their own session; no permission required.
   */
  logout: Tapi.post<{ response: null }>()({
    endpoint: "/user-session/logout",
  }),
  /**
   * Invalidate all of the caller's sessions and clear the session cookie.
   *
   * Authenticated user acting on their own sessions; no permission required.
   */
  logoutAll: Tapi.post<{ response: UserSessionLogoutAllResponse }>()({
    endpoint: "/user-session/logout-all",
  }),
  /**
   * Revoke a single session by its identifier.
   *
   * Any authenticated user for their own sessions; revoking another user's session requires `RevokeUserSessions`, which only platform staff hold.
   */
  revoke: Tapi.delete<{ path: { session_uid: Uid }; response: null }>()({
    endpoint: "/user-session/:session_uid",
  }),
};
