// This file was generated by tapir. Do not edit this file manually.
import type { EmailQueueStatus } from "../types/EmailQueueStatus";
import type { Number1_500 } from "../primitives/Number1_500";

export type EmailQueueListQuery = {
  status: EmailQueueStatus | null,
  limit: Number1_500 | null,
};
