// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Call } from "../../types/database/Call";
import type { CallClientMsg } from "../../types/call/CallClientMsg";
import type { CallServerMsg } from "../../types/call/CallServerMsg";
import type { PlaceCallRequest } from "../../types/call/PlaceCallRequest";
import type { Uid } from "../../types/primitives/Uid";

export const call = {
  /**
   * Answer a ringing call, claiming it for the caller — who is then the only
   * one that may carry its media. A second operator answering the same call
   * gets "chamada já atendida".
   *
   * Requires `SendMessages` in the conversation's group.
   */
  answer: Tapi.post<{ path: { conversation_uid: Uid; call_uid: Uid }; response: Call }>()({
    endpoint: "/conversation/:conversation_uid/call/:call_uid/answer",
  }),
  /**
   * End a call in progress. Not restricted to the operator holding it: a call
   * whose operator walked away has to be endable by whoever is still there. A
   * call that was never answered here has nothing to hang up — refusing that one
   * is `reject`.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  hangup: Tapi.post<{ path: { conversation_uid: Uid; call_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/call/:call_uid/hangup",
  }),
  /**
   * The call's live media, typed both ways. Binary frames carry the media
   * itself — `0x01` plus one 1920-byte s16le 16 kHz mono audio frame, or `0x02`
   * plus a flags byte and one H.264 Annex-B access unit — in exactly the
   * formats WhatsApp uses, so nothing between the browser and the contact
   * transcodes. Text frames carry the in-call controls: the video upgrade
   * handshake, camera state, orientation and reactions. Everything that decides
   * whether the call exists stays on the REST routes above.
   *
   * Reconnecting re-attaches and replaces the previous tracks; a claimed call
   * whose operator stays gone for 30 seconds is hung up rather than left
   * running silently.
   *
   * Requires `SendMessages` in the conversation's group, and the caller must be
   * the operator who answered (or placed) this call.
   */
  media: Tapi.ws<{ path: { conversation_uid: Uid; call_uid: Uid }; send: CallClientMsg; receive: CallServerMsg }>()({
    endpoint: "/conversation/:conversation_uid/call/:call_uid/media/ws",
  }),
  /**
   * Call the conversation's contact. The body is channel-tagged — only
   * whatsapp_native carries calls, so no other channel's shape deserializes.
   * Returns as soon as the offer is on the wire — the contact's phone has not
   * rung yet, and the phases that follow arrive as `call_updated` events. Only
   * one call at a time per account.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  place: Tapi.post<{ path: { conversation_uid: Uid }; body: PlaceCallRequest; response: Call }>()({
    endpoint: "/conversation/:conversation_uid/call",
  }),
  /**
   * Refuse a ringing call. Available to anyone who could have answered it — a
   * shared inbox's ringing call is everyone's to decline.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  reject: Tapi.post<{ path: { conversation_uid: Uid; call_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/call/:call_uid/reject",
  }),
  /**
   * List the calls ringing right now on accounts the caller can see — inbound,
   * unclaimed and still answerable. Ring events are broadcast once and never
   * replayed, so a client that just connected (a reloaded page, a login while a
   * call is ringing) hydrates its ringing list from here.
   *
   * Requires `ViewMessages`; the list is clamped to the groups where it is held.
   */
  ringing: Tapi.get<{ response: Array<Call> }>()({
    endpoint: "/call/ringing",
  }),
};
