// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { AccountInsightsQuery } from "../../types/social_account/AccountInsightsQuery";
import type { ConnectCallbackQuery } from "../../types/social_account/ConnectCallbackQuery";
import type { ConnectConfirmRequest } from "../../types/social_account/ConnectConfirmRequest";
import type { ConnectNativeRequest } from "../../types/social_account/ConnectNativeRequest";
import type { ConnectReviewQuery } from "../../types/social_account/ConnectReviewQuery";
import type { ConnectReviewResponse } from "../../types/social_account/ConnectReviewResponse";
import type { ConnectSocialAccountRequest } from "../../types/social_account/ConnectSocialAccountRequest";
import type { ConnectSocialAccountResponse } from "../../types/social_account/ConnectSocialAccountResponse";
import type { ConnectSocialAccountsConnected } from "../../types/social_account/ConnectSocialAccountsConnected";
import type { ConnectStevoRequest } from "../../types/social_account/ConnectStevoRequest";
import type { ConnectStevoResponse } from "../../types/social_account/ConnectStevoResponse";
import type { ConnectWhatsappRequest } from "../../types/social_account/ConnectWhatsappRequest";
import type { ConnectWhatsappResponse } from "../../types/social_account/ConnectWhatsappResponse";
import type { ExposureQuery } from "../../types/social_account/ExposureQuery";
import type { ExposureReport } from "../../types/domain/ExposureReport";
import type { Insight } from "../../types/meta/Insight";
import type { InsightHistoryQuery } from "../../types/insight/InsightHistoryQuery";
import type { InsightSeries } from "../../types/insight/InsightSeries";
import type { ListSocialAccountsQuery } from "../../types/social_account/ListSocialAccountsQuery";
import type { NativePairingStatusResponse } from "../../types/social_account/NativePairingStatusResponse";
import type { NativeQrResponse } from "../../types/social_account/NativeQrResponse";
import type { RefreshProfileResponse } from "../../types/social_account/RefreshProfileResponse";
import type { SessionStatus } from "../../types/social_account/SessionStatus";
import type { SetSocialAccountAliasRequest } from "../../types/social_account/SetSocialAccountAliasRequest";
import type { SetSocialAccountConversationCapRequest } from "../../types/social_account/SetSocialAccountConversationCapRequest";
import type { SetSocialAccountEnabledRequest } from "../../types/social_account/SetSocialAccountEnabledRequest";
import type { SetSocialAccountPresenceRequest } from "../../types/social_account/SetSocialAccountPresenceRequest";
import type { SocialAccountResponse } from "../../types/social_account/SocialAccountResponse";
import type { StartNativePairingResponse } from "../../types/social_account/StartNativePairingResponse";
import type { StevoPairRequest } from "../../types/social_account/StevoPairRequest";
import type { StevoPairResponse } from "../../types/social_account/StevoPairResponse";
import type { StevoQrResponse } from "../../types/social_account/StevoQrResponse";
import type { StevoStatusResponse } from "../../types/social_account/StevoStatusResponse";
import type { Uid } from "../../types/primitives/Uid";

export const socialAccount = {
  /**
   * Meta OAuth redirect target: consumes the state, exchanges the code, and
   * stashes the grant snapshot for review — nothing is registered yet; always
   * redirects the browser back to the frontend, with a review token on
   * success.
   *
   * Public — no authentication required; authorization comes from the one-shot state token issued by `socialAccount.connect`.
   */
  callback: Tapi.get<{ query: ConnectCallbackQuery; response: null }>()({
    endpoint: "/social-account/callback",
  }),
  /**
   * Start the Meta OAuth flow for a group, returning the login dialog URL. The
   * callback stashes the granted pages (and linked Instagram accounts) for
   * review; `socialAccount.connectConfirm` is what registers the selection.
   *
   * Requires `ConnectSocialAccounts` in the named group.
   */
  connect: Tapi.post<{ body: ConnectSocialAccountRequest; response: ConnectSocialAccountResponse }>()({
    endpoint: "/social-account/connect",
  }),
  /**
   * Register the selected accounts from a stashed grant (one-shot). Pages and
   * instagram accounts are selected independently; unselected accounts stay in
   * the Meta grant but out of the hub.
   *
   * Requires `ConnectSocialAccounts` in the group the stashed grant targets.
   */
  connectConfirm: Tapi.post<{ body: ConnectConfirmRequest; response: ConnectSocialAccountsConnected }>()({
    endpoint: "/social-account/connect/confirm",
  }),
  /**
   * Load a stashed Meta grant for the selection screen: every account it
   * covers, plus group accounts whose stored token died on the Meta side
   * (access removed) — those are flagged for reauthorization. Repeatable;
   * only confirm consumes the stash.
   *
   * Requires `ConnectSocialAccounts` in the group the stashed grant targets.
   */
  connectReview: Tapi.get<{ query: ConnectReviewQuery; response: ConnectReviewResponse }>()({
    endpoint: "/social-account/connect/review",
  }),
  /**
   * Connect a Stevo instance (unofficial WhatsApp gateway) to a group: the hub
   * validates the server + apikey and registers the account. The webhook must
   * be set manually in the Stevo panel. Pair the phone afterwards via the
   * `stevo/qr` or `stevo/pair` sub-routes.
   *
   * Requires `ConnectSocialAccounts` in the named group.
   */
  connectStevo: Tapi.post<{ body: ConnectStevoRequest; response: ConnectStevoResponse }>()({
    endpoint: "/social-account/stevo",
  }),
  /**
   * Connect a WhatsApp Business Account to a group by manual provisioning: the
   * hub discovers the WABA's phone numbers with the supplied permanent token,
   * subscribes webhooks, and registers one social account per number.
   *
   * Requires `ConnectSocialAccounts` in the named group.
   */
  connectWhatsapp: Tapi.post<{ body: ConnectWhatsappRequest; response: ConnectWhatsappResponse }>()({
    endpoint: "/social-account/whatsapp",
  }),
  /**
   * Count connected social accounts, optionally filtered by group.
   *
   * Requires `ViewSocialAccounts`; the count covers only accounts of groups where the caller holds it.
   */
  count: Tapi.get<{ query: ListSocialAccountsQuery; response: number }>()({
    endpoint: "/social-account/count",
  }),
  /**
   * Disconnect a social account, deleting its conversations, messages, and
   * posts with it. Native whatsapp accounts also unpair the phone
   * (best-effort, in the background).
   *
   * Requires `DeleteSocialAccounts` in the account's group.
   */
  delete: Tapi.delete<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid",
  }),
  /**
   * Read the account's exposure telemetry, hour by hour over the requested
   * period (at most 92 days): how many platform lookups it made (usync number
   * checks, profile pictures, presence subscriptions), its sends by origin,
   * first-time contacts, whatsapp 429 and 463/475 answers, slow send acks and
   * sends still without a delivery receipt an hour later, plus the alerts the
   * last 24 hours raise right now. Only the session-backed whatsapp channels
   * are metered.
   *
   * Requires `ViewSocialAccounts` in the account's group.
   */
  exposure: Tapi.get<{ path: { social_account_uid: Uid }; query: ExposureQuery; response: ExposureReport }>()({
    endpoint: "/social-account/:social_account_uid/exposure",
  }),
  /**
   * Fetch a single connected social account by uid, with the live session
   * status of its whatsapp session when applicable.
   *
   * Requires `ViewSocialAccounts` in the account's group.
   */
  get: Tapi.get<{ path: { social_account_uid: Uid }; response: SocialAccountResponse }>()({
    endpoint: "/social-account/:social_account_uid",
  }),
  /**
   * Fetch platform metrics for a facebook page or instagram professional
   * account (the per-channel defaults, or a caller-supplied
   * `metrics`/`period`/`metric_type`). No whatsapp flavor exposes insights.
   *
   * Requires `ViewInsights` in the account's group.
   */
  insights: Tapi.get<{ path: { social_account_uid: Uid }; query: AccountInsightsQuery; response: Array<Insight> }>()({
    endpoint: "/social-account/:social_account_uid/insight",
  }),
  /**
   * Day-by-day history of the account's collected metrics (reach, views,
   * follower counts, …), grouped per metric — the charting companion to the
   * live insights passthrough. History exists only from the day the account
   * was connected. A channel that reports no insights is refused here exactly
   * as the live endpoint refuses it.
   *
   * Requires `ViewInsights` in the account's group.
   */
  insightsHistory: Tapi.get<{ path: { social_account_uid: Uid }; query: InsightHistoryQuery; response: Array<InsightSeries> }>()({
    endpoint: "/social-account/:social_account_uid/insight/history",
  }),
  /**
   * List connected social accounts, optionally filtered by group, each with the
   * live session status of its whatsapp session when applicable.
   *
   * Requires `ViewSocialAccounts`; the list covers only accounts of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListSocialAccountsQuery; response: Array<SocialAccountResponse> }>()({
    endpoint: "/social-account",
  }),
  /**
   * Close the account's session without unpairing the phone; conflicts if the
   * phone already unpaired.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  nativeDisconnect: Tapi.post<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/native/disconnect",
  }),
  /**
   * Unpair the phone entirely (logout); re-pairing needs a new QR scan;
   * conflicts if the phone already unpaired.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  nativeLogout: Tapi.delete<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/native/session",
  }),
  /**
   * Poll a pairing's outcome; stop polling once `status` leaves `pairing`.
   *
   * Requires `ConnectSocialAccounts` in the group the pairing targets.
   */
  nativePairingStatus: Tapi.get<{ path: { pairing_handle: Uid }; response: NativePairingStatusResponse }>()({
    endpoint: "/social-account-pairing/:pairing_handle/status",
  }),
  /**
   * The current pairing QR to render (null until the first code arrives).
   *
   * Requires `ConnectSocialAccounts` in the group the pairing targets.
   */
  nativeQr: Tapi.get<{ path: { pairing_handle: Uid }; response: NativeQrResponse }>()({
    endpoint: "/social-account-pairing/:pairing_handle/qr",
  }),
  /**
   * Re-establish the account's session after a drop; conflicts if the phone
   * unpaired (re-pair with a new QR instead) or while a whatsapp ban on the
   * number is still in force, since logging back in during a ban lengthens it.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  nativeReconnect: Tapi.post<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/native/reconnect",
  }),
  /**
   * Live session status of a native account; a phone-side unpair reports
   * `unpaired` instead of an error.
   *
   * Requires `ViewSocialAccounts` in the account's group.
   */
  nativeStatus: Tapi.get<{ path: { social_account_uid: Uid }; response: SessionStatus }>()({
    endpoint: "/social-account/:social_account_uid/native/status",
  }),
  /**
   * Re-read this account's name and picture from its platform now, rather than
   * waiting for the daily sweep. Answers `true` when something actually changed.
   *
   * Never touches the alias — that is yours, and a platform rename is exactly
   * what it is meant to survive.
   *
   * Requires `UpdateSocialAccounts` in the account's group.
   */
  refreshProfile: Tapi.post<{ path: { social_account_uid: Uid }; response: RefreshProfileResponse }>()({
    endpoint: "/social-account/:social_account_uid/profile/refresh",
  }),
  /**
   * Set or clear an operator's own label for a connected account, on any
   * channel. The account's `name` is the platform's and is refreshed from it —
   * this is the field a team controls, for telling apart several accounts that
   * the platform names alike. Clearing it leaves the platform name alone.
   *
   * Requires `UpdateSocialAccounts` in the account's group.
   */
  setAlias: Tapi.put<{ path: { social_account_uid: Uid }; body: SetSocialAccountAliasRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/alias",
  }),
  /**
   * Cap how many conversations the hub may open on this account in any 24
   * hours, whoever asks for them (inbox, api key, campaign, import, GoHighLevel),
   * or lift the cap with `null`. Only the session-backed whatsapp channels enforce
   * it; other channels are refused.
   *
   * Requires `UpdateSocialAccounts` in the account's group.
   */
  setConversationCap: Tapi.put<{ path: { social_account_uid: Uid }; body: SetSocialAccountConversationCapRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/conversation-cap",
  }),
  /**
   * Enable or disable a connected social account; disabled accounts stop
   * ingesting webhooks and reject sends/publishes. Enabling clears a session
   * incident the next connect would clear anyway, leaves a reach-out hold to
   * expire on its own, and conflicts while a whatsapp ban is still in force. Disabling a native whatsapp account also
   * disconnects its session, and enabling connects it again.
   *
   * Requires `UpdateSocialAccounts` in the account's group.
   */
  setEnabled: Tapi.put<{ path: { social_account_uid: Uid }; body: SetSocialAccountEnabledRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/enabled",
  }),
  /**
   * Choose how this native whatsapp account announces itself online: following
   * the operators looking at its inbox (the default) or never. Takes effect on
   * the live session at once. One change per account every 30 seconds; a
   * sooner one is refused with the seconds left. Other channels have no
   * presence to steer and are refused.
   *
   * Requires `UpdateSocialAccounts` in the account's group.
   */
  setPresence: Tapi.put<{ path: { social_account_uid: Uid }; body: SetSocialAccountPresenceRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/presence",
  }),
  /**
   * Start a native (whatsmeow) pairing; returns a handle to poll for the QR and
   * the paired account. The account row is created only when the scan succeeds.
   *
   * Requires `ConnectSocialAccounts` in the named group.
   */
  startNativePairing: Tapi.post<{ body: ConnectNativeRequest; response: StartNativePairingResponse }>()({
    endpoint: "/social-account/native",
  }),
  /**
   * Close the instance's session without unpairing the phone. Temporarily
   * disabled — always fails with 503.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  stevoDisconnect: Tapi.post<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/stevo/disconnect",
  }),
  /**
   * Unpair the phone entirely (logout); re-pairing needs a new QR scan.
   * Temporarily disabled — always fails with 503.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  stevoLogout: Tapi.delete<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/stevo/session",
  }),
  /**
   * Start QR-less pairing: returns the code the user types under "link with
   * phone number" on the device. Temporarily disabled — always fails with 503.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  stevoPair: Tapi.post<{ path: { social_account_uid: Uid }; body: StevoPairRequest; response: StevoPairResponse }>()({
    endpoint: "/social-account/:social_account_uid/stevo/pair",
  }),
  /**
   * Fetch the instance's pairing QR code to render for the admin (valid while
   * the instance is connected but not yet logged in). Temporarily disabled —
   * always fails with 503.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  stevoQr: Tapi.get<{ path: { social_account_uid: Uid }; response: StevoQrResponse }>()({
    endpoint: "/social-account/:social_account_uid/stevo/qr",
  }),
  /**
   * Re-establish the instance's session after a drop; conflicts while a
   * whatsapp ban on the number is still in force, since logging back in
   * during a ban lengthens it. Temporarily disabled — always fails with 503.
   *
   * Requires `ConnectSocialAccounts` in the account's group.
   */
  stevoReconnect: Tapi.post<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/stevo/reconnect",
  }),
  /**
   * Live connection status of the instance (connected = session up; logged_in
   * = phone paired). Reading it also refreshes the account's stored name from
   * the paired profile when it changed (the picture follows the daily profile
   * sweep, which asks for it only once the gateway has echoed the account's
   * own number), and reads the gateway's health report: a reported reach-out
   * hold records a `reachout_timelock` session incident on the account, and its
   * lifting clears it. Both emit `account_updated` — the poll is the natural
   * refresh point, since it already runs whenever the panel is open.
   *
   * Requires `ViewSocialAccounts` in the account's group.
   */
  stevoStatus: Tapi.get<{ path: { social_account_uid: Uid }; response: StevoStatusResponse }>()({
    endpoint: "/social-account/:social_account_uid/stevo/status",
  }),
};
