// This file was generated by tapir. Do not edit this file manually.

export type AuditAction = "login" | "logout" | "logout_all" | "forgot_password" | "reset_password" | "register" | "create" | "update" | "delete" | "activate" | "deactivate" | "change_password" | "revoke" | "rotate" | "generate" | "set_permissions" | "set_enabled" | "retry" | "enroll_user_mfa" | "remove_user_mfa" | "user_mfa_challenge" | "user_mfa_verify" | "reset_user_mfa" | "add_member" | "set_member_role" | "remove_member" | "set_super_admin" | "unknown";

/** Every `AuditAction`, in declaration order. */
export const AUDIT_ACTION = ["login", "logout", "logout_all", "forgot_password", "reset_password", "register", "create", "update", "delete", "activate", "deactivate", "change_password", "revoke", "rotate", "generate", "set_permissions", "set_enabled", "retry", "enroll_user_mfa", "remove_user_mfa", "user_mfa_challenge", "user_mfa_verify", "reset_user_mfa", "add_member", "set_member_role", "remove_member", "set_super_admin", "unknown"] as const satisfies readonly AuditAction[];
