// This file was generated by tapir. Do not edit this file manually.

/**
 * How a call finished. Stamped once, when the platform reports the call ended,
 * and never revised — the conversation timeline reads it to say what happened
 * in words a person recognizes ("perdida", "recusada").
 */
export type CallOutcome = "completed" | "missed" | "rejected" | "answered_elsewhere" | "canceled" | "failed";

/** Every `CallOutcome`, in declaration order. */
export const CALL_OUTCOME = ["completed", "missed", "rejected", "answered_elsewhere", "canceled", "failed"] as const satisfies readonly CallOutcome[];
