// This file was generated by tapir. Do not edit this file manually.

/**
 * Which side placed the call. WhatsApp calls are peer-to-peer, so this is the
 * only thing that distinguishes an operator dialling a contact from the same
 * contact dialling in.
 */
export type CallDirection = "inbound" | "outbound";

/** Every `CallDirection`, in declaration order. */
export const CALL_DIRECTION = ["inbound", "outbound"] as const satisfies readonly CallDirection[];
