// This file was generated by tapir. Do not edit this file manually.

/**
 * Why a recipient was ruled out — the safety rails, exhaustively. A rail
 * that merely *defers* a recipient (its account offline or day-capped) is
 * not here: those rows stay `pending` and come back.
 */
export type CampaignSkipReason = "in_cooldown" | "missing_variable" | "campaign_ended";

/** Every `CampaignSkipReason`, in declaration order. */
export const CAMPAIGN_SKIP_REASON = ["in_cooldown", "missing_variable", "campaign_ended"] as const satisfies readonly CampaignSkipReason[];
