// This file was generated by tapir. Do not edit this file manually.

/**
 * The social platforms the hub speaks. Every channel-scoped payload —
 * messages, posts, accounts — is distinguished by this identifier so
 * consumers integrate one API shape across platforms.
 */
export type Channel = "facebook" | "instagram" | "whatsapp" | "whatsapp_stevo" | "whatsapp_native";

/** Every `Channel`, in declaration order. */
export const CHANNEL = ["facebook", "instagram", "whatsapp", "whatsapp_stevo", "whatsapp_native"] as const satisfies readonly Channel[];
