// This file was generated by tapir. Do not edit this file manually.

export type EmailQueueStatus = "pending" | "sending" | "sent" | "failed";

/** Every `EmailQueueStatus`, in declaration order. */
export const EMAIL_QUEUE_STATUS = ["pending", "sending", "sent", "failed"] as const satisfies readonly EmailQueueStatus[];
