// This file was generated by tapir. Do not edit this file manually.

/**
 * Tags a queued email so the worker can update the originating record on
 * completion (e.g. flip an `user_invite.email_status` to Sent/Failed).
 */
export type EmailKind = "other" | "user_invite" | "user_password_reset";

/** Every `EmailKind`, in declaration order. */
export const EMAIL_KIND = ["other", "user_invite", "user_password_reset"] as const satisfies readonly EmailKind[];
