// This file was generated by tapir. Do not edit this file manually.

export type HttpRateLimitScope = "global" | "anonymous" | "group";

/** Every `HttpRateLimitScope`, in declaration order. */
export const HTTP_RATE_LIMIT_SCOPE = ["global", "anonymous", "group"] as const satisfies readonly HttpRateLimitScope[];
