// This file was generated by tapir. Do not edit this file manually.

/**
 * Content that only arrives inbound. There is no send call for these shapes
 * — a send request takes [`OutboundContent`] and cannot even express them.
 */
export type InboundContent = {
  "kind": "share",
  url: string,
} | {
  "kind": "story_mention",
  url: string,
} | {
  "kind": "story_reply",
  story_url: string,
  text: string,
} | {
  "kind": "quick_reply",
  payload: string,
  text: string,
} | {
  "kind": "postback",
  title: string,
  payload: string,
} | {
  "kind": "unavailable",
  reason: string | null,
} | {
  "kind": "unsupported"
};
