// This file was generated by tapir. Do not edit this file manually.

export type IssueSeverity = "low" | "medium" | "high" | "critical";

/** Every `IssueSeverity`, in declaration order. */
export const ISSUE_SEVERITY = ["low", "medium", "high", "critical"] as const satisfies readonly IssueSeverity[];
