// This file was generated by tapir. Do not edit this file manually.

export type IssueCategory = "bug" | "performance" | "suggestion" | "ui" | "other";

/** Every `IssueCategory`, in declaration order. */
export const ISSUE_CATEGORY = ["bug", "performance", "suggestion", "ui", "other"] as const satisfies readonly IssueCategory[];
