// This file was generated by tapir. Do not edit this file manually.

/**
 * The storage/DTO axis: the role one `user_group` membership holds, stored as
 * TEXT. Splitting it from [`UserRole`] is what makes `SuperAdmin`
 * unrepresentable as a membership — the DB CHECK and strict deserialization
 * both reject it.
 */
export type MembershipRole = "admin" | "user";

/** Every `MembershipRole`, in declaration order. */
export const MEMBERSHIP_ROLE = ["admin", "user"] as const satisfies readonly MembershipRole[];
