// This file was generated by tapir. Do not edit this file manually.
import type { InboundContent } from "./InboundContent";
import type { OutboundContent } from "./OutboundContent";

/**
 * Stored message content, identical across channels: every row carries
 * either a sendable shape or an inbound-only one. Untagged over the two
 * internally-tagged halves, so the JSON stays the flat `kind`-tagged object
 * it always was — the split exists only in the type system.
 */
export type MessageContent = OutboundContent | InboundContent;
