// This file was generated by tapir. Do not edit this file manually.

/**
 * Who produced an outbound message row — the attribution consumers (CRMs)
 * use to tell machine sends from human takeovers without correlation
 * heuristics. `None` on inbound rows and on rows stored before the field
 * existed.
 */
export type MessageSentBy = "api_key" | "user" | "platform";

/** Every `MessageSentBy`, in declaration order. */
export const MESSAGE_SENT_BY = ["api_key", "user", "platform"] as const satisfies readonly MessageSentBy[];
