// This file was generated by tapir. Do not edit this file manually.

export type PostStatus = "scheduled" | "pending" | "published" | "failed" | "deleted";

/** Every `PostStatus`, in declaration order. */
export const POST_STATUS = ["scheduled", "pending", "published", "failed", "deleted"] as const satisfies readonly PostStatus[];
