// This file was generated by tapir. Do not edit this file manually.
import type { FacebookPostContent } from "../meta/FacebookPostContent";
import type { InstagramPostContent } from "../meta/InstagramPostContent";

/**
 * Channel-tagged post payload: publishing surfaces genuinely differ per
 * platform, so the variants carry channel-specific fields while the API
 * stays a single endpoint distinguished by the `channel` tag.
 */
export type PostContent = {
  "channel": "facebook"
} & FacebookPostContent | {
  "channel": "instagram"
} & InstagramPostContent;
