// This file was generated by tapir. Do not edit this file manually.

export type RateLimitAction = "login_attempt" | "user_password_reset" | "user_mfa_verify" | "user_mfa_dispatch_email" | "file_upload";

/** Every `RateLimitAction`, in declaration order. */
export const RATE_LIMIT_ACTION = ["login_attempt", "user_password_reset", "user_mfa_verify", "user_mfa_dispatch_email", "file_upload"] as const satisfies readonly RateLimitAction[];
