// This file was generated by tapir. Do not edit this file manually.

/**
 * Where a conversation (re-)entry came from, normalized across every channel
 * that reports one. Kind-tagged so consumers distinguish origins without
 * probing fields: each variant carries exactly what its origin provides.
 */
export type Referral = {
  "kind": "whatsapp_ad",
  /**
   * Link to the ad or post.
   */
  source_url: string | null,
  /**
   * The ad or post id — what campaign reporting groups by.
   */
  source_id: string | null,
  /**
   * `ad` or `post`.
   */
  source_type: string | null,
  /**
   * The creative's title.
   */
  headline: string | null,
  /**
   * The creative's description.
   */
  body: string | null,
  /**
   * `image` or `video`.
   */
  media_type: string | null,
  /**
   * The creative's image, video still, or thumbnail — whichever the
   * channel reported, collapsed to one url.
   */
  thumbnail_url: string | null,
  /**
   * The click token, unique per ad tap.
   */
  ctwa_clid: string | null,
} | {
  "kind": "messenger_ad",
  /**
   * The ad id — what campaign reporting groups by.
   */
  ad_id: string | null,
  /**
   * The creative's title.
   */
  headline: string | null,
  /**
   * The creative's image or video still, collapsed to one url.
   */
  thumbnail_url: string | null,
  post_id: string | null,
  product_id: string | null,
  /**
   * The ref payload set on the ad, when one was.
   */
  ref_payload: string | null,
} | {
  "kind": "link",
  /**
   * `SHORTLINK`, `MESSENGER_CODE`, `CUSTOMER_CHAT_PLUGIN`, …
   */
  source: string | null,
  /**
   * The ref payload the link carried.
   */
  ref_payload: string | null,
  /**
   * The page the chat plugin was embedded on.
   */
  referer_uri: string | null,
};
