// This file was generated by tapir. Do not edit this file manually.

/**
 * The entities a search can answer with — the closed set every fan-out
 * matches exhaustively, so a new entity fails the build at each decision
 * point until it is handled there.
 */
export type SearchKind = "group" | "user" | "conversation" | "message";

/** Every `SearchKind`, in declaration order. */
export const SEARCH_KIND = ["group", "user", "conversation", "message"] as const satisfies readonly SearchKind[];
