// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MessageSearchHit } from "./MessageSearchHit";
import type { Name } from "../primitives/Name";
import type { Uid } from "../primitives/Uid";

export type SearchHitKind = {
  "kind": "group",
  uid: Uid,
  name: Name,
} | {
  "kind": "user",
  uid: Uid,
  name: Name,
  email: Email,
} | {
  "kind": "conversation",
  uid: Uid,
  social_account_uid: Uid,
  name: string | null,
  participant_id: string,
  participant_avatar_url: string | null,
} | {
  "kind": "message"
} & MessageSearchHit;
