// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { Name } from "../primitives/Name";
import type { Uid } from "../primitives/Uid";

export type SearchHitKind = {
  "kind": "group",
  uid: Uid,
  name: Name,
} | {
  "kind": "user",
  uid: Uid,
  name: Name,
  email: Email,
};
