// This file was generated by tapir. Do not edit this file manually.

/**
 * A button on a structured message. `Url` opens the link; `Postback` sends
 * the payload back as an [`InboundContent::Postback`] message.
 */
export type TemplateButton = {
  "type": "url",
  title: string,
  url: string,
} | {
  "type": "postback",
  title: string,
  payload: string,
};
