// This file was generated by tapir. Do not edit this file manually.

export type UserInviteEmailStatus = "pending_send" | "sent" | "failed";

/** Every `UserInviteEmailStatus`, in declaration order. */
export const USER_INVITE_EMAIL_STATUS = ["pending_send", "sent", "failed"] as const satisfies readonly UserInviteEmailStatus[];
