// This file was generated by tapir. Do not edit this file manually.

export type UserMfaKind = "totp" | "email";

/** Every `UserMfaKind`, in declaration order. */
export const USER_MFA_KIND = ["totp", "email"] as const satisfies readonly UserMfaKind[];
