// This file was generated by tapir. Do not edit this file manually.

export type AccountInsightsQuery = {
  /**
   * Meta metric names (comma-separated); defaults per channel. Metrics of a
   * single `metric_type` only — Meta rejects a mixed list.
   */
  metrics: string | null,
  /**
   * day / week / days_28 — defaults to day.
   */
  period: string | null,
  /**
   * `total_value` for metrics Meta only reports as a total; omit for
   * time-series ones. Only read alongside `metrics`.
   */
  metric_type: string | null,
};
