// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../domain/Channel";
import type { ChannelFamily } from "../domain/ChannelFamily";
import type { ResponseWindow } from "../domain/ResponseWindow";
import type { Transport } from "../domain/Transport";

/**
 * One channel and the platform rules the hub enforces on it.
 */
export type ChannelRule = {
  channel: Channel,
  family: ChannelFamily,
  transport: Transport,
  /**
   * What a conversation accepts after the contact's last inbound message;
   * the send routes refuse what it does not pass.
   */
  response_window: ResponseWindow,
};
