// This file was generated by tapir. Do not edit this file manually.

export type ConnectConfirmRequest = {
  token: string,
  /**
   * The `external_id`s to register — pages and instagram accounts are
   * selected independently.
   */
  external_ids: Array<string>,
};
