// This file was generated by tapir. Do not edit this file manually.
import type { InstagramAltTarget } from "./InstagramAltTarget";
import type { Uid } from "../primitives/Uid";

/**
 * Which login opens the grant: the hub's own Meta app (every page and linked
 * instagram account the admin grants, reviewed together) or the alternate
 * gateway's, one channel per grant while the hub's app awaits review. A login
 * may name the group's account it reconnects, so the grant lands on that
 * account and refreshes it in place; otherwise every selected account is
 * registered anew, however many times the same page or number is already
 * connected — each connection is its own account, sharing nothing with the
 * others.
 */
export type ConnectSocialAccountRequest = {
  "login": "meta",
  group_uid: Uid,
  /**
   * The group's official facebook or instagram account this login
   * reconnects, if any.
   */
  social_account_uid: Uid | null,
} | {
  "login": "facebook_alt",
  group_uid: Uid,
  /**
   * The group's alt account this login reconnects, if any.
   */
  social_account_uid: Uid | null,
} | {
  "login": "instagram_alt",
  group_uid: Uid,
  target: InstagramAltTarget,
} | {
  "login": "whatsapp_alt",
  group_uid: Uid,
  /**
   * The group's alt account this login reconnects, if any.
   */
  social_account_uid: Uid | null,
};
