// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ConnectWhatsappRequest = {
  group_uid: Uid,
  /**
   * The WhatsApp Business Account id (from Business Manager).
   */
  waba_id: string,
  /**
   * A permanent system user token holding `whatsapp_business_messaging` +
   * `whatsapp_business_management`, generated once in Business Manager.
   */
  access_token: string,
};
