// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ConnectStevoResponse = {
  social_account_uid: Uid,
  connected: boolean,
  /**
   * False until a phone is paired — fetch the QR (or a pairing code) next.
   */
  logged_in: boolean,
};
