// This file was generated by tapir. Do not edit this file manually.

export type ConnectReviewQuery = {
  /**
   * The review token from the callback redirect (`?review=<token>`).
   */
  token: string,
};
