// This file was generated by tapir. Do not edit this file manually.
import type { GrantAccount } from "./GrantAccount";
import type { RemovedAccess } from "./RemovedAccess";

export type ConnectReviewResponse = {
  /**
   * Every account the grant covers, facebook pages and their linked
   * instagram accounts alike.
   */
  accounts: Array<GrantAccount>,
  /**
   * Group accounts whose access died on the Meta side.
   */
  removed: Array<RemovedAccess>,
};
