// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ConnectStevoRequest = {
  group_uid: Uid,
  /**
   * The Stevo server base URL (white-label domain), e.g.
   * `https://api.seudominio.com`.
   */
  server_url: string,
  /**
   * The instance apikey from the Stevo panel.
   */
  api_key: string,
  /**
   * An optional label of your own. The account's `name` always comes from the
   * paired profile — this is the field you control.
   */
  name: string | null,
};
