// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type ExposureQuery = {
  /**
   * Start of the period; defaults to seven days before `until`.
   */
  since: Timestamp | null,
  /**
   * End of the period; defaults to now.
   */
  until: Timestamp | null,
};
