// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../domain/Channel";

/**
 * One account the stashed grant covers, for the selection screen.
 */
export type GrantAccount = {
  channel: Channel,
  external_id: string,
  name: string,
  username: string | null,
  /**
   * How many accounts of this identity the target group already holds;
   * confirming adds another, independent one, unless the login named the
   * account it reconnects.
   */
  connections: number,
};
