// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../types/Channel";

/**
 * One account the stashed grant covers, for the selection screen.
 */
export type GrantAccount = {
  channel: Channel,
  external_id: string,
  name: string,
  username: string | null,
  /**
   * Already registered in the target group — confirming it refreshes the
   * stored token and display fields.
   */
  connected: boolean,
  /**
   * Registered in another group: shown locked, never selectable (accounts
   * cannot be moved between groups by a connect).
   */
  other_group: boolean,
};
