// This file was generated by tapir. Do not edit this file manually.

/**
 * Progress of a native QR pairing.
 */
export type NativePairingStatus = "pairing" | "paired" | "failed";

/** Every `NativePairingStatus`, in declaration order. */
export const NATIVE_PAIRING_STATUS = ["pairing", "paired", "failed"] as const satisfies readonly NativePairingStatus[];
