// This file was generated by tapir. Do not edit this file manually.
import type { NativePairingStatus } from "./NativePairingStatus";
import type { Uid } from "../primitives/Uid";

export type NativePairingStatusResponse = {
  status: NativePairingStatus,
  /**
   * Set once `status` is `paired`.
   */
  social_account_uid: Uid | null,
};
