// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type NativeQrResponse = {
  /**
   * The QR code to render, or null until the first code arrives and while a
   * fresh batch is being fetched after a renewal.
   */
  qr: string | null,
  /**
   * The instant the code stops being accepted, about a minute after it
   * arrived. Past it the code is dead, nothing replaces it on its own, and
   * `socialAccount.nativeRenewQr` asks the phone for a fresh one.
   */
  expires_at: Timestamp | null,
};
