// This file was generated by tapir. Do not edit this file manually.

export type NativeQrResponse = {
  /**
   * The QR code to render, or null until the first code arrives.
   */
  qr: string | null,
};
