// This file was generated by tapir. Do not edit this file manually.

export type RefreshProfileResponse = {
  /**
   * Whether the platform reported a name or picture different from the stored one.
   */
  changed: boolean,
};
