// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../domain/Channel";
import type { Uid } from "../primitives/Uid";

/**
 * A group account whose stored token no longer works — access was removed
 * on the Meta side. Flagged `needs_reauth`; a connect naming it by
 * `social_account_uid` is the cure.
 */
export type RemovedAccess = {
  social_account_uid: Uid,
  channel: Channel,
  name: string,
};
