// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-agnostic whatsapp session state, precomputed so the frontend maps
 * each value straight to a badge and action — no per-channel logic.
 */
export type SessionStatus = "connected" | "disconnected" | "unpaired" | "unavailable";

/** Every `SessionStatus`, in declaration order. */
export const SESSION_STATUS = ["connected", "disconnected", "unpaired", "unavailable"] as const satisfies readonly SessionStatus[];
