// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100000 } from "../primitives/Number1_100000";

export type SetSocialAccountConversationCapRequest = {
  /**
   * Most conversations the hub may open on the account in any 24 hours;
   * `null` lifts the cap.
   */
  cap: Number1_100000 | null,
};
