// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";

export type SetSocialAccountAliasRequest = {
  /**
   * The operator's own label for this account; `null` clears it and the
   * platform's name stands alone.
   */
  alias: Name | null,
};
