// This file was generated by tapir. Do not edit this file manually.
import type { PresencePolicy } from "../domain/PresencePolicy";

export type SetSocialAccountPresenceRequest = {
  policy: PresencePolicy,
};
