// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type SetSocialAccountGroupRequest = {
  /**
   * The group the account moves into.
   */
  group_uid: Uid,
  /**
   * Carry along the GoHighLevel locations, campaigns and contact imports that
   * act only on this account. Without it, the move is refused while any exist.
   */
  move_references: boolean,
};
