// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type StartNativePairingResponse = {
  /**
   * Poll `native/{handle}/qr` and `native/{handle}/status` with this.
   */
  pairing_handle: Uid,
};
