// This file was generated by tapir. Do not edit this file manually.

export type StevoPairResponse = {
  /**
   * The code the user types under "link with phone number" on the device.
   */
  code: string,
};
