// This file was generated by tapir. Do not edit this file manually.

export type StevoQrResponse = {
  /**
   * The QR payload to render (data-URI image or raw code, as the gateway
   * provides it).
   */
  qr: string,
};
