// This file was generated by tapir. Do not edit this file manually.
import type { Phone } from "../primitives/Phone";

export type StevoPairRequest = {
  /**
   * The phone to pair, in E.164 (`+<country code><number>`).
   */
  phone: Phone,
};
