// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { AudienceRequest } from "../../types/campaign/AudienceRequest";
import type { CampaignDetail } from "../../types/campaign/CampaignDetail";
import type { CampaignRecipient } from "../../types/database/CampaignRecipient";
import type { CampaignStats } from "../../types/campaign/CampaignStats";
import type { CreateCampaignRequest } from "../../types/campaign/CreateCampaignRequest";
import type { ListCampaignsQuery } from "../../types/campaign/ListCampaignsQuery";
import type { ListRecipientsQuery } from "../../types/campaign/ListRecipientsQuery";
import type { MessageWithContext } from "../../types/message/MessageWithContext";
import type { PreflightReport } from "../../types/campaign/PreflightReport";
import type { RemoveRecipientsRequest } from "../../types/campaign/RemoveRecipientsRequest";
import type { SetAccountsRequest } from "../../types/campaign/SetAccountsRequest";
import type { TestSendRequest } from "../../types/campaign/TestSendRequest";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateCampaignRequest } from "../../types/campaign/UpdateCampaignRequest";

export const campaign = {
  /**
   * Append an audience to the end of the queue — the same sources as a
   * build, added to what is there. Draft, paused or done; conversations
   * already in the ledger (queued or reached) are skipped.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  addRecipients: Tapi.post<{ path: { campaign_uid: Uid }; body: AudienceRequest; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/recipient",
  }),
  /**
   * Build (or rebuild) the audience: the source resolves to numbers, each
   * assigned an account (balanced, preferring one that already has the
   * conversation), frozen as the recipient ledger. Draft only — past a start
   * the ledger is the record of who was reached; use `addRecipients`.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  buildAudience: Tapi.post<{ path: { campaign_uid: Uid }; body: AudienceRequest; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/audience",
  }),
  /**
   * Cancel the campaign: queued recipients become `canceled`, and campaign
   * messages still waiting in the send queue are pulled back. Terminal;
   * messages already sent stay.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  cancel: Tapi.post<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/cancel",
  }),
  /**
   * Create a draft campaign in a group. Its accounts are the group's whatsapp
   * accounts (native or Stevo, mixed freely); nothing sends until templates,
   * accounts and an audience exist and `start` passes the preflight.
   *
   * Requires `ManageCampaigns` in the target group; group-scoped API keys create into their own group, others must name it.
   */
  create: Tapi.post<{ body: CreateCampaignRequest; response: CampaignDetail }>()({
    endpoint: "/campaign",
  }),
  /**
   * Delete a campaign and its ledger. Refused while running — pause or cancel
   * first. Messages already sent stay in their conversations.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  delete: Tapi.delete<{ path: { campaign_uid: Uid }; response: null }>()({
    endpoint: "/campaign/:campaign_uid",
  }),
  /**
   * One campaign with its derived counters — the page's poll.
   *
   * Requires `ViewCampaigns` in the campaign's group.
   */
  get: Tapi.get<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid",
  }),
  /**
   * List campaigns, newest first, optionally one group's.
   *
   * Requires `ViewCampaigns`; the list covers only campaigns of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListCampaignsQuery; response: Array<CampaignDetail> }>()({
    endpoint: "/campaign",
  }),
  /**
   * Pause the drip: queued recipients stay queued, nothing more is sent until
   * a resume. Messages already in the send queue still go out.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  pause: Tapi.post<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/pause",
  }),
  /**
   * The start gate's dry run: hard errors, foreseeable skips, and the sending
   * estimate.
   *
   * Requires `ViewCampaigns` in the campaign's group.
   */
  preflight: Tapi.get<{ path: { campaign_uid: Uid }; response: PreflightReport }>()({
    endpoint: "/campaign/:campaign_uid/preflight",
  }),
  /**
   * A page of the recipient ledger in drip order, optionally one status.
   *
   * Requires `ViewCampaigns` in the campaign's group.
   */
  recipients: Tapi.get<{ path: { campaign_uid: Uid }; query: ListRecipientsQuery; response: Array<CampaignRecipient> }>()({
    endpoint: "/campaign/:campaign_uid/recipient",
  }),
  /**
   * Hand the whole queue out again across the current accounts: balanced,
   * preferring an account that already has each number's conversation. For
   * after accounts were added, or a queue that grew lopsided. Draft, paused
   * and done only.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  redistribute: Tapi.post<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/redistribute",
  }),
  /**
   * Drop queued recipients from the audience. Draft, paused or done; rows that
   * already ran stay as history.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  removeRecipients: Tapi.post<{ path: { campaign_uid: Uid }; body: RemoveRecipientsRequest; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/recipient/remove",
  }),
  /**
   * Resume a paused drip where it stood.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  resume: Tapi.post<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/resume",
  }),
  /**
   * Replace the participating account set. Draft, paused and done only; every
   * account must be a whatsapp (native or Stevo) account of the campaign's
   * group. Queued recipients of an account taken out are handed to the
   * accounts that remain, balanced and preferring one that already knows
   * them; rows that already ran stay. The set may be empty — the queue then
   * waits for the next account change — and the campaign cannot start until
   * it has one.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  setAccounts: Tapi.put<{ path: { campaign_uid: Uid }; body: SetAccountsRequest; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/account",
  }),
  /**
   * Start the drip, from draft or from done — a done campaign restarts on
   * whatever is still queued, never on who was already reached. Runs the
   * preflight and refuses on any error; from then on the dispatcher sends
   * one message per interval inside the window.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  start: Tapi.post<{ path: { campaign_uid: Uid }; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid/start",
  }),
  /**
   * Delivery truth: recipient status crossed with each message's own platform
   * status, plus the reply count.
   *
   * Requires `ViewCampaigns` in the campaign's group.
   */
  stats: Tapi.get<{ path: { campaign_uid: Uid }; response: CampaignStats }>()({
    endpoint: "/campaign/:campaign_uid/stats",
  }),
  /**
   * Send one template to one conversation, now, outside any schedule — the
   * operator's own eyes on the rendered result.
   *
   * Requires `ManageCampaigns` in the campaign's group; the conversation must belong to the same group and channel.
   */
  test: Tapi.post<{ path: { campaign_uid: Uid }; body: TestSendRequest; response: MessageWithContext }>()({
    endpoint: "/campaign/:campaign_uid/test",
  }),
  /**
   * Replace the campaign's schedule, ceilings and rotation. Draft, paused and
   * done only — a running drip is retuned by pausing first.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  update: Tapi.put<{ path: { campaign_uid: Uid }; body: UpdateCampaignRequest; response: CampaignDetail }>()({
    endpoint: "/campaign/:campaign_uid",
  }),
};
