// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { Channel } from "../../../types/types/Channel";
import type { ChannelPacingRule } from "../../../types/database/ChannelPacingRule";
import type { CreateChannelPacingRequest } from "../../../types/rate_limit/CreateChannelPacingRequest";
import type { CreateChannelPacingResponse } from "../../../types/rate_limit/CreateChannelPacingResponse";
import type { UpdateChannelPacingRequest } from "../../../types/rate_limit/UpdateChannelPacingRequest";

export const pacing = {
  /**
   * Start pacing outbound sends on a channel. Every send is queued either way —
   * `message.send` stores the message as `pending` and returns immediately — so
   * a rule decides how fast the per-account queue drains, not whether one is
   * used. Without a rule (the default) the queue drains as fast as it can.
   *
   * Requires `CreateRateLimits`, which only platform staff hold.
   */
  create: Tapi.post<{ body: CreateChannelPacingRequest; response: CreateChannelPacingResponse }>()({
    endpoint: "/rate-limit/pacing",
  }),
  /**
   * Stop pacing a channel: its queue drains as fast as it can again. Messages
   * already queued still drain, without the delay.
   *
   * Requires `DeleteRateLimits`, which only platform staff hold.
   */
  delete: Tapi.delete<{ path: { channel: Channel }; response: null }>()({
    endpoint: "/rate-limit/pacing/:channel",
  }),
  /**
   * Fetch a single channel pacing rule by uid.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { channel: Channel }; response: ChannelPacingRule }>()({
    endpoint: "/rate-limit/pacing/:channel",
  }),
  /**
   * List every channel pacing rule. Channels with no rule are unpaced.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<ChannelPacingRule> }>()({
    endpoint: "/rate-limit/pacing",
  }),
  /**
   * Update a channel's pacing. Takes effect on the next send; messages already
   * queued keep draining under the new timing.
   *
   * Requires `UpdateRateLimits`, which only platform staff hold.
   */
  update: Tapi.put<{ path: { channel: Channel }; body: UpdateChannelPacingRequest; response: null }>()({
    endpoint: "/rate-limit/pacing/:channel",
  }),
};
