// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../../runtime";
import type { UserMfaEnrollConfirmRequest } from "../../../../types/user_mfa/UserMfaEnrollConfirmRequest";
import type { UserMfaEnrollEmailStartRequest } from "../../../../types/user_mfa/UserMfaEnrollEmailStartRequest";
import type { UserMfaEnrollSessionResponse } from "../../../../types/user_mfa/UserMfaEnrollSessionResponse";

export const email = {
  /**
   * Confirm bootstrap email-factor enrollment with a code and, on success, mint a user session token.
   *
   * Public — no authentication required; the request is gated solely by the ephemeral enrollment token in the body.
   */
  confirm: Tapi.post<{ body: UserMfaEnrollConfirmRequest; response: UserMfaEnrollSessionResponse }>()({
    endpoint: "/user-session/mfa/enroll/email/confirm",
  }),
  /**
   * Begin email-factor enrollment during forced bootstrap, emailing a one-time code.
   *
   * Public — no authentication required; the request is gated by the ephemeral enrollment token in the body and by the per-IP and per-token code-dispatch throttle.
   */
  start: Tapi.post<{ body: UserMfaEnrollEmailStartRequest; response: null }>()({
    endpoint: "/user-session/mfa/enroll/email/start",
  }),
};
