// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { GhlDeliveryPayload } from "../../../types/ghl/GhlDeliveryPayload";

export const ghl = {
  /**
   * GoHighLevel conversation-provider delivery webhook: sends the message a
   * location placed on the provider out on the whatsapp account it is linked
   * to. Anything the bridge can never deliver is answered 200 so GoHighLevel
   * stops retrying it; a failed send answers 5xx so it does not.
   *
   * Public — no authentication required; authorization comes from the secret path segment configured as the marketplace app's delivery URL.
   */
  receive: Tapi.post<{ path: { secret: string }; body: GhlDeliveryPayload; response: null }>()({
    endpoint: "/webhook/ghl/:secret",
  }),
};
