// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../../runtime";
import type { UserMfaEnrollTotpStartResponse } from "../../../../types/user_mfa/UserMfaEnrollTotpStartResponse";
import type { UserMfaMgmtTotpConfirmRequest } from "../../../../types/user_mfa/UserMfaMgmtTotpConfirmRequest";

export const totp = {
  /**
   * Confirm self-service TOTP enrollment with a code.
   *
   * Authenticated user acting on their own factors; no permission required.
   */
  confirm: Tapi.post<{ body: UserMfaMgmtTotpConfirmRequest; response: null }>()({
    endpoint: "/user-mfa/factor/totp/confirm",
  }),
  /**
   * Begin self-service TOTP enrollment, returning the secret, otpauth URI, and QR code.
   *
   * Authenticated user acting on their own factors; no permission required.
   */
  start: Tapi.post<{ response: UserMfaEnrollTotpStartResponse }>()({
    endpoint: "/user-mfa/factor/totp/start",
  }),
};
