// This file was generated by tapi. Do not edit manually.

import { ghl } from "./ghl";
import { meta } from "./meta";
import { stevo } from "./stevo";

export const webhook = {
  ghl,
  meta,
  stevo,
};
