// This file was generated by tapi. Do not edit manually.

import { gateway } from "./gateway";
import { ghl } from "./ghl";
import { meta } from "./meta";

export const webhook = {
  gateway,
  ghl,
  meta,
};
