// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateTemplateRequest } from "../../types/message/CreateTemplateRequest";
import type { CreateTemplateResponse } from "../../types/message/CreateTemplateResponse";
import type { DeleteTemplateQuery } from "../../types/message/DeleteTemplateQuery";
import type { ListTemplatesQuery } from "../../types/message/ListTemplatesQuery";
import type { TemplateResponse } from "../../types/message/TemplateResponse";

export const whatsappTemplate = {
  /**
   * Submit a whatsapp message template for Meta's review; once APPROVED it is
   * sendable as `template` content.
   *
   * Requires `ManageTemplates` in the account's group.
   */
  create: Tapi.post<{ body: CreateTemplateRequest; response: CreateTemplateResponse }>()({
    endpoint: "/whatsapp/template",
  }),
  /**
   * Delete a whatsapp message template by name (all languages, or one specific
   * `hsm_id`).
   *
   * Requires `ManageTemplates` in the account's group.
   */
  delete: Tapi.delete<{ query: DeleteTemplateQuery; response: null }>()({
    endpoint: "/whatsapp/template",
  }),
  /**
   * List the WABA's whatsapp message templates, all statuses (only APPROVED
   * ones are sendable).
   *
   * Requires `ViewTemplates` in the account's group.
   */
  list: Tapi.get<{ query: ListTemplatesQuery; response: Array<TemplateResponse> }>()({
    endpoint: "/whatsapp/template",
  }),
};
