// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";

export type UserInvitePreviewResponse = {
  email: Email,
  /**
   * No account holds this address yet, so accepting means creating one. When
   * false the recipient signs in first and accepts from the dialog.
   */
  requires_account: boolean,
};
