// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipRole } from "../domain/MembershipRole";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type UserInviteDetailResponse = {
  email: Email,
  group_uid: Uid,
  group_name: Name,
  /**
   * The group's logo at a signed address the invited account may fetch
   * before it holds `ViewGroups`; valid for 30 minutes from this answer.
   */
  logo_url: string | null,
  role: MembershipRole,
  invited_by_name: Name,
  expires_at: Timestamp,
};
