// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipRole } from "../types/MembershipRole";
import type { Name } from "../primitives/Name";
import type { Uid } from "../primitives/Uid";

/**
 * `group_uid` and `role` are a tied pair: both name the membership accepting
 * the invitation grants, both absent invites to the platform alone. Half a
 * pair is refused.
 */
export type UserInviteSendRequest = {
  email: Email,
  name: Name,
  group_uid: Uid | null,
  role: MembershipRole | null,
};
