// This file was generated by tapir. Do not edit this file manually.
import type { Password8_128_F_F_T_F } from "../primitives/Password8_128_F_F_T_F";
import type { Uid } from "../primitives/Uid";

export type UserInviteAcceptRequest = {
  token: Uid,
  password: Password8_128_F_F_T_F,
};
