// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipRole } from "../types/MembershipRole";
import type { Uid } from "../primitives/Uid";

/**
 * `group_uid` and `role` are a tied pair: both name the membership accepting
 * the invitation grants, both absent invites to the platform alone. Half a
 * pair is refused.
 *
 * No name: the sender is naming a mailbox, not a person, and the account's
 * name is chosen by whoever answers it.
 */
export type UserInviteSendRequest = {
  email: Email,
  group_uid: Uid | null,
  role: MembershipRole | null,
};
