// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";

export const stevo = {
  /**
   * Stevo webhook receiver: authenticates the delivery by the echoed instance
   * token, stores normalized messages (deduplicating redeliveries), applies
   * receipts/reactions/edits/revokes, and enqueues CRM fan-out events.
   *
   * Public — no authentication required; authorization comes from the instance token echoed inside the payload.
   */
  receive: Tapi.post<{ response: null }>()({
    endpoint: "/webhook/stevo",
  }),
};
