// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { UserMfaFactorRow } from "../../../types/user_mfa/UserMfaFactorRow";
import type { UserMfaKind } from "../../../types/domain/UserMfaKind";
import { email } from "./email";
import { totp } from "./totp";

export const factor = {
  /**
   * Delete one of the caller's own MFA factors, refusing to remove their last confirmed factor.
   *
   * Authenticated user acting on their own factors; no permission required.
   */
  delete: Tapi.delete<{ path: { kind: UserMfaKind }; response: null }>()({
    endpoint: "/user-mfa/factor/:kind",
  }),
  /**
   * List the caller's own enrolled MFA factors.
   *
   * Authenticated user acting on their own factors; no permission required.
   */
  list: Tapi.get<{ response: Array<UserMfaFactorRow> }>()({
    endpoint: "/user-mfa/factor",
  }),
  email,
  totp,
};
