// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100 } from "../primitives/Number1_100";
import type { Text0_8000 } from "../primitives/Text0_8000";
import type { Uid } from "../primitives/Uid";

export type MessageSearchQuery = {
  q: Text0_8000,
  /**
   * Narrow to these groups, each one the caller may see; omit for everything the caller may see.
   */
  group_uids: Array<Uid> | null,
  /**
   * Narrow to these accounts, each one in scope; naming any account overrides the groups.
   */
  social_account_uids: Array<Uid> | null,
  /**
   * Search inside this conversation only.
   */
  conversation_uid: Uid | null,
  /**
   * Keyset cursor: only hits with `id` strictly smaller are returned.
   */
  before_id: number | null,
  limit: Number1_100 | null,
};
