// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100 } from "../primitives/Number1_100";
import type { Text0_8000 } from "../primitives/Text0_8000";
import type { Uid } from "../primitives/Uid";

export type MessageSearchQuery = {
  q: Text0_8000,
  group_uid: Uid | null,
  social_account_uid: Uid | null,
  /**
   * Search inside this conversation only.
   */
  conversation_uid: Uid | null,
  /**
   * Keyset cursor: only hits with `id` strictly smaller are returned.
   */
  before_id: number | null,
  limit: Number1_100 | null,
};
