// This file was generated by tapir. Do not edit this file manually.
import type { Number1_50 } from "../primitives/Number1_50";
import type { Text8000 } from "../primitives/Text8000";

export type SearchQuery = {
  q: Text8000,
  limit: Number1_50 | null,
};
