// This file was generated by tapir. Do not edit this file manually.
import type { Number1_50 } from "../primitives/Number1_50";
import type { Text0_8000 } from "../primitives/Text0_8000";

export type SearchQuery = {
  q: Text0_8000,
  limit: Number1_50 | null,
};
