// This file was generated by tapir. Do not edit this file manually.
import type { Number1_50 } from "../primitives/Number1_50";
import type { SearchKind } from "../types/SearchKind";
import type { Text0_8000 } from "../primitives/Text0_8000";

export type SearchQuery = {
  q: Text0_8000,
  /**
   * Hits per kind (1..=50, default 10) — a preview cap, not a page.
   */
  limit: Number1_50 | null,
  /**
   * Only these kinds; absent or empty means every kind.
   */
  kinds: Array<SearchKind> | null,
};
