// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CalendarEventQuery } from "../../types/google_account/CalendarEventQuery";
import type { CalendarPage } from "../../types/google/CalendarPage";
import type { Event } from "../../types/google/Event";
import type { EventInput } from "../../types/google/EventInput";
import type { EventPage } from "../../types/google/EventPage";
import type { FreeBusyRequest } from "../../types/google_account/FreeBusyRequest";
import type { FreeBusyResponse } from "../../types/google_account/FreeBusyResponse";
import type { ListCalendarEventsQuery } from "../../types/google_account/ListCalendarEventsQuery";
import type { ListCalendarsQuery } from "../../types/google_account/ListCalendarsQuery";
import type { Uid } from "../../types/primitives/Uid";

export const calendar = {
  /**
   * Create an event on a calendar the account can write to.
   *
   * Requires `ManageCalendars` in the account's group.
   */
  createEvent: Tapi.post<{ path: { social_account_uid: Uid }; query: CalendarEventQuery; body: EventInput; response: Event }>()({
    endpoint: "/calendar/:social_account_uid/event",
  }),
  /**
   * Delete (cancel) an event; deleting an already-cancelled event succeeds.
   *
   * Requires `ManageCalendars` in the account's group.
   */
  deleteEvent: Tapi.delete<{ path: { social_account_uid: Uid; event_id: string }; query: CalendarEventQuery; response: null }>()({
    endpoint: "/calendar/:social_account_uid/event/:event_id",
  }),
  /**
   * Busy intervals for a set of calendars within a time range. A calendar
   * that cannot be read carries an `error` — never treat it as free.
   *
   * Requires `ViewCalendars` in the account's group.
   */
  freeBusy: Tapi.post<{ path: { social_account_uid: Uid }; body: FreeBusyRequest; response: FreeBusyResponse }>()({
    endpoint: "/calendar/:social_account_uid/freebusy",
  }),
  /**
   * Get one event.
   *
   * Requires `ViewCalendars` in the account's group.
   */
  getEvent: Tapi.get<{ path: { social_account_uid: Uid; event_id: string }; query: CalendarEventQuery; response: Event }>()({
    endpoint: "/calendar/:social_account_uid/event/:event_id",
  }),
  /**
   * List the calendars the account can see — for pickers. Follow
   * `next_page_token` for more.
   *
   * Requires `ViewCalendars` in the account's group.
   */
  listCalendars: Tapi.get<{ path: { social_account_uid: Uid }; query: ListCalendarsQuery; response: CalendarPage }>()({
    endpoint: "/calendar/:social_account_uid/calendar",
  }),
  /**
   * List a calendar's events within a time range, expanded to single
   * instances and ordered by start. Follow `next_page_token` for more.
   *
   * Requires `ViewCalendars` in the account's group.
   */
  listEvents: Tapi.get<{ path: { social_account_uid: Uid }; query: ListCalendarEventsQuery; response: EventPage }>()({
    endpoint: "/calendar/:social_account_uid/event",
  }),
  /**
   * Patch an event: only the fields sent are changed — an omitted field is
   * kept, never cleared.
   *
   * Requires `ManageCalendars` in the account's group.
   */
  updateEvent: Tapi.patch<{ path: { social_account_uid: Uid; event_id: string }; query: CalendarEventQuery; body: EventInput; response: Event }>()({
    endpoint: "/calendar/:social_account_uid/event/:event_id",
  }),
};
