// This file was generated by permission catalog codegen. Do not edit manually.
//
// Generated from the `permissions!` catalog in
// crates/core/types/src/permission.rs — grouping, pt-BR labels, and
// required-permission rows are backend-owned; the frontend renders this
// catalog verbatim.
import type { UserPermission } from "./types/types/UserPermission";

export interface PermissionGroup {
  readonly id: string;
  readonly label: string;
  readonly perms: readonly UserPermission[];
}

export const PERMISSION_GROUPS: readonly PermissionGroup[] = [
  {
    id: "groups",
    label: "Grupos",
    perms: ["view_groups", "create_groups", "update_groups", "toggle_group_enabled", "delete_groups"],
  },
  {
    id: "members",
    label: "Membros",
    perms: ["view_members", "add_members", "set_member_role", "remove_members"],
  },
  {
    id: "users",
    label: "Usuários",
    perms: ["view_users", "provision_users", "invite_users", "view_invites", "update_users", "activate_users", "delete_users", "view_user_sessions", "revoke_user_sessions", "reset_user_mfa", "set_super_admin"],
  },
  {
    id: "social_accounts",
    label: "Contas sociais",
    perms: ["view_social_accounts", "connect_social_accounts", "update_social_accounts", "delete_social_accounts"],
  },
  {
    id: "messages",
    label: "Conversas",
    perms: ["view_messages", "send_messages", "manage_messages", "import_contacts"],
  },
  {
    id: "campaigns",
    label: "Campanhas",
    perms: ["view_campaigns", "manage_campaigns"],
  },
  {
    id: "posts",
    label: "Publicações",
    perms: ["view_posts", "publish_posts", "update_posts", "delete_posts"],
  },
  {
    id: "comments",
    label: "Comentários",
    perms: ["view_comments", "reply_comments", "moderate_comments"],
  },
  {
    id: "insights",
    label: "Métricas",
    perms: ["view_insights"],
  },
  {
    id: "templates",
    label: "Modelos WhatsApp",
    perms: ["view_templates", "manage_templates"],
  },
  {
    id: "calendars",
    label: "Agendas",
    perms: ["view_calendars", "manage_calendars"],
  },
  {
    id: "business",
    label: "Google Business",
    perms: ["view_business", "manage_business"],
  },
  {
    id: "media",
    label: "Mídia",
    perms: ["upload_media"],
  },
  {
    id: "webhooks",
    label: "Webhooks",
    perms: ["view_webhook", "manage_webhook"],
  },
  {
    id: "api_keys",
    label: "API Keys",
    perms: ["view_api_keys", "create_api_keys", "update_api_keys", "grant_api_key_permissions", "rotate_api_keys", "revoke_api_keys"],
  },
  {
    id: "audit",
    label: "Auditoria",
    perms: ["view_audit_logs"],
  },
  {
    id: "limits",
    label: "Limites",
    perms: ["view_rate_limits", "create_rate_limits", "update_rate_limits", "delete_rate_limits"],
  },
  {
    id: "email",
    label: "E-mail",
    perms: ["manage_email_queue"],
  },
  {
    id: "pulse",
    label: "Pulse",
    perms: ["view_pulse"],
  },
  {
    id: "issues",
    label: "Problemas",
    perms: ["view_issues", "manage_issues"],
  },
];

export const PERMISSION_LABEL: Record<UserPermission, string> = {
  view_groups: "Visualizar grupos",
  create_groups: "Criar grupos",
  update_groups: "Atualizar grupos",
  toggle_group_enabled: "Habilitar / desabilitar",
  delete_groups: "Excluir grupos",
  view_members: "Visualizar membros",
  add_members: "Adicionar membros",
  set_member_role: "Alterar papel",
  remove_members: "Remover membros",
  view_users: "Visualizar usuários",
  provision_users: "Provisionar usuários",
  invite_users: "Enviar convites",
  view_invites: "Visualizar convites",
  update_users: "Atualizar usuários",
  activate_users: "Ativar / desativar",
  delete_users: "Excluir usuários",
  view_user_sessions: "Visualizar sessões",
  revoke_user_sessions: "Revogar sessões",
  reset_user_mfa: "Redefinir MFA",
  set_super_admin: "Definir super admin",
  view_social_accounts: "Visualizar contas sociais",
  connect_social_accounts: "Conectar contas sociais",
  update_social_accounts: "Atualizar contas sociais",
  delete_social_accounts: "Excluir contas sociais",
  view_messages: "Visualizar mensagens",
  send_messages: "Enviar mensagens",
  manage_messages: "Excluir conversas e histórico",
  import_contacts: "Importar contatos",
  view_campaigns: "Visualizar campanhas",
  manage_campaigns: "Gerenciar campanhas",
  view_posts: "Visualizar publicações",
  publish_posts: "Publicar",
  update_posts: "Atualizar publicações",
  delete_posts: "Excluir publicações",
  view_comments: "Visualizar comentários",
  reply_comments: "Comentar, responder e curtir",
  moderate_comments: "Ocultar e excluir comentários",
  view_insights: "Visualizar métricas",
  view_templates: "Visualizar modelos",
  manage_templates: "Gerenciar modelos",
  view_calendars: "Visualizar agendas e eventos",
  manage_calendars: "Gerenciar eventos de agenda",
  view_business: "Visualizar perfil de negócio",
  manage_business: "Gerenciar perfil de negócio",
  upload_media: "Enviar mídia",
  view_webhook: "Visualizar webhook de eventos",
  manage_webhook: "Gerenciar webhook de eventos",
  view_api_keys: "Visualizar chaves",
  create_api_keys: "Criar chaves",
  update_api_keys: "Atualizar chaves",
  grant_api_key_permissions: "Conceder permissões",
  rotate_api_keys: "Rotacionar chaves",
  revoke_api_keys: "Revogar chaves",
  view_audit_logs: "Visualizar auditoria",
  view_rate_limits: "Visualizar rate limits",
  create_rate_limits: "Criar rate limits",
  update_rate_limits: "Atualizar rate limits",
  delete_rate_limits: "Excluir rate limits",
  manage_email_queue: "Gerenciar fila de e-mail",
  view_pulse: "Visualizar Pulse",
  view_issues: "Visualizar problemas",
  manage_issues: "Gerenciar problemas",
};

/**
 * The catalog's `requires` rows (`Permission::requires`): a permission may
 * only be granted together with these, because holding it already exercises
 * their capabilities through an internal path. The backend rejects grant sets
 * that are not closed under this relation.
 */
export const PERMISSION_REQUIRES: Partial<Record<UserPermission, readonly UserPermission[]>> = {
  import_contacts: ["send_messages"],
  manage_campaigns: ["send_messages"],
};
