// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ApproveRequest = {
  client_id: Uid,
  redirect_uri: string,
  state: string | null,
  code_challenge: string,
  code_challenge_method: string,
  response_type: string | null,
  resource: string | null,
};
