// This file was generated by tapir. Do not edit this file manually.

export type ApproveResponse = {
  /**
   * The client's redirect uri with the code (and state) appended; the page navigates there.
   */
  redirect_to: string,
};
