// This file was generated by tapir. Do not edit this file manually.

export type ConsentResponse = {
  /**
   * The name the client registered under; what the consent card shows.
   */
  client_name: string,
  /**
   * The resource the token will be bound to: this server's MCP endpoint.
   */
  resource: string,
};
