// This file was generated by tapir. Do not edit this file manually.
import type { CommentCreate } from "./CommentCreate";

/**
 * Channel-tagged top-level comment: only facebook and instagram carry a
 * comment surface, so no other channel's shape deserializes. The `channel`
 * must match the account's.
 */
export type CreateCommentRequest = {
  "channel": "facebook"
} & CommentCreate | {
  "channel": "instagram"
} & CommentCreate;
