// This file was generated by tapir. Do not edit this file manually.

export type CreateCommentRequest = {
  /**
   * Platform post/media id — hub posts expose it as `external_id`, and any
   * other post of the account works too.
   */
  external_post_id: string,
  message: string,
};
