// This file was generated by tapir. Do not edit this file manually.
import type { Number1_500 } from "../primitives/Number1_500";
import type { Uid } from "../primitives/Uid";

export type ListCommentsQuery = {
  /**
   * Narrow to these groups, each one the caller may see; omit for everything the caller may see.
   */
  group_uids: Array<Uid> | null,
  /**
   * Narrow to these accounts, each one in scope; naming any account overrides the groups.
   */
  social_account_uids: Array<Uid> | null,
  /**
   * Filter to one post's comments (platform post/media id).
   */
  external_post_id: string | null,
  /**
   * Poll cursor: only comments with `id` strictly greater are returned.
   */
  since_id: number,
  limit: Number1_500 | null,
};
