// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged mention reply: mentions are an instagram surface, so no
 * other channel's shape deserializes. The `channel` must match the
 * account's.
 */
export type MentionReplyRequest = {
  "channel": "instagram",
  message: string,
};
