// This file was generated by tapir. Do not edit this file manually.

export type PrivateReplyResponse = {
  /**
   * Platform message id; the DM itself lands in the conversation via the
   * echo webhook.
   */
  mid: string,
};
