// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_3600 } from "../primitives/Number1_3600";
import type { RateLimitAction } from "../types/RateLimitAction";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type ActionRateLimitRule = {
  uid: Uid,
  action: RateLimitAction,
  max_requests: Number1_100000,
  window_seconds: Number1_3600,
  created_at: Timestamp,
  updated_at: Timestamp,
};
