// This file was generated by tapir. Do not edit this file manually.
import type { ApiKeyPermissions } from "./ApiKeyPermissions";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type ApiKey = {
  uid: Uid,
  group_uid: Uid | null,
  name: Name,
  permissions: ApiKeyPermissions,
  enabled: boolean,
  created_by: Uid,
  revoked_at: Timestamp | null,
  revoked_by: Uid | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
