// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type AuditLogStats = {
  count: number,
  success_count: number,
  failure_count: number,
  since: Timestamp | null,
  until: Timestamp | null,
};
