// This file was generated by tapir. Do not edit this file manually.
import type { CallDirection } from "../types/CallDirection";
import type { CallOutcome } from "../types/CallOutcome";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One WhatsApp voice or video call, from the moment it rings (or is placed)
 * until the platform says it ended. A live call has `ended_at` and `outcome`
 * null; both are stamped together, exactly once.
 */
export type Call = {
  /**
   * Strictly increasing insert order.
   */
  id: number,
  uid: Uid,
  group_uid: Uid,
  social_account_uid: Uid,
  conversation_uid: Uid,
  /**
   * The platform's id for this call — how bridge events find the row.
   */
  wa_call_id: string,
  direction: CallDirection,
  /**
   * Started as a video call, as opposed to upgrading to one mid-call.
   */
  video: boolean,
  /**
   * Video was active at some point, from either side.
   */
  had_video: boolean,
  /**
   * The operator who claimed the call; `None` while it is still ringing, and
   * forever on a call nobody here took.
   */
  answered_by_uid: Uid | null,
  started_at: Timestamp,
  answered_at: Timestamp | null,
  ended_at: Timestamp | null,
  outcome: CallOutcome | null,
  created_at: Timestamp,
};
