// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Comment = {
  /**
   * Strictly increasing insert order — the polling cursor.
   */
  id: number,
  uid: Uid,
  social_account_uid: Uid,
  /**
   * Local post row when the commented post was published through the hub.
   */
  post_uid: Uid | null,
  external_id: string,
  external_post_id: string,
  external_parent_id: string | null,
  from_id: string,
  from_name: string | null,
  /**
   * The account's own comments (our replies or comments made natively).
   */
  from_account: boolean,
  text: string,
  hidden: boolean,
  deleted: boolean,
  sent_at: Timestamp,
  created_at: Timestamp,
};
