// This file was generated by tapir. Do not edit this file manually.
import type { ContactImportStatus } from "../types/ContactImportStatus";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One CSV upload: the mapping the operator confirmed and where the load
 * stands. The rows (and their verdicts) live in `contact_import_row`; every
 * counter a page renders is derived from them, never stored here.
 */
export type ContactImport = {
  uid: Uid,
  group_uid: Uid,
  /**
   * The operator's name for the batch; `filename` is where it came from.
   */
  name: Name,
  filename: string,
  status: ContactImportStatus,
  /**
   * The CSV header row; `ContactImportRow::raw` indexes into it.
   */
  columns: Array<string>,
  /**
   * Column indexes the operator mapped.
   */
  phone_column: number,
  name_column: number | null,
  /**
   * The country a bare number is read against (e.g. `55`).
   */
  default_calling_code: string,
  created_by_uid: Uid | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
