// This file was generated by tapir. Do not edit this file manually.
import type { MessageContentKind } from "../types/MessageContentKind";
import type { MessageDirection } from "../types/MessageDirection";
import type { MessageSentBy } from "../types/MessageSentBy";
import type { MessageStatus } from "../types/MessageStatus";
import type { Referral } from "../types/Referral";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Conversation = {
  uid: Uid,
  social_account_uid: Uid,
  /**
   * Platform participant id (PSID / IGSID / whatsapp wa_id) — scoped to the
   * account.
   */
  participant_id: string,
  /**
   * Best-effort profile fetched from Meta on first contact.
   */
  participant_name: string | null,
  participant_username: string | null,
  participant_avatar_url: string | null,
  last_message_at: Timestamp,
  /**
   * Last inbound (participant) message — anchors whatsapp's 24h window.
   */
  last_inbound_at: Timestamp | null,
  /**
   * Inbound messages sent at or before this instant were marked seen on the
   * platform. Unread detection: `last_inbound_at > seen_up_to`.
   */
  seen_up_to: Timestamp | null,
  /**
   * Inbound messages since the conversation was last read (hub-local; a
   * platform mark-seen also clears it).
   */
  unread_count: number,
  /**
   * Denormalized newest-message preview — what a chat-list line renders.
   */
  last_message_uid: Uid | null,
  last_message_kind: MessageContentKind | null,
  last_message_text: string | null,
  last_message_direction: MessageDirection | null,
  last_message_status: MessageStatus | null,
  /**
   * Sender attribution of the previewed message (outbound only) — lets list
   * consumers detect human takeovers without fetching messages.
   */
  last_message_sent_by: MessageSentBy | null,
  /**
   * The ad the conversation last arrived from (click-to-whatsapp) — the
   * newest message-level referral, rolled up here like the last_message_*
   * columns so a chat list answers "where did this come from" directly.
   */
  referral: Referral | null,
  /**
   * When that referral arrived (the message's sent_at).
   */
  referral_at: Timestamp | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
