// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * An installed GoHighLevel location: a delivery destination owning its OAuth
 * grant plus the binding to the whatsapp account it bridges into the
 * location's SMS channel. Disconnecting deletes the row — there is no
 * `enabled` flag.
 */
export type GhlLocation = {
  uid: Uid,
  group_uid: Uid,
  /**
   * GHL's location (sub-account) id — how the delivery webhook finds the row.
   */
  location_id: string,
  /**
   * GHL's agency (company) id; empty when the grant does not carry one.
   */
  company_id: string,
  name: string,
  scope: string | null,
  /**
   * The grant went stale (`invalid_grant` on refresh) and only a reconnect
   * can revive it.
   */
  needs_reauth: boolean,
  /**
   * The social account this location bridges; `None` until an admin links one.
   */
  target_account_uid: Uid | null,
  /**
   * The contact tag added on GoHighLevel's side when a human answers from the
   * hub or the paired phone — the hook a location's workflow uses to put its
   * Conversation AI bot to sleep. `None` = the handoff is off.
   */
  handoff_tag: string | null,
  /**
   * Inbound-sync cursor into `message.id`: the target account's messages
   * beyond it still owe GHL a delivery.
   */
  last_message_id: number,
  connected_by: Uid,
  created_at: Timestamp,
  updated_at: Timestamp,
};
