// This file was generated by tapir. Do not edit this file manually.
import type { HttpRateLimitScope } from "../types/HttpRateLimitScope";
import type { Number1024_107374182400 } from "../primitives/Number1024_107374182400";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_3600 } from "../primitives/Number1_3600";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type HttpRateLimitRule = {
  uid: Uid,
  scope: HttpRateLimitScope,
  group_uid: Uid | null,
  max_requests: Number1_100000,
  max_bytes_in: Number1024_107374182400 | null,
  max_bytes_out: Number1024_107374182400 | null,
  window_seconds: Number1_3600,
  created_at: Timestamp,
  updated_at: Timestamp,
};
