// This file was generated by tapir. Do not edit this file manually.
import type { IssueCategory } from "../types/IssueCategory";
import type { IssueDetails } from "../types/IssueDetails";
import type { IssueScreenshots } from "../types/IssueScreenshots";
import type { IssueSeverity } from "../types/IssueSeverity";
import type { IssueStatus } from "../types/IssueStatus";
import type { Text8000 } from "../primitives/Text8000";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Issue = {
  id: number,
  uid: Uid,
  category: IssueCategory,
  severity: IssueSeverity,
  status: IssueStatus,
  description: Text8000,
  details: IssueDetails,
  screenshots: IssueScreenshots,
  reported_by: Uid,
  created_at: Timestamp,
  updated_at: Timestamp,
};
