// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Mention = {
  /**
   * Strictly increasing insert order — the polling cursor.
   */
  id: number,
  uid: Uid,
  social_account_uid: Uid,
  /**
   * The media where the account was mentioned (caption or comment).
   */
  external_media_id: string,
  /**
   * Set when the mention happened inside a comment.
   */
  external_comment_id: string | null,
  created_at: Timestamp,
};
