// This file was generated by tapir. Do not edit this file manually.
import type { MessageContent } from "../types/MessageContent";
import type { MessageDirection } from "../types/MessageDirection";
import type { MessageReaction } from "../types/MessageReaction";
import type { MessageSentBy } from "../types/MessageSentBy";
import type { MessageStatus } from "../types/MessageStatus";
import type { Referral } from "../types/Referral";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Message = {
  /**
   * Strictly increasing insert order — the polling cursor.
   */
  id: number,
  uid: Uid,
  conversation_uid: Uid,
  social_account_uid: Uid,
  participant_id: string,
  direction: MessageDirection,
  content: MessageContent,
  reactions: Array<MessageReaction>,
  /**
   * Local uid of the message this one replies to, when we hold it.
   */
  reply_to_uid: Uid | null,
  /**
   * The ad this message arrived from (whatsapp: official reports it as
   * `referral`, the session-backed flavors as `contextInfo.externalAdReply`).
   * Set only on the first message after an ad tap.
   */
  referral: Referral | null,
  status: MessageStatus,
  error: string | null,
  external_mid: string | null,
  /**
   * Client-supplied dedup key: a keyed retry of a failed send updates this
   * row in place instead of inserting a sibling.
   */
  idempotency_key: string | null,
  /**
   * Who produced this outbound row: a machine client through the api, a hub
   * operator, or a platform echo (paired phone / whatsapp web / meta
   * business inbox, incl. history imports). `None` on inbound rows and rows
   * stored before the field existed.
   */
  sent_by: MessageSentBy | null,
  /**
   * The api key / user uid behind `sent_by`, when it names one.
   */
  sent_by_uid: Uid | null,
  /**
   * The send sequence this queued row belongs to; `None` for every send that stands alone.
   */
  burst: string | null,
  /**
   * Set when the message text was edited on the platform.
   */
  edited_at: Timestamp | null,
  /**
   * Set when the message was revoked on the platform; the row stays.
   */
  deleted_at: Timestamp | null,
  sent_at: Timestamp,
  created_at: Timestamp,
};
