// This file was generated by tapir. Do not edit this file manually.

export type PulseDiskInventoryRow = {
  recorded_at: number,
  name: string,
  mount_point: string,
  fs_type: string,
  total_bytes: number,
  removed: boolean,
};
