// This file was generated by tapir. Do not edit this file manually.

export type PulseGpuMetricRow = {
  recorded_at: number,
  gpu_index: number,
  vram_used_bytes: number,
  vram_usage_percent: number,
  utilization_percent: number,
  memory_utilization_percent: number,
  clock_graphics_mhz: number,
  clock_memory_mhz: number,
  temperature_celsius: number,
  power_watts: number,
};
