// This file was generated by tapir. Do not edit this file manually.

export type PulseNetworkInventoryRow = {
  recorded_at: number,
  interface: string,
  mac_address: string,
  ipv4_addresses: Array<string>,
  ipv6_addresses: Array<string>,
  link_speed_mbps: number | null,
  is_physical: boolean,
  removed: boolean,
};
