// This file was generated by tapir. Do not edit this file manually.
import type { RateLimitRuleKind } from "../types/RateLimitRuleKind";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type RateLimitRule = {
  uid: Uid,
  rule: RateLimitRuleKind,
  created_at: Timestamp,
  updated_at: Timestamp,
};
