// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { Name } from "../primitives/Name";
import type { Password8_128_F_F_T_F } from "../primitives/Password8_128_F_F_T_F";

export type CreateUserRequest = {
  email: Email,
  name: Name,
  password: Password8_128_F_F_T_F,
};
