// This file was generated by tapir. Do not edit this file manually.
import type { MessageChime } from "../domain/MessageChime";

export type SetUserNotificationRequest = {
  message_chime: MessageChime,
};
