// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * A change to the caller's own notification choices, applied to every listed
 * account at once; a `null` choice stays as it is.
 */
export type SetUserAccountNotificationRequest = {
  social_account_uids: Array<Uid>,
  /**
   * New messages on these accounts ring the message sound.
   */
  message_sound: boolean | null,
  /**
   * Incoming calls on these accounts raise the call alert: popup and ringtone.
   */
  call_alert: boolean | null,
};
