// This file was generated by tapir. Do not edit this file manually.
import type { MessageChime } from "../domain/MessageChime";

/**
 * The caller's own notification choices that are not tied to one account.
 */
export type UserNotificationResponse = {
  message_chime: MessageChime,
};
