// This file was generated by tapir. Do not edit this file manually.
import type { Password8_128_F_F_T_F } from "../primitives/Password8_128_F_F_T_F";

export type UserChangePasswordRequest = {
  current_password: string,
  new_password: Password8_128_F_F_T_F,
};
