// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipResponse } from "./MembershipResponse";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";
import type { UserPermission } from "../types/UserPermission";

/**
 * The caller's own account plus everything a gating decision reads: the
 * platform-wide permission set the `super_admin` flag carries, and one entry
 * per group they belong to. A user who belongs to nowhere is ordinary — both
 * lists are simply empty.
 */
export type UserSelfResponse = {
  /**
   * Held everywhere, in every group and outside all of them: the whole
   * catalog for platform staff, empty for everyone else, whose authority
   * lives entirely in `memberships`.
   */
  permissions: Array<UserPermission>,
  memberships: Array<MembershipResponse>,
  uid: Uid,
  email: Email,
  name: Name,
  enabled: boolean,
  super_admin: boolean,
  last_seen: Timestamp | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
