// This file was generated by tapir. Do not edit this file manually.
import type { MembershipRole } from "../domain/MembershipRole";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One membership seen from the user's side — the mirror of the group roster's
 * entry, carrying the fields that name the group behind it instead of the
 * group record itself.
 */
export type UserMembershipResponse = {
  group_uid: Uid,
  /**
   * The group's name, so the panel names each group without a second call.
   */
  name: Name,
  /**
   * The group's own flag: a membership into a disabled group keeps working,
   * so the roster says so rather than hiding it.
   */
  enabled: boolean,
  role: MembershipRole,
  member_since: Timestamp,
};
