// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ContactImportDetail } from "../../types/contact_import/ContactImportDetail";
import type { ContactImportRow } from "../../types/domain/ContactImportRow";
import type { ListImportRowsQuery } from "../../types/contact_import/ListImportRowsQuery";
import type { ListImportsQuery } from "../../types/contact_import/ListImportsQuery";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateContactImportRequest } from "../../types/contact_import/UpdateContactImportRequest";
import type { UpdateImportRowRequest } from "../../types/contact_import/UpdateImportRowRequest";
import type { UploadContactImportForm } from "../../types/contact_import/UploadContactImportForm";

export const contactImport = {
  /**
   * Cancel the import: every still-queued row becomes `skipped`. Terminal;
   * conversations already created stay.
   *
   * Requires `ImportContacts` in the import's group.
   */
  cancel: Tapi.post<{ path: { import_uid: Uid }; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid/cancel",
  }),
  /**
   * Delete an import and its rows. Refused while loading — pause or cancel
   * first. Conversations already created stay.
   *
   * Requires `ImportContacts` in the import's group.
   */
  delete: Tapi.delete<{ path: { import_uid: Uid }; response: null }>()({
    endpoint: "/contact-import/:import_uid",
  }),
  /**
   * Drop a staged row instead of fixing it: the record simply leaves the
   * import.
   *
   * Requires `ImportContacts` in the import's group.
   */
  deleteRow: Tapi.delete<{ path: { import_uid: Uid; row_id: number }; response: null }>()({
    endpoint: "/contact-import/:import_uid/row/:row_id",
  }),
  /**
   * One import with its derived counters and drain estimate — the progress
   * page's poll.
   *
   * Requires `ImportContacts` in the import's group.
   */
  get: Tapi.get<{ path: { import_uid: Uid }; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid",
  }),
  /**
   * List imports, newest first, optionally one group's.
   *
   * Requires `ImportContacts`; the list covers only imports of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListImportsQuery; response: Array<ContactImportDetail> }>()({
    endpoint: "/contact-import",
  }),
  /**
   * Download the file as it was parsed: the original columns and cells, one
   * line per record still in the import — rows deleted while staged are not
   * in it. Cells are re-quoted per RFC 4180, so byte-for-byte it may differ
   * from the upload.
   *
   * Requires `ImportContacts` in the import's group.
   */
  original: Tapi.get<{ path: { import_uid: Uid }; response: Blob }>()({
    endpoint: "/contact-import/:import_uid/original.csv",
  }),
  /**
   * Pause loading: queued rows stay queued and the loaders skip them until a
   * resume. Rows already being checked finish.
   *
   * Requires `ImportContacts` in the import's group.
   */
  pause: Tapi.post<{ path: { import_uid: Uid }; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid/pause",
  }),
  /**
   * Download the import's report: the original columns plus the normalized
   * phone, the verdict and its detail, one line per record.
   *
   * Requires `ImportContacts` in the import's group.
   */
  report: Tapi.get<{ path: { import_uid: Uid }; response: Blob }>()({
    endpoint: "/contact-import/:import_uid/report.csv",
  }),
  /**
   * Resume a paused import: the loaders pick the queue back up where it stood.
   *
   * Requires `ImportContacts` in the import's group.
   */
  resume: Tapi.post<{ path: { import_uid: Uid }; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid/resume",
  }),
  /**
   * A page of the import's rows in file order, optionally one verdict only —
   * the fix table and the verdict drill-downs.
   *
   * Requires `ImportContacts` in the import's group.
   */
  rows: Tapi.get<{ path: { import_uid: Uid }; query: ListImportRowsQuery; response: Array<ContactImportRow> }>()({
    endpoint: "/contact-import/:import_uid/row",
  }),
  /**
   * Start loading: pending rows are dealt round-robin across the accounts and
   * one paced loader per account begins verifying numbers and creating
   * conversations. Rows are no longer editable.
   *
   * Requires `ImportContacts` in the import's group.
   */
  start: Tapi.post<{ path: { import_uid: Uid }; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid/start",
  }),
  /**
   * Rename the import. Any status.
   *
   * Requires `ImportContacts` in the import's group.
   */
  update: Tapi.put<{ path: { import_uid: Uid }; body: UpdateContactImportRequest; response: ContactImportDetail }>()({
    endpoint: "/contact-import/:import_uid",
  }),
  /**
   * Fix a staged row: the corrected values are re-parsed and the row gets its
   * new verdict. Only parse-phase verdicts are editable, and only while the
   * import is staged.
   *
   * Requires `ImportContacts` in the import's group.
   */
  updateRow: Tapi.put<{ path: { import_uid: Uid; row_id: number }; body: UpdateImportRowRequest; response: ContactImportRow }>()({
    endpoint: "/contact-import/:import_uid/row/:row_id",
  }),
  /**
   * Upload a CSV of contacts: the file is parsed synchronously, every record
   * gets a parse verdict, and the import is created `staged` — nothing touches
   * a platform until `start`. Invalid rows stay editable while staged.
   *
   * Requires `ImportContacts` in the accounts' group; every account must be a whatsapp session account (stevo or native) of that same group.
   */
  upload: Tapi.post<{ formData: UploadContactImportForm; response: ContactImportDetail }>()({
    endpoint: "/contact-import",
  }),
};
