// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { PulseDiskMetricRow } from "../../../types/database/PulseDiskMetricRow";
import type { PulseGpuMetricRow } from "../../../types/database/PulseGpuMetricRow";
import type { PulseHistoryQuery } from "../../../types/pulse/PulseHistoryQuery";
import type { PulseHostMetricRow } from "../../../types/database/PulseHostMetricRow";
import type { PulseNetworkMetricRow } from "../../../types/database/PulseNetworkMetricRow";

export const history = {
  /**
   * List historical disk metrics within a time window.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  disk: Tapi.get<{ query: PulseHistoryQuery; response: Array<PulseDiskMetricRow> }>()({
    endpoint: "/pulse/history/disk",
  }),
  /**
   * List historical GPU metrics within a time window.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  gpu: Tapi.get<{ query: PulseHistoryQuery; response: Array<PulseGpuMetricRow> }>()({
    endpoint: "/pulse/history/gpu",
  }),
  /**
   * List historical host metrics within a time window.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  host: Tapi.get<{ query: PulseHistoryQuery; response: Array<PulseHostMetricRow> }>()({
    endpoint: "/pulse/history/host",
  }),
  /**
   * List historical network metrics within a time window.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  network: Tapi.get<{ query: PulseHistoryQuery; response: Array<PulseNetworkMetricRow> }>()({
    endpoint: "/pulse/history/network",
  }),
};
