// This file was generated by tapir. Do not edit this file manually.

export type PulseProcessStatus = "run" | "sleep" | "stop" | "zombie" | "idle" | "dead" | "tracing" | "wakekill" | "waking" | "parked" | "lock_blocked" | "uninterruptible_disk_sleep" | "suspended" | "unknown";

/** Every `PulseProcessStatus`, in declaration order. */
export const PULSE_PROCESS_STATUS = ["run", "sleep", "stop", "zombie", "idle", "dead", "tracing", "wakekill", "waking", "parked", "lock_blocked", "uninterruptible_disk_sleep", "suspended", "unknown"] as const satisfies readonly PulseProcessStatus[];
