// This file was generated by tapir. Do not edit this file manually.

export type PulseSystemInfo = {
  hostname: string,
  os_name: string,
  os_version: string,
  kernel_version: string,
  cpu_model: string,
  physical_cores: number,
  logical_cores: number,
};
