// This file was generated by tapir. Do not edit this file manually.
import type { PulseCpuSnapshot } from "./PulseCpuSnapshot";
import type { PulseDiskSnapshot } from "./PulseDiskSnapshot";
import type { PulseGpuSnapshot } from "./PulseGpuSnapshot";
import type { PulseNetworkSnapshot } from "./PulseNetworkSnapshot";
import type { PulseProcessSnapshot } from "./PulseProcessSnapshot";
import type { PulseRamSnapshot } from "./PulseRamSnapshot";

export type PulseSnapshot = {
  timestamp_ms: number,
  uptime_secs: number,
  cpu: PulseCpuSnapshot,
  ram: PulseRamSnapshot,
  disks: Array<PulseDiskSnapshot>,
  networks: Array<PulseNetworkSnapshot>,
  processes: Array<PulseProcessSnapshot>,
  gpus: Array<PulseGpuSnapshot>,
};
