// This file was generated by tapir. Do not edit this file manually.
import type { PulseGpuVendor } from "./PulseGpuVendor";

export type PulseGpuSnapshot = {
  index: number,
  name: string,
  vendor: PulseGpuVendor,
  vram_total_bytes: number,
  vram_used_bytes: number,
  vram_usage_percent: number,
  utilization_percent: number,
  memory_utilization_percent: number,
  clock_graphics_mhz: number,
  clock_memory_mhz: number,
  temperature_celsius: number,
  power_watts: number,
  power_limit_watts: number,
};
