// This file was generated by tapir. Do not edit this file manually.
import type { PulseTemperatureReading } from "./PulseTemperatureReading";

export type PulseDiskSnapshot = {
  name: string,
  mount_point: string,
  fs_type: string,
  total_bytes: number,
  available_bytes: number,
  usage_percent: number,
  read_bytes: number,
  written_bytes: number,
  total_read_bytes: number,
  total_written_bytes: number,
  read_bytes_per_sec: number,
  written_bytes_per_sec: number,
  read_iops: number,
  write_iops: number,
  temperatures: Array<PulseTemperatureReading>,
};
