// This file was generated by tapir. Do not edit this file manually.

export type PulseNetworkSnapshot = {
  interface: string,
  mac_address: string,
  ipv4_addresses: Array<string>,
  ipv6_addresses: Array<string>,
  link_speed_mbps: number | null,
  is_physical: boolean,
  received_bytes: number,
  transmitted_bytes: number,
  total_received_bytes: number,
  total_transmitted_bytes: number,
  received_bytes_per_sec: number,
  transmitted_bytes_per_sec: number,
  received_packets: number,
  transmitted_packets: number,
  received_errors: number,
  transmitted_errors: number,
};
