// This file was generated by tapir. Do not edit this file manually.
import type { PulseProcessStatus } from "./PulseProcessStatus";

export type PulseProcessSnapshot = {
  pid: number,
  name: string,
  cpu_usage: number,
  memory_bytes: number,
  virtual_memory_bytes: number,
  disk_read_bytes: number,
  disk_written_bytes: number,
  status: PulseProcessStatus,
  run_time_secs: number,
};
