// This file was generated by tapir. Do not edit this file manually.
import type { PulseTemperatureReading } from "./PulseTemperatureReading";

export type PulseRamSnapshot = {
  total_bytes: number,
  used_bytes: number,
  available_bytes: number,
  usage_percent: number,
  swap_total_bytes: number,
  swap_used_bytes: number,
  swap_usage_percent: number,
  page_in_bytes_per_sec: number,
  page_out_bytes_per_sec: number,
  swap_in_bytes_per_sec: number,
  swap_out_bytes_per_sec: number,
  temperatures: Array<PulseTemperatureReading>,
};
