// This file was generated by tapir. Do not edit this file manually.
import type { IssueCategory } from "../domain/IssueCategory";
import type { IssueSeverity } from "../domain/IssueSeverity";
import type { Text0_2048 } from "../primitives/Text0_2048";
import type { Text0_8000 } from "../primitives/Text0_8000";

export type CreateIssueForm = {
  category: IssueCategory,
  severity: IssueSeverity,
  description: Text0_8000,
  url: Text0_2048 | null,
  screenshots: Array<File>,
};
