// This file was generated by tapir. Do not edit this file manually.
import type { IssueDetails } from "../domain/IssueDetails";
import type { IssueSeverity } from "../domain/IssueSeverity";
import type { Text0_8000 } from "../primitives/Text0_8000";

export type CreateIssueForm = {
  severity: IssueSeverity,
  description: Text0_8000,
  details: IssueDetails,
  screenshots: Array<File>,
};
