// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Call } from "../../types/domain/Call";
import type { Conversation } from "../../types/domain/Conversation";
import type { ConversationActionRequest } from "../../types/message/ConversationActionRequest";
import type { ConversationAvatar } from "../../types/message/ConversationAvatar";
import type { ConversationCallsQuery } from "../../types/call/ConversationCallsQuery";
import type { ConversationMessageCountQuery } from "../../types/message/ConversationMessageCountQuery";
import type { ConversationMessagesQuery } from "../../types/message/ConversationMessagesQuery";
import type { CreateConversationRequest } from "../../types/message/CreateConversationRequest";
import type { ListConversationsQuery } from "../../types/message/ListConversationsQuery";
import type { Message } from "../../types/domain/Message";
import type { SetConversationAliasRequest } from "../../types/message/SetConversationAliasRequest";
import type { Uid } from "../../types/primitives/Uid";

export const conversation = {
  /**
   * Send a presence signal into a conversation: mark_seen, typing_on, or
   * typing_off. The payload is channel-tagged and the `channel` must match the
   * conversation's account; official whatsapp has no typing_off (its indicator
   * auto-dismisses), so that channel's shape cannot express one. Mark-seen
   * receipts every inbound message still unread (the latest 50 on the
   * session-backed whatsapp channels, the latest one on official whatsapp) and
   * advances the conversation's `seen_up_to` watermark (`last_inbound_at >
   * seen_up_to` = unread); with nothing unread it is a no-op.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  action: Tapi.post<{ path: { conversation_uid: Uid }; body: ConversationActionRequest; response: null }>()({
    endpoint: "/conversation/:conversation_uid/action",
  }),
  /**
   * Set or clear the operator's label for the contact. Independent of the
   * platform-fetched participant name, which profile refreshes keep updating;
   * clearing the alias falls back to it.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  alias: Tapi.put<{ path: { conversation_uid: Uid }; body: SetConversationAliasRequest; response: Conversation }>()({
    endpoint: "/conversation/:conversation_uid/alias",
  }),
  /**
   * The participant's full-size profile picture, fetched from the platform on
   * first request and kept until the platform reports a picture change; a
   * request that finds none is not retried for ten minutes. Channels without a
   * full-size picture answer with the picture the hub already holds.
   *
   * Requires `ViewMessages` in the conversation's group.
   */
  avatar: Tapi.get<{ path: { conversation_uid: Uid }; response: ConversationAvatar }>()({
    endpoint: "/conversation/:conversation_uid/avatar",
  }),
  /**
   * List a conversation's calls, newest first; `before_id` pages older history.
   *
   * Requires `ViewMessages` in the conversation's group.
   */
  calls: Tapi.get<{ path: { conversation_uid: Uid }; query: ConversationCallsQuery; response: Array<Call> }>()({
    endpoint: "/conversation/:conversation_uid/call",
  }),
  /**
   * Erase the conversation's stored history on the hub, keeping the
   * conversation: its messages go, the preview and unread badge reset, and the
   * 24h-window watermarks stay. Nothing is deleted on the platform.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  clear: Tapi.delete<{ path: { conversation_uid: Uid }; response: Conversation }>()({
    endpoint: "/conversation/:conversation_uid/message",
  }),
  /**
   * Open (or return) a conversation with a phone number — a channel-tagged
   * request whose declared channel must match the account's; only
   * whatsapp_stevo / whatsapp_native can verify a number on the platform,
   * so no other channel's shape deserializes. A number the account already
   * talks to returns its conversation with no platform lookup at all; a new
   * one is checked first (an unrecognized number or failed check creates
   * nothing), the platform's canonical id keys the conversation, and the
   * initial profile (name, picture) is stored best-effort and refreshed at
   * most every 30 days.
   *
   * Requires `SendMessages` in the account's group.
   */
  create: Tapi.post<{ body: CreateConversationRequest; response: Conversation }>()({
    endpoint: "/conversation",
  }),
  /**
   * Delete the conversation and its whole stored history from the hub.
   * Nothing is deleted on the platform: a later inbound message from the same
   * participant opens a fresh conversation.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  delete: Tapi.delete<{ path: { conversation_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid",
  }),
  /**
   * List conversations, newest activity first, optionally filtered by group or
   * social account; `before_activity_at`+`before_uid` page older activity
   * (keyset cursor). Rows carry the denormalized chat-list summary (unread
   * badge + last-message preview). `q` narrows to conversations whose
   * participant (alias, name, username, phone) contains it — a term under 2
   * characters answers with no rows; not combinable with `uids`.
   *
   * Requires `ViewMessages`; the list covers only conversations of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListConversationsQuery; response: Array<Conversation> }>()({
    endpoint: "/conversation",
  }),
  /**
   * How many messages the conversation holds, narrowed by `kinds` like the
   * list — what a media gallery shows as its total.
   *
   * Requires `ViewMessages` in the conversation's group.
   */
  messageCount: Tapi.get<{ path: { conversation_uid: Uid }; query: ConversationMessageCountQuery; response: number }>()({
    endpoint: "/conversation/:conversation_uid/message/count",
  }),
  /**
   * List a conversation's messages, newest first; `before_id` pages older
   * history. `after_id` pages newer history from an anchored message: each
   * page is the oldest `limit` rows above the cursor, still newest-first on
   * the wire (never both cursors).
   *
   * Requires `ViewMessages` in the conversation's group.
   */
  messages: Tapi.get<{ path: { conversation_uid: Uid }; query: ConversationMessagesQuery; response: Array<Message> }>()({
    endpoint: "/conversation/:conversation_uid/message",
  }),
  /**
   * Clear the conversation's unread badge (hub-local read state, shared by
   * every operator). Never sends a platform read receipt — that stays the
   * explicit `mark_seen` conversation action.
   *
   * Requires `ViewMessages` in the conversation's group.
   */
  read: Tapi.put<{ path: { conversation_uid: Uid }; response: Conversation }>()({
    endpoint: "/conversation/:conversation_uid/read",
  }),
  /**
   * How many conversations hold unread messages, across every group where the
   * caller holds `ViewMessages` — the inbox badge.
   *
   * Requires `ViewMessages`; the count covers every group where the caller holds it.
   */
  unreadCount: Tapi.get<{ response: number }>()({
    endpoint: "/conversation/unread",
  }),
};
