// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Comment } from "../../types/database/Comment";
import type { CommentMessageRequest } from "../../types/engagement/CommentMessageRequest";
import type { CreateCommentRequest } from "../../types/engagement/CreateCommentRequest";
import type { ListCommentsQuery } from "../../types/engagement/ListCommentsQuery";
import type { PrivateReplyRequest } from "../../types/engagement/PrivateReplyRequest";
import type { PrivateReplyResponse } from "../../types/engagement/PrivateReplyResponse";
import type { SetCommentHiddenRequest } from "../../types/engagement/SetCommentHiddenRequest";
import type { Uid } from "../../types/primitives/Uid";

export const comment = {
  /**
   * Comment on a post/media as the account named in the path (top-level
   * comment). The payload is channel-tagged and must match the account's
   * channel — only facebook and instagram carry a comment surface, so no
   * other channel's shape deserializes.
   *
   * Requires `ReplyComments` in the account's group.
   */
  create: Tapi.post<{ path: { social_account_uid: Uid }; body: CreateCommentRequest; response: Comment }>()({
    endpoint: "/social-account/:social_account_uid/comment",
  }),
  /**
   * Delete a comment from the platform; the row is kept with `deleted` set.
   *
   * Requires `ModerateComments` in the account's group.
   */
  delete: Tapi.delete<{ path: { social_account_uid: Uid; comment_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid",
  }),
  /**
   * Fetch a single comment of the account. A comment uid outside the named
   * account reads as not found.
   *
   * Requires `ViewComments` in the account's group.
   */
  get: Tapi.get<{ path: { social_account_uid: Uid; comment_uid: Uid }; response: Comment }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid",
  }),
  /**
   * Like a comment as the page (Facebook only — Instagram's API has no
   * comment likes).
   *
   * Requires `ReplyComments` in the account's group.
   */
  like: Tapi.post<{ path: { social_account_uid: Uid; comment_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid/like",
  }),
  /**
   * Poll the unified comment feed: comments with `id` greater than `since_id`,
   * oldest first, optionally filtered by group, account, or post.
   *
   * Requires `ViewComments`; the feed covers only comments of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListCommentsQuery; response: Array<Comment> }>()({
    endpoint: "/comment",
  }),
  /**
   * Answer a comment privately with a DM (allowed once per comment; the
   * message lands in the conversation via the echo webhook). The account's
   * own comments are refused.
   *
   * Requires `SendMessages` in the account's group (the reply is a DM, not a comment).
   */
  privateReply: Tapi.post<{ path: { social_account_uid: Uid; comment_uid: Uid }; body: PrivateReplyRequest; response: PrivateReplyResponse }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid/private-reply",
  }),
  /**
   * Reply to a comment as the account (threaded reply).
   *
   * Requires `ReplyComments` in the account's group.
   */
  reply: Tapi.post<{ path: { social_account_uid: Uid; comment_uid: Uid }; body: CommentMessageRequest; response: Comment }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid/reply",
  }),
  /**
   * Hide or unhide a comment on the platform.
   *
   * Requires `ModerateComments` in the account's group.
   */
  setHidden: Tapi.put<{ path: { social_account_uid: Uid; comment_uid: Uid }; body: SetCommentHiddenRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid/hidden",
  }),
  /**
   * Remove the page's like from a comment (Facebook only).
   *
   * Requires `ReplyComments` in the account's group.
   */
  unlike: Tapi.delete<{ path: { social_account_uid: Uid; comment_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/comment/:comment_uid/like",
  }),
};
