// This file was generated by validation codegen. Do not edit manually.
//
// The single TypeScript port of the Rust validation interpreter
// (crates/tapir/src/validation/mod.rs). A validated newtype bakes in its spec and
// calls check()/checkAll() here.

export type Preprocess = "none" | "trim" | "trim_lowercase";

export type Constraint =
  | { kind: "minLen"; min: number }
  | { kind: "maxLen"; max: number }
  | { kind: "exactLen"; len: number }
  | { kind: "minDigits"; min: number }
  | { kind: "maxDigits"; max: number }
  | { kind: "noControlChars" }
  | { kind: "asciiDigitsOnly" }
  | { kind: "regex"; source: string; hint: string | null }
  | { kind: "requireUppercase" }
  | { kind: "requireLowercase" }
  | { kind: "requireDigit" }
  | { kind: "requireSymbol" }
  | { kind: "min"; value: number }
  | { kind: "max"; value: number };

export type Violation =
  | { kind: "tooShort"; min: number }
  | { kind: "tooLong"; max: number }
  | { kind: "exactLength"; expected: number; actual: number }
  | { kind: "tooFewDigits"; min: number }
  | { kind: "tooManyDigits"; max: number }
  | { kind: "invalidFormat"; hint: string | null }
  | { kind: "invalidChars" }
  | { kind: "notDigits" }
  | { kind: "tooSmall"; min: number }
  | { kind: "tooLarge"; max: number }
  | { kind: "missingUppercase" }
  | { kind: "missingLowercase" }
  | { kind: "missingDigit" }
  | { kind: "missingSymbol" };

export interface ValidationSpec {
  preprocess: Preprocess;
  constraints: Constraint[];
}

// The value a spec validates: a string (text/password newtypes) or a number (a
// Number). One spec model covers both domains.
export type Value = string | number;

// Rust `str::len` counts UTF-8 bytes; JS `.length` counts UTF-16 code units.
// Length bounds are byte bounds, so count bytes to stay 1:1.
const ENCODER = new TextEncoder();
function byteLen(s: string): number {
  return ENCODER.encode(s).length;
}

function digitCount(s: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 48 && c <= 57) n++;
  }
  return n;
}

// Rust char::is_control: C0 (U+0000–U+001F), DEL (U+007F), C1 (U+0080–U+009F).
const CONTROL_CHARS = /[\u0000-\u001f\u007f-\u009f]/;

const REGEX_CACHE = new Map<string, RegExp>();
function regexFor(source: string): RegExp {
  let re = REGEX_CACHE.get(source);
  if (re === undefined) {
    re = new RegExp(source);
    REGEX_CACHE.set(source, re);
  }
  return re;
}

export function normalize(spec: ValidationSpec, value: string): string {
  if (spec.preprocess === "trim") return value.trim();
  if (spec.preprocess === "trim_lowercase") return value.trim().toLowerCase();
  return value;
}

// One constraint against a value; null if satisfied. A constraint whose domain
// doesn't match the value never fires (specs are homogeneous).
function checkOne(c: Constraint, value: Value): Violation | null {
  const s = typeof value === "string" ? value : "";
  switch (c.kind) {
    case "minLen":
      return byteLen(s) < c.min ? { kind: "tooShort", min: c.min } : null;
    case "maxLen":
      return byteLen(s) > c.max ? { kind: "tooLong", max: c.max } : null;
    case "exactLen":
      return byteLen(s) !== c.len ? { kind: "exactLength", expected: c.len, actual: byteLen(s) } : null;
    case "minDigits":
      return digitCount(s) < c.min ? { kind: "tooFewDigits", min: c.min } : null;
    case "maxDigits":
      return digitCount(s) > c.max ? { kind: "tooManyDigits", max: c.max } : null;
    case "noControlChars":
      return CONTROL_CHARS.test(s) ? { kind: "invalidChars" } : null;
    case "asciiDigitsOnly":
      return !/^[0-9]*$/.test(s) ? { kind: "notDigits" } : null;
    case "regex":
      return !regexFor(c.source).test(s) ? { kind: "invalidFormat", hint: c.hint } : null;
    case "requireUppercase":
      return !/\p{Lu}/u.test(s) ? { kind: "missingUppercase" } : null;
    case "requireLowercase":
      return !/\p{Ll}/u.test(s) ? { kind: "missingLowercase" } : null;
    case "requireDigit":
      return !/[0-9]/.test(s) ? { kind: "missingDigit" } : null;
    case "requireSymbol":
      return !/[^\p{L}\p{N}]/u.test(s) ? { kind: "missingSymbol" } : null;
    case "min":
      return typeof value === "number" && value < c.value ? { kind: "tooSmall", min: c.value } : null;
    case "max":
      return typeof value === "number" && value > c.value ? { kind: "tooLarge", max: c.value } : null;
  }
}

// The first violation, or null if valid. Used by a newtype's parse().
export function check(spec: ValidationSpec, value: Value): Violation | null {
  const v = typeof value === "string" ? normalize(spec, value) : value;
  for (const c of spec.constraints) {
    const viol = checkOne(c, v);
    if (viol) return viol;
  }
  return null;
}

// Every unmet constraint, in order — for a password-strength meter / live field
// checklist. Empty array means valid.
export function checkAll(spec: ValidationSpec, value: Value): Violation[] {
  const v = typeof value === "string" ? normalize(spec, value) : value;
  const out: Violation[] = [];
  for (const c of spec.constraints) {
    const viol = checkOne(c, v);
    if (viol) out.push(viol);
  }
  return out;
}

// pt-BR problem text, mirroring Violation::message on the Rust side.
export function message(v: Violation): string {
  switch (v.kind) {
    case "tooShort":
      return `muito curto (mínimo ${v.min} caracteres)`;
    case "tooLong":
      return `muito longo (máximo ${v.max} caracteres)`;
    case "exactLength":
      return `tamanho inválido (esperado ${v.expected}, recebido ${v.actual})`;
    case "tooFewDigits":
      return `muito curto (mínimo ${v.min} dígitos)`;
    case "tooManyDigits":
      return `muito longo (máximo ${v.max} dígitos)`;
    case "invalidFormat":
      return v.hint ? `formato inválido (${v.hint})` : "formato inválido";
    case "invalidChars":
      return "caracteres inválidos";
    case "notDigits":
      return "deve conter apenas dígitos";
    case "tooSmall":
      return `muito pequeno (mínimo ${v.min})`;
    case "tooLarge":
      return `muito grande (máximo ${v.max})`;
    case "missingUppercase":
      return "deve conter uma letra maiúscula";
    case "missingLowercase":
      return "deve conter uma letra minúscula";
    case "missingDigit":
      return "deve conter um dígito";
    case "missingSymbol":
      return "deve conter um símbolo";
  }
}
