// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { UserPasswordResetConfirmRequest } from "../../types/user_password_reset/UserPasswordResetConfirmRequest";
import type { UserPasswordResetStartRequest } from "../../types/user_password_reset/UserPasswordResetStartRequest";

export const userPasswordReset = {
  /**
   * Set a new password using a valid reset token, revoking the user's existing sessions.
   *
   * Public — no authentication required; authorization is via the ephemeral reset token.
   */
  confirm: Tapi.post<{ body: UserPasswordResetConfirmRequest; response: null }>()({
    endpoint: "/user-password-reset/confirm",
  }),
  /**
   * Issue a password-reset token and email a reset link to the address if it maps to an enabled account.
   *
   * Public — no authentication required.
   */
  request: Tapi.post<{ body: UserPasswordResetStartRequest; response: null }>()({
    endpoint: "/user-password-reset/request",
  }),
};
