// This file was generated by tapir. Do not edit this file manually.
import type { ConversationCounts } from "./ConversationCounts";
import type { Uid } from "../primitives/Uid";

export type AccountConversationInsight = {
  social_account_uid: Uid,
  /**
   * The whole period for this account.
   */
  counts: ConversationCounts,
};
