// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAccountSeries } from "../domain/FacebookAccountSeries";
import type { FacebookAltAccountSeries } from "../domain/FacebookAltAccountSeries";
import type { InstagramAccountSeries } from "../domain/InstagramAccountSeries";
import type { InstagramAltAccountSeries } from "../domain/InstagramAltAccountSeries";

/**
 * An account's collected metrics, day by day, in the vocabulary of its
 * channel: each channel names only the metrics it reports.
 */
export type AccountInsightHistory = {
  "channel": "facebook",
  series: Array<FacebookAccountSeries>,
} | {
  "channel": "instagram",
  series: Array<InstagramAccountSeries>,
} | {
  "channel": "facebook_alt",
  series: Array<FacebookAltAccountSeries>,
} | {
  "channel": "instagram_alt",
  series: Array<InstagramAltAccountSeries>,
};
