// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAccountMetric } from "../domain/FacebookAccountMetric";
import type { FacebookAltAccountMetric } from "../domain/FacebookAltAccountMetric";
import type { InstagramAccountMetric } from "../domain/InstagramAccountMetric";
import type { InstagramAltAccountMetric } from "../domain/InstagramAltAccountMetric";

/**
 * Which account metrics to aggregate; the channel decides the vocabulary, and
 * only accounts of that channel take part.
 */
export type AccountMetricQuery = {
  "channel": "facebook",
  metrics: Array<FacebookAccountMetric>,
} | {
  "channel": "instagram",
  metrics: Array<InstagramAccountMetric>,
} | {
  "channel": "facebook_alt",
  metrics: Array<FacebookAltAccountMetric>,
} | {
  "channel": "instagram_alt",
  metrics: Array<InstagramAltAccountMetric>,
};
