// This file was generated by tapir. Do not edit this file manually.
import type { ActivityGranularity } from "../domain/ActivityGranularity";
import type { Channel } from "../domain/Channel";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type ConversationInsightQuery = {
  /**
   * Narrow to one group; omit for everything the caller may see.
   */
  group_uid: Uid | null,
  /**
   * Narrow to these accounts; each must be in scope.
   */
  social_account_uids: Array<Uid> | null,
  /**
   * Narrow to these channels.
   */
  channels: Array<Channel> | null,
  /**
   * Start of the period (unix ms), inclusive.
   */
  since: Timestamp,
  /**
   * End of the period (unix ms), exclusive.
   */
  until: Timestamp,
  granularity: ActivityGranularity,
  /**
   * Minutes east of UTC that periods align to; 0 when omitted.
   */
  utc_offset_minutes: number | null,
};
