// This file was generated by tapir. Do not edit this file manually.
import type { AccountConversationInsight } from "./AccountConversationInsight";
import type { ConversationBucket } from "./ConversationBucket";
import type { ConversationCounts } from "./ConversationCounts";
import type { HourOfWeek } from "./HourOfWeek";

export type ConversationInsightResponse = {
  /**
   * Accounts the query covered after every filter.
   */
  accounts: number,
  /**
   * One per period, oldest first, gaps included as zeros.
   */
  buckets: Array<ConversationBucket>,
  /**
   * The whole period folded once; distinct counts span the whole period.
   */
  totals: ConversationCounts,
  /**
   * One row per account in scope, zeros included.
   */
  by_account: Array<AccountConversationInsight>,
  /**
   * 168 cells, Monday midnight first.
   */
  by_hour_of_week: Array<HourOfWeek>,
};
