// This file was generated by tapir. Do not edit this file manually.
import type { ReplyBands } from "./ReplyBands";
import type { TypicalWait } from "./TypicalWait";

/**
 * What a scope's conversations did in one period.
 */
export type ConversationCounts = {
  /**
   * Conversations whose first message ever falls in the period and came
   * from the customer.
   */
  new_by_customer: number,
  /**
   * Conversations whose first message ever falls in the period and came
   * from the account.
   */
  new_by_account: number,
  /**
   * Distinct conversations where the customer wrote in the period.
   */
  customers_writing: number,
  /**
   * Messages received.
   */
  inbound: number,
  /**
   * Messages the account sent, whoever or whatever sent them.
   */
  outbound: number,
  /**
   * Requests that open an atendimento: the customer writes first, or after
   * 24 hours of silence in the conversation, answered or not.
   */
  openings: number,
  /**
   * First reply to each atendimento, over the answered ones.
   */
  first_reply: ReplyBands,
  first_reply_typical: TypicalWait,
  /**
   * Replies to requests inside an ongoing atendimento, over the answered
   * ones.
   */
  later_reply: ReplyBands,
  later_reply_typical: TypicalWait,
  /**
   * Account messages that start contact: the first message of the
   * conversation, or one after 24 hours of silence while no customer request
   * waits.
   */
  outreach: number,
  /**
   * Of those, the ones the customer answered within 24 hours.
   */
  outreach_replied: number,
  /**
   * Of those, the ones younger than 24 hours still without an answer.
   */
  outreach_open: number,
};
