// This file was generated by tapir. Do not edit this file manually.
import type { ConversationCounts } from "./ConversationCounts";
import type { Timestamp } from "../primitives/Timestamp";

export type ConversationBucket = {
  /**
   * Start of the period (unix ms), aligned to the requested offset.
   */
  period_start: Timestamp,
  /**
   * End of the period (unix ms), exclusive; it may pass `until`.
   */
  period_end: Timestamp,
  /**
   * The query covers only part of the period.
   */
  partial: boolean,
  counts: ConversationCounts,
};
