// This file was generated by tapir. Do not edit this file manually.
import type { ReplyBands } from "./ReplyBands";

/**
 * Atendimentos opened in one hour of the week across the period.
 */
export type HourOfWeek = {
  /**
   * 1 is Monday and 7 is Sunday, in the requested offset.
   */
  weekday: number,
  /**
   * Hour of the day, 0 to 23, in the requested offset.
   */
  hour: number,
  openings: number,
  first_reply: ReplyBands,
};
