// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAccountBucket } from "../domain/FacebookAccountBucket";
import type { FacebookAltAccountBucket } from "../domain/FacebookAltAccountBucket";
import type { FacebookAltPostBucket } from "../domain/FacebookAltPostBucket";
import type { FacebookPostBucket } from "../domain/FacebookPostBucket";
import type { InstagramAccountBucket } from "../domain/InstagramAccountBucket";
import type { InstagramAltAccountBucket } from "../domain/InstagramAltAccountBucket";
import type { InstagramAltPostBucket } from "../domain/InstagramAltPostBucket";
import type { InstagramPostBucket } from "../domain/InstagramPostBucket";

/**
 * Aggregated periods, in the vocabulary the request declared.
 */
export type InsightQueryResponse = {
  "channel": "facebook_account",
  buckets: Array<FacebookAccountBucket>,
} | {
  "channel": "instagram_account",
  buckets: Array<InstagramAccountBucket>,
} | {
  "channel": "facebook_alt_account",
  buckets: Array<FacebookAltAccountBucket>,
} | {
  "channel": "instagram_alt_account",
  buckets: Array<InstagramAltAccountBucket>,
} | {
  "channel": "facebook_post",
  buckets: Array<FacebookPostBucket>,
} | {
  "channel": "instagram_post",
  buckets: Array<InstagramPostBucket>,
} | {
  "channel": "facebook_alt_post",
  buckets: Array<FacebookAltPostBucket>,
} | {
  "channel": "instagram_alt_post",
  buckets: Array<InstagramAltPostBucket>,
};
