// This file was generated by tapir. Do not edit this file manually.
import type { InsightPoint } from "./InsightPoint";

/**
 * One collected metric as a day-by-day series.
 */
export type InsightSeries = {
  metric: string,
  points: Array<InsightPoint>,
};
