// This file was generated by tapir. Do not edit this file manually.
import type { Granularity } from "../domain/Granularity";
import type { InsightQuerySubject } from "./InsightQuerySubject";
import type { Roll } from "../domain/Roll";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type InsightQueryRequest = {
  subject: InsightQuerySubject,
  /**
   * Narrow to one group; omit for everything the caller may see.
   */
  group_uid: Uid | null,
  /**
   * Narrow to these accounts; every one must belong to the declared channel.
   */
  social_account_uids: Array<Uid> | null,
  /**
   * Inclusive range over snapshot days (unix ms); defaults to the last 30 days.
   */
  since: Timestamp | null,
  until: Timestamp | null,
  granularity: Granularity,
  /**
   * `sum` adds the days of a period; `last` keeps each subject's newest day
   * in the period (running totals such as followers).
   */
  roll: Roll,
};
