// This file was generated by tapir. Do not edit this file manually.
import type { AccountMetricQuery } from "./AccountMetricQuery";
import type { PostMetricQuery } from "./PostMetricQuery";

/**
 * What the query aggregates: accounts or their posts.
 */
export type InsightQuerySubject = {
  "subject": "account",
  query: AccountMetricQuery,
} | {
  "subject": "post",
  query: PostMetricQuery,
};
