// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type InsightHistoryQuery = {
  /**
   * Filter to these collected metric names (comma-separated); defaults to
   * every stored metric.
   */
  metrics: string | null,
  /**
   * Inclusive range over snapshot days (unix ms); defaults to the last 30 days.
   */
  from: Timestamp | null,
  to: Timestamp | null,
};
