// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type InsightHistoryQuery = {
  /**
   * Inclusive range over snapshot days (unix ms); defaults to the last 30 days.
   */
  since: Timestamp | null,
  until: Timestamp | null,
};
