// This file was generated by tapir. Do not edit this file manually.
import type { PostingBucket } from "./PostingBucket";

export type PostingInsightResponse = {
  /**
   * Accounts the query covered after every filter.
   */
  accounts: number,
  /**
   * One per period, oldest first, gaps included as zeros.
   */
  buckets: Array<PostingBucket>,
  /**
   * Posts published across the whole period.
   */
  posts: number,
};
