// This file was generated by tapir. Do not edit this file manually.

/**
 * Answered requests by how long the customer waited, from the request's
 * first message to the account's reply.
 */
export type ReplyBands = {
  /**
   * Answered within 5 minutes.
   */
  up_to_5m: number,
  /**
   * Answered after 5 minutes and within an hour.
   */
  up_to_1h: number,
  /**
   * Answered after an hour and within 24 hours.
   */
  up_to_24h: number,
  /**
   * Answered after more than 24 hours.
   */
  over_24h: number,
};
