// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAltPostSeries } from "../domain/FacebookAltPostSeries";
import type { FacebookPostSeries } from "../domain/FacebookPostSeries";
import type { InstagramAltPostSeries } from "../domain/InstagramAltPostSeries";
import type { InstagramPostSeries } from "../domain/InstagramPostSeries";

/**
 * A platform post's collected metrics, day by day, in the vocabulary of its
 * channel.
 */
export type SocialPostInsightHistory = {
  "channel": "facebook",
  series: Array<FacebookPostSeries>,
} | {
  "channel": "instagram",
  series: Array<InstagramPostSeries>,
} | {
  "channel": "facebook_alt",
  series: Array<FacebookAltPostSeries>,
} | {
  "channel": "instagram_alt",
  series: Array<InstagramAltPostSeries>,
};
