// This file was generated by tapir. Do not edit this file manually.

/**
 * The median wait over answered requests.
 */
export type TypicalWait = {
  "kind": "value",
  ms: number,
} | {
  "kind": "too_few",
  samples: number,
};
