// This file was generated by tapir. Do not edit this file manually.
import type { ApiKeyPermissions } from "../domain/ApiKeyPermissions";
import type { Name } from "../primitives/Name";
import type { Uid } from "../primitives/Uid";

export type CreateApiKeyRequest = {
  name: Name,
  group_uid: Uid | null,
  permissions: ApiKeyPermissions,
};
