// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { OptionalUpdate } from "../axumy/OptionalUpdate";

export type UpdateApiKeyRequest = {
  name: OptionalUpdate<Name>,
  enabled: OptionalUpdate<boolean>,
};
