// This file was generated by tapir. Do not edit this file manually.
import type { ApiKeyPermissions } from "../database/ApiKeyPermissions";

export type UpdateApiKeyPermissionsRequest = {
  permissions: ApiKeyPermissions,
};
