// This file was generated by tapi. Do not edit manually.

import { apiKey } from "./api_key";
import { auditLog } from "./audit_log";
import { business } from "./business";
import { calendar } from "./calendar";
import { call } from "./call";
import { campaign } from "./campaign";
import { campaignTemplate } from "./campaign_template";
import { comment } from "./comment";
import { contactImport } from "./contact_import";
import { conversation } from "./conversation";
import { event } from "./event";
import { eventWebhook } from "./event_webhook";
import { ghl } from "./ghl";
import { gif } from "./gif";
import { google } from "./google";
import { group } from "./group";
import { groupMember } from "./group_member";
import { issue } from "./issue";
import { mailQueue } from "./mail_queue";
import { media } from "./media";
import { mention } from "./mention";
import { message } from "./message";
import { oauth } from "./oauth";
import { post } from "./post";
import { pulse } from "./pulse";
import { rateLimit } from "./rate_limit";
import { search } from "./search";
import { socialAccount } from "./social_account";
import { test } from "./test";
import { uptime } from "./uptime";
import { user } from "./user";
import { userAccountNotification } from "./user_account_notification";
import { userInvite } from "./user_invite";
import { userMembership } from "./user_membership";
import { userMfa } from "./user_mfa";
import { userNotification } from "./user_notification";
import { userPasswordReset } from "./user_password_reset";
import { userSession } from "./user_session";
import { webhook } from "./webhook";
import { whatsappTemplate } from "./whatsapp_template";

export const routes = {
  apiKey,
  auditLog,
  business,
  calendar,
  call,
  campaign,
  campaignTemplate,
  comment,
  contactImport,
  conversation,
  event,
  eventWebhook,
  ghl,
  gif,
  google,
  group,
  groupMember,
  issue,
  mailQueue,
  media,
  mention,
  message,
  oauth,
  post,
  pulse,
  rateLimit,
  search,
  socialAccount,
  test,
  uptime,
  user,
  userAccountNotification,
  userInvite,
  userMembership,
  userMfa,
  userNotification,
  userPasswordReset,
  userSession,
  webhook,
  whatsappTemplate,
};
