// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateIssueForm } from "../../types/issue/CreateIssueForm";
import type { CreateIssueResponse } from "../../types/issue/CreateIssueResponse";
import type { Issue } from "../../types/domain/Issue";
import type { SetIssueStatusRequest } from "../../types/issue/SetIssueStatusRequest";
import type { Uid } from "../../types/primitives/Uid";

export const issue = {
  /**
   * Count issues — every issue for a caller holding `ViewIssues`, and only the caller's own reports for everyone else.
   *
   * Any authenticated user; `ViewIssues`, which only platform staff hold, is what widens the count beyond the caller's own reports.
   */
  count: Tapi.get<{ response: number }>()({
    endpoint: "/issue/count",
  }),
  /**
   * Report a new issue (category, severity, description, an optional page url and up to 10 optional screenshots) recorded under the caller's own user. The screenshots become hosted media named by `Issue.screenshots`, served by `media.serve` to platform staff holding `ViewIssues` and to the reporter themselves.
   *
   * Any authenticated user. Rejected when the platform is at its open-issue cap, and — when screenshots are attached — when the caller trips the per-user file-upload throttle.
   */
  create: Tapi.post<{ formData: CreateIssueForm; response: CreateIssueResponse }>()({
    endpoint: "/issue",
  }),
  /**
   * Fetch a single issue by uid.
   *
   * Any authenticated user for an issue they reported; `ViewIssues`, which only platform staff hold, reaches any issue. An issue the caller may not read reads as not found.
   */
  get: Tapi.get<{ path: { issue_uid: Uid }; response: Issue }>()({
    endpoint: "/issue/:issue_uid",
  }),
  /**
   * List issues, newest first — every issue for a caller holding `ViewIssues`, and only the caller's own reports for everyone else.
   *
   * Any authenticated user; `ViewIssues`, which only platform staff hold, is what widens the result beyond the caller's own reports.
   */
  list: Tapi.get<{ response: Array<Issue> }>()({
    endpoint: "/issue",
  }),
  /**
   * Update the status of an issue.
   *
   * Requires `ManageIssues`, which only platform staff hold.
   */
  setStatus: Tapi.put<{ path: { issue_uid: Uid }; body: SetIssueStatusRequest; response: null }>()({
    endpoint: "/issue/:issue_uid/status",
  }),
};
