// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateIssueForm } from "../../types/issue/CreateIssueForm";
import type { CreateIssueResponse } from "../../types/issue/CreateIssueResponse";
import type { Issue } from "../../types/domain/Issue";
import type { SetIssueStatusRequest } from "../../types/issue/SetIssueStatusRequest";
import type { Uid } from "../../types/primitives/Uid";

export const issue = {
  /**
   * Count issues.
   *
   * Requires `ViewIssues`, which only platform staff hold.
   */
  count: Tapi.get<{ response: number }>()({
    endpoint: "/issue/count",
  }),
  /**
   * Report a new issue (severity, description, details, and 1–10 screenshots) recorded under the caller's own user. The screenshots become hosted media named by `Issue.screenshots`, served by `media.serve` to platform staff holding `ViewIssues`.
   *
   * Any authenticated user. Rejected when the platform is at its open-issue cap, and — when screenshots are attached — when the caller trips the per-user file-upload throttle.
   */
  create: Tapi.post<{ formData: CreateIssueForm; response: CreateIssueResponse }>()({
    endpoint: "/issue",
  }),
  /**
   * Fetch a single issue by uid.
   *
   * Requires `ViewIssues`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { issue_uid: Uid }; response: Issue }>()({
    endpoint: "/issue/:issue_uid",
  }),
  /**
   * List issues.
   *
   * Requires `ViewIssues`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<Issue> }>()({
    endpoint: "/issue",
  }),
  /**
   * Update the status of an issue.
   *
   * Requires `ManageIssues`, which only platform staff hold.
   */
  setStatus: Tapi.put<{ path: { issue_uid: Uid }; body: SetIssueStatusRequest; response: null }>()({
    endpoint: "/issue/:issue_uid/status",
  }),
};
