// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { GetWebhookQuery } from "../../types/event/GetWebhookQuery";
import type { SetWebhookRequest } from "../../types/event/SetWebhookRequest";
import type { SetWebhookResponse } from "../../types/event/SetWebhookResponse";
import type { Uid } from "../../types/primitives/Uid";
import type { Webhook } from "../../types/database/Webhook";

export const eventWebhook = {
  /**
   * Remove the group's outbound webhook, dropping its pending deliveries.
   *
   * Requires `ManageWebhook` in the webhook's group.
   */
  delete: Tapi.delete<{ path: { webhook_uid: Uid }; response: null }>()({
    endpoint: "/event/webhook/:webhook_uid",
  }),
  /**
   * Fetch the group's outbound webhook configuration (the secret is never
   * returned here).
   *
   * Requires `ViewWebhook` in the target group; group-scoped API keys read their own group, others must name it.
   */
  get: Tapi.get<{ query: GetWebhookQuery; response: Webhook | null }>()({
    endpoint: "/event/webhook",
  }),
  /**
   * Configure (create or replace) the group's outbound webhook: the group's
   * events (optionally narrowed by kind/channel filters) are POSTed to the
   * URL in signed batches.
   *
   * Requires `ManageWebhook` in the target group; group-scoped API keys configure their own group, others must name it.
   */
  set: Tapi.put<{ body: SetWebhookRequest; response: SetWebhookResponse }>()({
    endpoint: "/event/webhook",
  }),
};
