// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CommentMessageRequest } from "../../types/engagement/CommentMessageRequest";
import type { ListMentionsQuery } from "../../types/engagement/ListMentionsQuery";
import type { Mention } from "../../types/database/Mention";
import type { Uid } from "../../types/primitives/Uid";

export const mention = {
  /**
   * Poll the mention feed: mentions with `id` greater than `since_id`, oldest
   * first (Instagram only — the account mentioned in captions or comments).
   *
   * Requires `ViewComments`; the feed covers only mentions of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListMentionsQuery; response: Array<Mention> }>()({
    endpoint: "/mention",
  }),
  /**
   * Reply to an Instagram mention (in the mentioned media's comments).
   *
   * Requires `ReplyComments` in the account's group.
   */
  reply: Tapi.post<{ path: { social_account_uid: Uid; mention_uid: Uid }; body: CommentMessageRequest; response: null }>()({
    endpoint: "/social-account/:social_account_uid/mention/:mention_uid/reply",
  }),
};
