// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ConversationInsightQuery } from "../../types/insight/ConversationInsightQuery";
import type { ConversationInsightResponse } from "../../types/insight/ConversationInsightResponse";
import type { InsightQueryRequest } from "../../types/insight/InsightQueryRequest";
import type { InsightQueryResponse } from "../../types/insight/InsightQueryResponse";
import type { PostingInsightQuery } from "../../types/insight/PostingInsightQuery";
import type { PostingInsightResponse } from "../../types/insight/PostingInsightResponse";

export const insight = {
  /**
   * Customer service over a scope per hour, day, week or month. A customer
   * message opens a request; later customer messages join it until the account
   * replies, or until the customer writes again after 24 hours without a reply.
   * The wait runs from the request's first message to the account's next
   * message, whoever or whatever sent it; a request never answered is counted
   * only as an atendimento. A request opens an atendimento
   * when the customer writes first or after 24 hours of silence. Requests and
   * outreach belong to the period they started in. New conversations count each conversation's first
   * message ever. Periods align to `utc_offset_minutes`; weeks start on
   * Monday.
   *
   * Requires `ViewMessages`; covers only accounts of groups where the caller holds it, narrowed by `group_uid`, `social_account_uids` (each must be in scope) and `channels`. Hourly periods over at most 31 days, the others over at most 731 (400 beyond).
   */
  conversation: Tapi.post<{ body: ConversationInsightQuery; response: ConversationInsightResponse }>()({
    endpoint: "/insight/conversation",
  }),
  /**
   * Platform posts published over a scope per hour, day, week or month,
   * counted at their publication time; posts removed from the platform are
   * left out. Periods align to `utc_offset_minutes`; weeks start on Monday.
   *
   * Requires `ViewPosts`; covers only accounts of groups where the caller holds it, narrowed by `group_uid`, `social_account_uids` (each must be in scope) and `channels`. Hourly periods over at most 31 days, the others over at most 731 (400 beyond).
   */
  posting: Tapi.post<{ body: PostingInsightQuery; response: PostingInsightResponse }>()({
    endpoint: "/insight/posting",
  }),
  /**
   * Aggregate collected metrics over many accounts of one channel, by day,
   * week or month. Only accounts of the declared channel take part; a named
   * account of another channel is refused. Breakdown metrics (demographics)
   * cannot be aggregated.
   *
   * Requires `ViewInsights` in every group the query reaches; accounts the caller may not see are refused.
   */
  query: Tapi.post<{ body: InsightQueryRequest; response: InsightQueryResponse }>()({
    endpoint: "/insight/query",
  }),
};
