// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { InsightQueryRequest } from "../../types/insight/InsightQueryRequest";
import type { InsightQueryResponse } from "../../types/insight/InsightQueryResponse";

export const insight = {
  /**
   * Aggregate collected metrics over many accounts of one channel, by day,
   * week or month. Only accounts of the declared channel take part; a named
   * account of another channel is refused. Breakdown metrics (demographics)
   * cannot be aggregated.
   *
   * Requires `ViewInsights` in every group the query reaches; accounts the caller may not see are refused.
   */
  query: Tapi.post<{ body: InsightQueryRequest; response: InsightQueryResponse }>()({
    endpoint: "/insight/query",
  }),
};
