// This file was generated by tapir. Do not edit this file manually.
import type { PostContent } from "../types/PostContent";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type CreatePostRequest = {
  social_account_uid: Uid,
  content: PostContent,
  /**
   * Hub-side schedule: when set (future instant), the post is stored as
   * `scheduled` and published by the hub when due — uniform across channels.
   */
  scheduled_at: Timestamp | null,
};
