// This file was generated by tapir. Do not edit this file manually.
import type { Number1_200 } from "../primitives/Number1_200";
import type { Uid } from "../primitives/Uid";

export type ListPostsQuery = {
  group_uid: Uid | null,
  social_account_uid: Uid | null,
  limit: Number1_200 | null,
};
