// This file was generated by tapir. Do not edit this file manually.
import type { Number1_200 } from "../primitives/Number1_200";
import type { Uid } from "../primitives/Uid";

export type ListPostsQuery = {
  /**
   * Narrow to these groups, each one the caller may see; omit for everything the caller may see.
   */
  group_uids: Array<Uid> | null,
  /**
   * Narrow to these accounts, each one in scope; naming any account overrides the groups.
   */
  social_account_uids: Array<Uid> | null,
  limit: Number1_200 | null,
};
