// This file was generated by tapir. Do not edit this file manually.
import type { Number1_200 } from "../primitives/Number1_200";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type ListSocialPostsQuery = {
  group_uid: Uid | null,
  social_account_uid: Uid | null,
  /**
   * The platform post of one hub post.
   */
  post_uid: Uid | null,
  /**
   * Only posts with at least one third-party comment the account has not answered.
   */
  unanswered_only: boolean,
  /**
   * Page cursor: only posts published strictly before this instant (ms).
   */
  before: Timestamp | null,
  limit: Number1_200 | null,
};
