// This file was generated by tapir. Do not edit this file manually.

export type PostInsightsQuery = {
  /**
   * Meta metric names (comma-separated); defaults per media kind.
   */
  metrics: string | null,
  period: string | null,
};
