// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged pin toggle — only facebook Page timelines have a pin
 * surface, so no other channel's shape deserializes. The `channel` must
 * match the post's.
 */
export type SetPostPinnedRequest = {
  "channel": "facebook",
  pinned: boolean,
};
