// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged comment toggle — the one edit Instagram's API supports;
 * facebook has no per-post comment toggle, so its shape does not
 * deserialize. The `channel` must match the post's.
 */
export type SetPostCommentsRequest = {
  "channel": "instagram",
  enabled: boolean,
};
