// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged hide toggle — only facebook Page timelines have a hide
 * surface, so no other channel's shape deserializes. The `channel` must
 * match the post's.
 */
export type SetPostHiddenRequest = {
  "channel": "facebook",
  hidden: boolean,
};
