// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type SocialPostSummaryQuery = {
  group_uid: Uid | null,
  social_account_uid: Uid | null,
  /**
   * Only posts with at least one third-party comment the account has not answered.
   */
  unanswered_only: boolean,
  /**
   * Only posts published at or after this instant (ms).
   */
  since: Timestamp | null,
  /**
   * Only posts published before this instant (ms).
   */
  until: Timestamp | null,
  /**
   * Caption search: a case-insensitive substring.
   */
  q: string | null,
};
