// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type SocialPostSummaryQuery = {
  /**
   * Narrow to these groups, each one the caller may see; omit for everything the caller may see.
   */
  group_uids: Array<Uid> | null,
  /**
   * Narrow to these accounts, each one in scope; naming any account overrides the groups.
   */
  social_account_uids: Array<Uid> | null,
  /**
   * Only posts with at least one third-party comment the account has not answered.
   */
  unanswered_only: boolean,
  /**
   * Only posts published at or after this instant (ms).
   */
  since: Timestamp | null,
  /**
   * Only posts published before this instant (ms).
   */
  until: Timestamp | null,
  /**
   * Caption search: a case-insensitive substring.
   */
  q: string | null,
};
