// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged edit payload — only facebook can edit a published post's
 * text on the platform (the Instagram API cannot edit captions), so no
 * other channel's shape deserializes. The `channel` must match the post's.
 */
export type UpdatePostRequest = {
  "channel": "facebook",
  /**
   * The new text: `message` on page posts, `description` on videos/reels;
   * stories carry no text.
   */
  message: string,
};
