// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../../runtime";
import type { UserMfaEnrollConfirmRequest } from "../../../../types/user_mfa/UserMfaEnrollConfirmRequest";
import type { UserMfaEnrollSessionResponse } from "../../../../types/user_mfa/UserMfaEnrollSessionResponse";
import type { UserMfaEnrollTotpStartRequest } from "../../../../types/user_mfa/UserMfaEnrollTotpStartRequest";
import type { UserMfaEnrollTotpStartResponse } from "../../../../types/user_mfa/UserMfaEnrollTotpStartResponse";

export const totp = {
  /**
   * Confirm bootstrap TOTP enrollment with a code and, on success, mint a user session token.
   *
   * Public — no authentication required; the request is gated solely by the ephemeral enrollment token in the body.
   */
  confirm: Tapi.post<{ body: UserMfaEnrollConfirmRequest; response: UserMfaEnrollSessionResponse }>()({
    endpoint: "/user-session/mfa/enroll/totp/confirm",
  }),
  /**
   * Begin TOTP enrollment during forced bootstrap, returning the secret, otpauth URI, and QR code.
   *
   * Public — no authentication required; the request is gated solely by the ephemeral enrollment token in the body.
   */
  start: Tapi.post<{ body: UserMfaEnrollTotpStartRequest; response: UserMfaEnrollTotpStartResponse }>()({
    endpoint: "/user-session/mfa/enroll/totp/start",
  }),
};
