// This file was generated by tapir. Do not edit this file manually.
import type { ContactImport } from "../database/ContactImport";
import type { ContactImportCounts } from "./ContactImportCounts";
import type { Uid } from "../primitives/Uid";

/**
 * One import with everything its page renders: the row, the accounts it
 * distributes over, the derived counters, and the drain estimate.
 */
export type ContactImportDetail = {
  import: ContactImport,
  social_account_uids: Array<Uid>,
  counts: ContactImportCounts,
  /**
   * Estimated milliseconds until the pending rows drain at current pacing;
   * `null` when nothing is pending.
   */
  eta_ms: number | null,
};
