// This file was generated by tapir. Do not edit this file manually.

/**
 * Row counts by verdict — always derived from the rows, never stored, so
 * they cannot drift from the ledger they summarize.
 */
export type ContactImportCounts = {
  total: number,
  pending: number,
  missing_phone: number,
  invalid_phone: number,
  invalid_name: number,
  duplicate_in_file: number,
  imported: number,
  not_on_whatsapp: number,
  check_failed: number,
  skipped: number,
};
