// This file was generated by tapir. Do not edit this file manually.
import type { ContactImportRowVerdict } from "../types/ContactImportRowVerdict";
import type { Number1_500 } from "../primitives/Number1_500";

export type ListImportRowsQuery = {
  verdict: ContactImportRowVerdict | null,
  /**
   * Keyset cursor: only rows with `id` strictly greater are returned.
   */
  after_id: number | null,
  limit: Number1_500 | null,
};
