// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";

/**
 * A staged row's fix: the full corrected pair, re-parsed under the import's
 * mapping. An empty phone re-verdicts as `missing_phone`; a `null` alias
 * clears it.
 */
export type UpdateImportRowRequest = {
  /**
   * The corrected phone, in any written form the numbering plan reads.
   */
  phone: string,
  alias: Name | null,
};
