// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { Text1_255 } from "../primitives/Text1_255";

export type UploadContactImportForm = {
  /**
   * The operator's name for the batch.
   */
  name: Name,
  /**
   * The file's own name, for provenance — the multipart layer deliberately
   * keeps client filenames out of the stored part, so it rides as a field.
   */
  filename: Text1_255,
  /**
   * The accounts the load distributes over, comma-separated uids. Every one
   * must be a whatsapp session account (stevo or native) of one same group,
   * which becomes the import's group.
   */
  social_account_uids: string,
  /**
   * 0-based index of the phone column in the header row.
   */
  phone_column: string,
  /**
   * 0-based index of the name column; omit for no name column.
   */
  name_column: string | null,
  /**
   * Country calling code bare numbers are read against; defaults to `55`.
   */
  default_calling_code: string | null,
  file: File,
};
