// This file was generated by tapir. Do not edit this file manually.

export type AnswerBusinessQuestionRequest = {
  /**
   * The question's name, `locations/{id}/questions/{id}`.
   */
  question: string,
  text: string,
};
