// This file was generated by tapir. Do not edit this file manually.
import type { DailyMetricSeries } from "../google/DailyMetricSeries";

export type BusinessPerformanceResponse = {
  /**
   * One day-by-day series per requested metric.
   */
  series: Array<DailyMetricSeries>,
};
