// This file was generated by tapir. Do not edit this file manually.

export type BusinessMenusQuery = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
};
