// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type BusinessPerformanceQuery = {
  /**
   * The location's v1 name, `locations/{id}`.
   */
  location: string,
  /**
   * Comma-separated metric names (see `DAILY_METRICS` in the bindings); at
   * most 10 per call. Omitted = the core set (impressions, conversations,
   * direction requests, call clicks, website clicks).
   */
  metrics: string | null,
  /**
   * Range bounds, inclusive, resolved to UTC calendar dates.
   */
  start: Timestamp,
  end: Timestamp,
};
