// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type BusinessKeywordsQuery = {
  /**
   * The location's v1 name, `locations/{id}`.
   */
  location: string,
  /**
   * Range bounds, inclusive, resolved to UTC calendar months. Keyword data
   * lags — the current month is usually empty.
   */
  start: Timestamp,
  end: Timestamp,
  page_token: string | null,
};
