// This file was generated by tapir. Do not edit this file manually.
import type { GoogleCapability } from "./GoogleCapability";
import type { Uid } from "../primitives/Uid";

export type ConnectGoogleRequest = {
  group_uid: Uid,
  /**
   * At least one; connecting later with more capabilities extends the grant
   * (incremental auth) instead of replacing it.
   */
  capabilities: Array<GoogleCapability>,
};
