// This file was generated by tapir. Do not edit this file manually.
import type { MediaItem } from "../google/MediaItem";

export type CreateBusinessMediaRequest = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  item: MediaItem,
};
