// This file was generated by tapir. Do not edit this file manually.
import type { LocalPost } from "../google/LocalPost";

export type CreateBusinessPostRequest = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  post: LocalPost,
};
