// This file was generated by tapir. Do not edit this file manually.

export type DeleteBusinessMediaQuery = {
  /**
   * The item's v4 name, `accounts/{id}/locations/{id}/media/{id}`.
   */
  media: string,
};
