// This file was generated by tapir. Do not edit this file manually.

export type DeleteBusinessPostQuery = {
  /**
   * The post's v4 name, `accounts/{id}/locations/{id}/localPosts/{id}`.
   */
  post: string,
};
