// This file was generated by tapir. Do not edit this file manually.

export type DeleteBusinessReplyQuery = {
  /**
   * The review's v4 name, `accounts/{id}/locations/{id}/reviews/{id}`.
   */
  review: string,
};
