// This file was generated by tapir. Do not edit this file manually.

export type DeleteBusinessAnswerQuery = {
  /**
   * The question's name, `locations/{id}/questions/{id}`.
   */
  question: string,
};
