// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type FreeBusyRequest = {
  calendar_ids: Array<string>,
  time_min: Timestamp,
  time_max: Timestamp,
  /**
   * IANA name for the response intervals; UTC when omitted.
   */
  time_zone: string | null,
};
