// This file was generated by tapir. Do not edit this file manually.
import type { CalendarBusy } from "./CalendarBusy";

export type FreeBusyResponse = {
  /**
   * One outcome per requested calendar, in request order.
   */
  calendars: Array<CalendarBusy>,
};
