// This file was generated by tapir. Do not edit this file manually.
import type { GoogleCapability } from "./GoogleCapability";

export type GoogleConfirmRequest = {
  token: string,
  /**
   * The capabilities to enable on the hub account; the stored scope keeps
   * only these families, even when the grant covers more.
   */
  capabilities: Array<GoogleCapability>,
};
