// This file was generated by tapir. Do not edit this file manually.
import type { GoogleCapability } from "./GoogleCapability";

/**
 * What a stashed Google grant covers, for the capability-selection screen.
 */
export type GoogleReview = {
  email: string,
  name: string,
  avatar_url: string | null,
  /**
   * The account is already registered in the target group — confirming
   * refreshes its grant and replaces its enabled capabilities.
   */
  connected: boolean,
  /**
   * Capabilities the grant covers — the selectable set. Incremental auth
   * unions grants, so this may exceed what was just requested.
   */
  granted: Array<GoogleCapability>,
  /**
   * Capabilities the admin asked for when starting the flow — the
   * pre-checked set.
   */
  requested: Array<GoogleCapability>,
};
