// This file was generated by tapir. Do not edit this file manually.

export type ListBusinessMediaQuery = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  /**
   * Page size; capped at 100, default 50.
   */
  page_size: number | null,
  page_token: string | null,
};
