// This file was generated by tapir. Do not edit this file manually.

export type ListBusinessLocationsQuery = {
  /**
   * The owning account, `accounts/{id}` (from `business.listAccounts`).
   */
  account: string,
  page_token: string | null,
};
