// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100 } from "../primitives/Number1_100";

export type ListBusinessQuestionsQuery = {
  /**
   * The location's v1 name, `locations/{id}`.
   */
  location: string,
  /**
   * Page size; capped at 100 (Google's limit), default 20.
   */
  page_size: Number1_100 | null,
  page_token: string | null,
};
