// This file was generated by tapir. Do not edit this file manually.

export type ListBusinessReviewsQuery = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  /**
   * Page size; capped at 50 (Google's limit), default 50.
   */
  page_size: number | null,
  page_token: string | null,
  /**
   * `update_time desc` (default), `rating` or `rating desc`.
   */
  order_by: string | null,
};
