// This file was generated by tapir. Do not edit this file manually.

export type ListBusinessQuestionsQuery = {
  /**
   * The location's v1 name, `locations/{id}`.
   */
  location: string,
  /**
   * Page size; capped at 100, default 20.
   */
  page_size: number | null,
  page_token: string | null,
};
