// This file was generated by tapir. Do not edit this file manually.

export type ListBusinessPostsQuery = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  /**
   * Page size; capped at 100 (Google's limit), default 20.
   */
  page_size: number | null,
  page_token: string | null,
};
