// This file was generated by tapir. Do not edit this file manually.
import type { Number1_2500 } from "../primitives/Number1_2500";
import type { Timestamp } from "../primitives/Timestamp";

export type ListCalendarEventsQuery = {
  /**
   * The calendar to list (its id — usually an email address).
   */
  calendar_id: string,
  time_min: Timestamp,
  time_max: Timestamp,
  /**
   * Free-text search over the events.
   */
  q: string | null,
  /**
   * Continues a previous page (`next_page_token`).
   */
  page_token: string | null,
  /**
   * Page size; capped at 2500 (Google's limit), default 250.
   * Bounded by the type like every other page size, rather than silently
   * clamped: a caller asking for more than Google's own 2500 ceiling gets
   * told so. `Number` deserialization enforces it.
   */
  max_results: Number1_2500 | null,
};
