// This file was generated by tapir. Do not edit this file manually.
import type { LocalPost } from "../google/LocalPost";

export type UpdateBusinessPostRequest = {
  /**
   * The post's v4 name, `accounts/{id}/locations/{id}/localPosts/{id}`.
   */
  post: string,
  /**
   * The new values for the masked fields.
   */
  update: LocalPost,
  /**
   * Comma-separated camelCase fields to write (e.g. `summary,callToAction`).
   */
  update_mask: string,
};
