// This file was generated by tapir. Do not edit this file manually.
import type { FoodMenus } from "../google/FoodMenus";

export type UpdateBusinessMenusRequest = {
  /**
   * The location's v4 name, `accounts/{id}/locations/{id}`.
   */
  location: string,
  /**
   * The full menu set — the update replaces the menus wholesale.
   */
  menus: FoodMenus,
};
