// This file was generated by tapir. Do not edit this file manually.
import type { Location } from "../google/Location";

export type UpdateBusinessLocationRequest = {
  /**
   * The location's v1 name, `locations/{id}`.
   */
  location: string,
  /**
   * The new values for the masked fields.
   */
  update: Location,
  /**
   * Comma-separated camelCase fields to write (e.g.
   * `profile.description,phoneNumbers.primaryPhone,websiteUri`); a masked
   * field absent from `update` is cleared.
   */
  update_mask: string,
};
