// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ConnectGoogleRequest } from "../../types/google_account/ConnectGoogleRequest";
import type { ConnectGoogleResponse } from "../../types/google_account/ConnectGoogleResponse";
import type { GoogleCallbackQuery } from "../../types/google_account/GoogleCallbackQuery";
import type { GoogleConfirmRequest } from "../../types/google_account/GoogleConfirmRequest";
import type { GoogleReview } from "../../types/google_account/GoogleReview";
import type { GoogleReviewQuery } from "../../types/google_account/GoogleReviewQuery";

export const google = {
  /**
   * Google OAuth redirect target: consumes the state, exchanges the code, and
   * stashes the grant snapshot for review — nothing is registered yet; always
   * redirects the browser back to the frontend, with a review token on
   * success.
   *
   * Public — no authentication required; authorization comes from the one-shot state token issued by `google.connect`.
   */
  callback: Tapi.get<{ query: GoogleCallbackQuery; response: null }>()({
    endpoint: "/google/callback",
  }),
  /**
   * Start the Google OAuth flow for a group with the chosen capabilities
   * (calendar, business profile), returning the consent dialog URL; the
   * granted account is connected to the group by the callback.
   *
   * Requires `ConnectSocialAccounts` in the named group.
   */
  connect: Tapi.post<{ body: ConnectGoogleRequest; response: ConnectGoogleResponse }>()({
    endpoint: "/google/connect",
  }),
  /**
   * Register (or refresh) the account from a stashed grant, enabling exactly
   * the chosen capabilities (one-shot). A granted-but-unchosen capability
   * stays out of the hub until a future connect enables it.
   *
   * Requires `ConnectSocialAccounts` in the group the stashed grant targets.
   */
  connectConfirm: Tapi.post<{ body: GoogleConfirmRequest; response: null }>()({
    endpoint: "/google/connect/confirm",
  }),
  /**
   * Load a stashed Google grant for the capability-selection screen: the
   * account's identity plus which capabilities the grant covers and which
   * were requested. Repeatable; only confirm consumes the stash.
   *
   * Requires `ConnectSocialAccounts` in the group the stashed grant targets.
   */
  connectReview: Tapi.get<{ query: GoogleReviewQuery; response: GoogleReview }>()({
    endpoint: "/google/connect/review",
  }),
};
