// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { InsightHistoryQuery } from "../../types/insight/InsightHistoryQuery";
import type { ListSocialPostsQuery } from "../../types/post/ListSocialPostsQuery";
import type { SocialPost } from "../../types/domain/SocialPost";
import type { SocialPostInsightHistory } from "../../types/insight/SocialPostInsightHistory";
import type { SocialPostSummary } from "../../types/domain/SocialPostSummary";
import type { SocialPostSummaryQuery } from "../../types/post/SocialPostSummaryQuery";
import type { Uid } from "../../types/primitives/Uid";

export const socialPost = {
  /**
   * Fetch one platform post by uid.
   *
   * Requires `ViewPosts` in the post's group.
   */
  get: Tapi.get<{ path: { social_post_uid: Uid }; response: SocialPost }>()({
    endpoint: "/social-post/:social_post_uid",
  }),
  /**
   * Day-by-day history of a platform post's collected metrics, in its channel's
   * own vocabulary. Posts are re-read on a schedule that slows with age (every
   * 5 minutes in the first day, every 3 hours after a month), so the newest day
   * is often still partial.
   *
   * Requires `ViewInsights` in the group of the post's account.
   */
  insightsHistory: Tapi.get<{ path: { social_post_uid: Uid }; query: InsightHistoryQuery; response: SocialPostInsightHistory }>()({
    endpoint: "/social-post/:social_post_uid/insight/history",
  }),
  /**
   * List the posts that stand on the platforms, newest first: every post the
   * hub knows about an account, published through it or not, with the
   * platform's comment and like counts and how many third-party comments the
   * account has not answered. `before` pages backwards.
   *
   * Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListSocialPostsQuery; response: Array<SocialPost> }>()({
    endpoint: "/social-post",
  }),
  /**
   * Totals over the platform posts in scope: how many there are, their
   * comments and the ones still unanswered. The list's pages never add up to
   * these; this does.
   *
   * Requires `ViewPosts`; counts only posts of groups where the caller holds it, narrowed by `group_uid` / `social_account_uid` when given.
   */
  summary: Tapi.get<{ query: SocialPostSummaryQuery; response: SocialPostSummary }>()({
    endpoint: "/social-post/summary",
  }),
};
