// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { InsightHistoryQuery } from "../../types/insight/InsightHistoryQuery";
import type { ListSocialPostsQuery } from "../../types/post/ListSocialPostsQuery";
import type { SocialPost } from "../../types/domain/SocialPost";
import type { SocialPostInsightHistory } from "../../types/insight/SocialPostInsightHistory";
import type { Uid } from "../../types/primitives/Uid";

export const socialPost = {
  /**
   * Fetch one platform post by uid.
   *
   * Requires `ViewPosts` in the post's group.
   */
  get: Tapi.get<{ path: { social_post_uid: Uid }; response: SocialPost }>()({
    endpoint: "/social-post/:social_post_uid",
  }),
  /**
   * Day-by-day history of a platform post's collected metrics, in its channel's
   * own vocabulary. Posts are re-read on a schedule that slows with age (every
   * 5 minutes in the first day, every 3 hours after a month), so the newest day
   * is often still partial.
   *
   * Requires `ViewInsights` in the group of the post's account.
   */
  insightsHistory: Tapi.get<{ path: { social_post_uid: Uid }; query: InsightHistoryQuery; response: SocialPostInsightHistory }>()({
    endpoint: "/social-post/:social_post_uid/insight/history",
  }),
  /**
   * List the posts that stand on the platforms, newest first: every post the
   * hub knows about an account, published through it or not, with the
   * platform's comment and like counts and how many third-party comments the
   * account has not answered. `before` pages backwards.
   *
   * Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListSocialPostsQuery; response: Array<SocialPost> }>()({
    endpoint: "/social-post",
  }),
  /**
   * Start a re-read of the account's posts from its platform in the background
   * and answer at once: the 25 most recent plus every post with comments, their
   * thumbnails and, for posts seen for the first time, their whole comment
   * thread. Every post the sync touches emits `social_post_updated`. Allowed
   * once per account every five minutes; the hub runs it by itself once when an
   * account connects. Only facebook_alt and instagram_alt accounts can be synced.
   *
   * Requires `ViewPosts` in the account's group; throttled to one call per account every five minutes.
   */
  sync: Tapi.post<{ path: { social_account_uid: Uid }; response: null }>()({
    endpoint: "/social-account/:social_account_uid/social-post/sync",
  }),
};
