// This file was generated by tapir. Do not edit this file manually.

export type VersionResponse = {
  /**
   * The release the server runs — the number the event socket's `welcome`
   * frame also carries.
   */
  version: string,
};
