// This file was generated by tapir. Do not edit this file manually.

/**
 * What still acts on an account from inside its group, and so has to travel
 * with it when the account changes group. Finished work stays behind: a
 * canceled campaign, or a contact import that is done or canceled, is not
 * counted.
 */
export type AccountReferences = {
  /**
   * GoHighLevel locations delivering into this account.
   */
  ghl_locations: number,
  /**
   * Campaigns sending only from this account.
   */
  campaigns: number,
  /**
   * Contact imports loading only into this account.
   */
  contact_imports: number,
  /**
   * Campaigns that also send from other accounts of the group, which cannot follow it.
   */
  shared_campaigns: number,
  /**
   * Contact imports that also load into other accounts of the group, which cannot follow it.
   */
  shared_contact_imports: number,
};
