// This file was generated by tapir. Do not edit this file manually.

export type AuditResource = "auth" | "user" | "group" | "user_invite" | "user_session" | "rate_limit" | "api_key" | "email" | "user_mfa" | "issue" | "social_account" | "message" | "post" | "webhook" | "comment" | "media" | "template" | "conversation" | "google_account" | "user_group" | "call" | "ghl_location" | "contact_import" | "campaign";

/** Every `AuditResource`, in declaration order. */
export const AUDIT_RESOURCE = ["auth", "user", "group", "user_invite", "user_session", "rate_limit", "api_key", "email", "user_mfa", "issue", "social_account", "message", "post", "webhook", "comment", "media", "template", "conversation", "google_account", "user_group", "call", "ghl_location", "contact_import", "campaign"] as const satisfies readonly AuditResource[];
