// This file was generated by tapir. Do not edit this file manually.

/**
 * The three video verbs a call carries, which are not interchangeable:
 * `Start` sends an upgrade *request* and holds our video until the peer
 * accepts, `Accept` answers the peer's request, and `Stop` withdraws video
 * entirely. Turning the camera on and off inside an already-video call is not
 * one of them — that is an ungated toggle, since no handshake is owed.
 */
export type CallVideoAction = "start" | "accept" | "stop";

/** Every `CallVideoAction`, in declaration order. */
export const CALL_VIDEO_ACTION = ["start", "accept", "stop"] as const satisfies readonly CallVideoAction[];
