// This file was generated by tapir. Do not edit this file manually.
import type { CampaignRecipientStatus } from "./CampaignRecipientStatus";
import type { CampaignSkipReason } from "./CampaignSkipReason";
import type { Name } from "../primitives/Name";
import type { Phone } from "../primitives/Phone";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One audience entry — a number, the account assigned to reach it — and its
 * outcome. The `pending` rows of a campaign, per account in `id` order, are
 * that account's queue: the message-table pattern, so a restart resumes the
 * drip from the table itself.
 */
export type CampaignRecipient = {
  id: number,
  campaign_uid: Uid,
  /**
   * E.164, the audience key: one row per number per campaign.
   */
  phone: Phone,
  /**
   * The name known for the number at build — an import's name column, or
   * an existing conversation's — for `{{nome}}` on a conversation that has
   * none yet, and applied as its alias when it is discovered.
   */
  alias: Name | null,
  /**
   * The account assigned to send, by the balanced-with-affinity
   * distribution at build.
   */
  social_account_uid: Uid,
  /**
   * The conversation on that account; `None` until the dispatcher
   * discovers it — a "new conversation" for the operator.
   */
  conversation_uid: Uid | null,
  status: CampaignRecipientStatus,
  skip_reason: CampaignSkipReason | null,
  /**
   * The wheel's pick, recorded at dispatch.
   */
  template_uid: Uid | null,
  message_uid: Uid | null,
  error: string | null,
  dispatched_at: Timestamp | null,
};
