// This file was generated by tapir. Do not edit this file manually.
import type { CampaignStatus } from "./CampaignStatus";
import type { Name } from "../primitives/Name";
import type { Number0_1439 } from "../primitives/Number0_1439";
import type { Number1000_86400000 } from "../primitives/Number1000_86400000";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_127 } from "../primitives/Number1_127";
import type { Number1_365 } from "../primitives/Number1_365";
import type { TemplateRotation } from "./TemplateRotation";
import type { Timestamp } from "../primitives/Timestamp";
import type { Timezone } from "../primitives/Timezone";
import type { Uid } from "../primitives/Uid";

/**
 * One bulk-messaging campaign: the schedule, the ceilings and the template
 * wheel's cursor. The audience lives in `campaign_recipient`, the wheel in
 * `campaign_template`; every progress counter is derived from them.
 */
export type Campaign = {
  uid: Uid,
  group_uid: Uid,
  name: Name,
  status: CampaignStatus,
  min_interval_ms: Number1000_86400000,
  max_interval_ms: Number1000_86400000,
  timezone: Timezone,
  window_start_minute: Number0_1439,
  window_end_minute: Number0_1439,
  weekdays: Number1_127,
  starts_at: Timestamp | null,
  ends_at: Timestamp | null,
  max_per_day: Number1_100000 | null,
  max_per_account_per_day: Number1_100000 | null,
  template_mode: TemplateRotation,
  /**
   * The linear wheel's position; advances on every dispatch, in either mode.
   */
  template_cursor: number,
  cooldown_days: Number1_365 | null,
  created_by_uid: Uid | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
