// This file was generated by tapir. Do not edit this file manually.

/**
 * One recipient's outcome. `Sent` means the message entered the send queue —
 * the platform's own verdict (delivered, read, failed) lives on the message
 * row the recipient points at, never copied here.
 */
export type CampaignRecipientStatus = "pending" | "sent" | "failed" | "skipped" | "canceled";

/** Every `CampaignRecipientStatus`, in declaration order. */
export const CAMPAIGN_RECIPIENT_STATUS = ["pending", "sent", "failed", "skipped", "canceled"] as const satisfies readonly CampaignRecipientStatus[];
