// This file was generated by tapir. Do not edit this file manually.

/**
 * The platform behind a channel, which fixes what a conversation allows:
 * Messenger rules for `facebook`, Instagram messaging rules for
 * `instagram`, WhatsApp rules for `whatsapp` (the linked-device transport
 * lifts the window and template rules).
 */
export type ChannelFamily = "facebook" | "instagram" | "whatsapp";

/** Every `ChannelFamily`, in declaration order. */
export const CHANNEL_FAMILY = ["facebook", "instagram", "whatsapp"] as const satisfies readonly ChannelFamily[];
