// This file was generated by tapir. Do not edit this file manually.
import type { ContactImportRowVerdict } from "./ContactImportRowVerdict";
import type { Name } from "../primitives/Name";
import type { Phone } from "../primitives/Phone";
import type { Uid } from "../primitives/Uid";

/**
 * One CSV record and its verdict. The `pending` rows of an account, in `id`
 * order, are that account's load queue — the message-table pattern, so a
 * restart resumes the load from the table itself. `phone` and `alias` only
 * ever hold values the newtypes accepted; an invalid cell stays in `raw`
 * (and `detail`), which is what keeps the typed decode total.
 */
export type ContactImportRow = {
  id: number,
  import_uid: Uid,
  /**
   * 1-based record number in the source file.
   */
  line: number,
  /**
   * The record's cells as read, indexing into the import's `columns`.
   */
  raw: Array<string>,
  phone: Phone | null,
  alias: Name | null,
  verdict: ContactImportRowVerdict,
  detail: string | null,
  social_account_uid: Uid | null,
  conversation_uid: Uid | null,
};
