// This file was generated by tapir. Do not edit this file manually.

/**
 * Where an import stands in its lifecycle. Parsing is synchronous, so an
 * import is born `Staged` with every row already carrying a parse verdict;
 * `start` moves it to `Loading`, and only `Loading` rows are fed to the
 * per-account loaders — pausing simply makes the queue queries skip them.
 */
export type ContactImportStatus = "staged" | "loading" | "paused" | "done" | "canceled";

/** Every `ContactImportStatus`, in declaration order. */
export const CONTACT_IMPORT_STATUS = ["staged", "loading", "paused", "done", "canceled"] as const satisfies readonly ContactImportStatus[];
