// This file was generated by tapir. Do not edit this file manually.
import type { EmailKind } from "./EmailKind";
import type { EmailQueueStatus } from "./EmailQueueStatus";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type EmailQueueItem = {
  id: number,
  to_email: string,
  to_name: string | null,
  subject: string,
  template_name: string,
  status: EmailQueueStatus,
  kind: EmailKind,
  target_uid: Uid | null,
  attempts: number,
  /**
   * When set, the worker won't retry this row until `next_retry_at <= now`.
   * `NULL` means "ready immediately" (fresh enqueue or operator-triggered retry).
   */
  next_retry_at: Timestamp | null,
  error_message: string | null,
  created_at: Timestamp,
  sent_at: Timestamp | null,
};
