// This file was generated by tapir. Do not edit this file manually.
import type { ExposureAlert } from "./ExposureAlert";
import type { ExposureBucket } from "./ExposureBucket";

/**
 * The account's exposure over a requested period, hour by hour, plus what the
 * last 24 hours say about it right now.
 */
export type ExposureReport = {
  /**
   * One entry per hour with any activity inside the requested period, oldest
   * first; hours with nothing counted are left out.
   */
  buckets: Array<ExposureBucket>,
  /**
   * Distinct numbers the account has ever talked to.
   */
  unique_contacts: number,
  /**
   * Consecutive latest accepted sends still without a delivery receipt.
   */
  undelivered_streak: number,
  /**
   * Conditions raised by the last 24 hours, whatever period was requested.
   */
  alerts: Array<ExposureAlert>,
};
