// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

/**
 * What one whatsapp account did on the platform in one hour, as the hub
 * counted it: every lookup and send it issued and every enforcement answer it
 * got back.
 */
export type ExposureBucket = {
  /**
   * Start of the hour the counts belong to.
   */
  start: Timestamp,
  /**
   * Number checks (usync) against the platform, one per new number.
   */
  usync: number,
  /**
   * Profile picture fetches, contacts and the account's own included.
   */
  profile_picture: number,
  /**
   * Presence subscriptions opened when an operator focused a conversation.
   */
  presence_subscribe: number,
  /**
   * Messages sent by an operator from the inbox.
   */
  sends_user: number,
  /**
   * Messages sent through the hub api by a machine client.
   */
  sends_api_key: number,
  /**
   * Messages dispatched by a campaign.
   */
  sends_campaign: number,
  /**
   * Messages delivered for a linked GoHighLevel location.
   */
  sends_ghl: number,
  /**
   * First-time contacts the account opened.
   */
  new_contacts: number,
  /**
   * Times whatsapp answered a send or lookup with 429 (rate limited).
   */
  rate_limited: number,
  /**
   * Times whatsapp answered a send with 463 or 475, or reported a reach-out
   * hold on the account.
   */
  reachout_hold: number,
  /**
   * Sends the platform took more than ten seconds to acknowledge.
   */
  slow_acks: number,
  /**
   * Number checks the platform took more than five seconds to answer.
   */
  slow_usync: number,
  /**
   * Sends the platform accepted that still have no delivery receipt an hour
   * later.
   */
  undelivered: number,
};
