// This file was generated by tapir. Do not edit this file manually.

/**
 * A condition in the account's exposure that deserves an operator's eye right
 * now. Raised from the counts of the last 24 hours, never stored: it clears
 * on its own when the counts do.
 */
export type ExposureAlert = "rate_limited" | "reachout_hold" | "undelivered_streak" | "api_key_spike" | "cap_nearly_reached" | "slow_platform";

/** Every `ExposureAlert`, in declaration order. */
export const EXPOSURE_ALERT = ["rate_limited", "reachout_hold", "undelivered_streak", "api_key_spike", "cap_nearly_reached", "slow_platform"] as const satisfies readonly ExposureAlert[];
