// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAltPostMetric } from "./FacebookAltPostMetric";
import type { InsightPoint } from "./InsightPoint";

/**
 * One metric as a day-by-day series.
 */
export type FacebookAltPostSeries = {
  metric: FacebookAltPostMetric,
  points: Array<InsightPoint>,
};
