// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAltAccountMetric } from "./FacebookAltAccountMetric";
import type { InsightPoint } from "./InsightPoint";

/**
 * One metric as a day-by-day series.
 */
export type FacebookAltAccountSeries = {
  metric: FacebookAltAccountMetric,
  points: Array<InsightPoint>,
};
