// This file was generated by tapir. Do not edit this file manually.
import type { FacebookMediaKind } from "./FacebookMediaKind";

export type FacebookSocialPost = {
  media_kind: FacebookMediaKind | null,
};
