// This file was generated by tapir. Do not edit this file manually.

/**
 * Facebook Page post metrics, Meta's own names.
 */
export type FacebookPostMetric = "post_media_view" | "post_total_media_view_unique" | "post_clicks" | "post_reactions_by_type_total" | "total_video_impressions" | "total_video_views" | "post_impressions" | "post_impressions_unique";

/** Every `FacebookPostMetric`, in declaration order. */
export const FACEBOOK_POST_METRIC = ["post_media_view", "post_total_media_view_unique", "post_clicks", "post_reactions_by_type_total", "total_video_impressions", "total_video_views", "post_impressions", "post_impressions_unique"] as const satisfies readonly FacebookPostMetric[];
