// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAccountMetric } from "./FacebookAccountMetric";
import type { Timestamp } from "../primitives/Timestamp";

/**
 * One aggregated period of one metric across the queried subjects.
 */
export type FacebookAccountBucket = {
  period_start: Timestamp,
  metric: FacebookAccountMetric,
  value: number,
  /**
   * How many subjects — accounts, or posts — contributed rows to the period.
   */
  subjects: number,
};
