// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAltPostMetric } from "./FacebookAltPostMetric";
import type { Timestamp } from "../primitives/Timestamp";

/**
 * One aggregated period of one metric across the queried subjects.
 */
export type FacebookAltPostBucket = {
  period_start: Timestamp,
  metric: FacebookAltPostMetric,
  value: number,
  /**
   * How many subjects — accounts, or posts — contributed rows to the period.
   */
  subjects: number,
};
