// This file was generated by tapir. Do not edit this file manually.

/**
 * The kinds a Facebook Page post can be, as the hub published it.
 */
export type FacebookMediaKind = "text" | "link" | "photos" | "video" | "reel" | "photo_story" | "video_story";

/** Every `FacebookMediaKind`, in declaration order. */
export const FACEBOOK_MEDIA_KIND = ["text", "link", "photos", "video", "reel", "photo_story", "video_story"] as const satisfies readonly FacebookMediaKind[];
