// This file was generated by tapir. Do not edit this file manually.
import type { FacebookPostMetric } from "./FacebookPostMetric";
import type { InsightPoint } from "./InsightPoint";

/**
 * One metric as a day-by-day series.
 */
export type FacebookPostSeries = {
  metric: FacebookPostMetric,
  points: Array<InsightPoint>,
};
