// This file was generated by tapir. Do not edit this file manually.
import type { MediaRef } from "./MediaRef";

export type FacebookMedia = {
  "kind": "text",
} | {
  "kind": "link",
  link: string,
} | {
  "kind": "photos",
  photos: Array<MediaRef>,
} | {
  "kind": "video",
  video: MediaRef,
} | {
  "kind": "reel",
  video: MediaRef,
} | {
  "kind": "photo_story",
  photo: MediaRef,
} | {
  "kind": "video_story",
  video: MediaRef,
};
