// This file was generated by tapir. Do not edit this file manually.

/**
 * Facebook post metrics as the alternate gateway reports them.
 */
export type FacebookAltPostMetric = "impressions" | "reach" | "likes" | "comments" | "shares" | "clicks" | "views" | "engagement_rate" | "reactions_like" | "reactions_love" | "reactions_haha" | "reactions_wow" | "reactions_sad" | "reactions_angry" | "reactions_care";

/** Every `FacebookAltPostMetric`, in declaration order. */
export const FACEBOOK_ALT_POST_METRIC = ["impressions", "reach", "likes", "comments", "shares", "clicks", "views", "engagement_rate", "reactions_like", "reactions_love", "reactions_haha", "reactions_wow", "reactions_sad", "reactions_angry", "reactions_care"] as const satisfies readonly FacebookAltPostMetric[];
