// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAccountMetric } from "./FacebookAccountMetric";
import type { InsightPoint } from "./InsightPoint";

/**
 * One metric as a day-by-day series.
 */
export type FacebookAccountSeries = {
  metric: FacebookAccountMetric,
  points: Array<InsightPoint>,
};
