// This file was generated by tapir. Do not edit this file manually.

/**
 * A surface a google grant can cover; the connect asks for a set and the
 * review shows which of them the grant actually returned.
 */
export type GoogleCapability = "calendar" | "business";

/** Every `GoogleCapability`, in declaration order. */
export const GOOGLE_CAPABILITY = ["calendar", "business"] as const satisfies readonly GoogleCapability[];
