// This file was generated by tapir. Do not edit this file manually.

/**
 * How a query buckets days.
 */
export type Granularity = "day" | "week" | "month";

/** Every `Granularity`, in declaration order. */
export const GRANULARITY = ["day", "week", "month"] as const satisfies readonly Granularity[];
