// This file was generated by tapir. Do not edit this file manually.
import type { Call } from "./Call";
import type { CallPhase } from "./CallPhase";
import type { Channel } from "./Channel";
import type { Comment } from "./Comment";
import type { Conversation } from "./Conversation";
import type { Mention } from "./Mention";
import type { Message } from "./Message";
import type { Post } from "./Post";
import type { PresenceState } from "./PresenceState";
import type { ReactionAction } from "./ReactionAction";
import type { Review } from "../google/Review";
import type { SocialAccount } from "./SocialAccount";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * Every event the hub emits, in the exact shape delivered to its outbound
 * transports: the group webhook (as the POST body) and the WebSocket stream
 * (as one frame). The `event` tag names the kind. Transient kinds
 * (`is_transient`) reach the socket only — they never enter the replay ring
 * the webhook batcher reads.
 */
export type HubEvent = {
  "event": "message_received",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message: Message,
} | {
  "event": "message_sent",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message: Message,
} | {
  "event": "message_queued",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message: Message,
} | {
  "event": "message_canceled",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message_uid: Uid,
  cascaded: boolean,
} | {
  "event": "message_reaction",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message_uid: Uid,
  reactor_id: string,
  action: ReactionAction,
  reaction: string | null,
  emoji: string | null,
} | {
  "event": "message_delivered",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  watermark: number,
  message_uid: Uid | null,
} | {
  "event": "message_read",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  watermark: number,
  message_uid: Uid | null,
} | {
  "event": "message_failed",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message_uid: Uid,
  error: string,
} | {
  "event": "message_updated",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message: Message,
} | {
  "event": "message_deleted",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  message_uid: Uid,
} | {
  "event": "participant_presence",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  state: PresenceState,
} | {
  "event": "comment_received",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  comment: Comment,
} | {
  "event": "comment_updated",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  comment: Comment,
} | {
  "event": "comment_deleted",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  comment_uid: Uid,
  external_id: string,
} | {
  "event": "mention_received",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  mention: Mention,
} | {
  "event": "post_published",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  post: Post,
} | {
  "event": "post_failed",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  post: Post,
} | {
  "event": "conversation_updated",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation: Conversation,
  typing: boolean,
} | {
  "event": "conversation_cleared",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
} | {
  "event": "conversation_removed",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
} | {
  "event": "contact_presence",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  online: boolean,
  last_seen_at: Timestamp | null,
} | {
  "event": "call_ringing",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  call: Call,
} | {
  "event": "call_updated",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  phase: CallPhase,
  call: Call,
} | {
  "event": "call_ended",
  group_uid: Uid,
  channel: Channel,
  social_account_uid: Uid,
  conversation_uid: Uid,
  call: Call,
} | {
  "event": "account_updated",
  group_uid: Uid,
  account: SocialAccount,
} | {
  "event": "account_removed",
  group_uid: Uid,
  social_account_uid: Uid,
} | {
  "event": "review_received",
  group_uid: Uid,
  social_account_uid: Uid,
  location_name: string,
  location_title: string,
  review: Review,
};
