// This file was generated by tapir. Do not edit this file manually.
import type { InstagramAltPostMetric } from "./InstagramAltPostMetric";
import type { Timestamp } from "../primitives/Timestamp";

/**
 * One aggregated period of one metric across the queried subjects.
 */
export type InstagramAltPostBucket = {
  period_start: Timestamp,
  metric: InstagramAltPostMetric,
  value: number,
  /**
   * How many subjects — accounts, or posts — contributed rows to the period.
   */
  subjects: number,
};
