// This file was generated by tapir. Do not edit this file manually.

/**
 * Instagram account metrics, Meta's own names.
 */
export type InstagramAccountMetric = "reach" | "follower_count" | "profile_views";

/** Every `InstagramAccountMetric`, in declaration order. */
export const INSTAGRAM_ACCOUNT_METRIC = ["reach", "follower_count", "profile_views"] as const satisfies readonly InstagramAccountMetric[];
