// This file was generated by tapir. Do not edit this file manually.
import type { InstagramMediaKind } from "./InstagramMediaKind";

export type InstagramSocialPost = {
  media_kind: InstagramMediaKind | null,
};
