// This file was generated by tapir. Do not edit this file manually.

/**
 * Instagram media metrics as the alternate gateway reports them.
 */
export type InstagramAltPostMetric = "impressions" | "reach" | "likes" | "comments" | "shares" | "saves" | "clicks" | "views" | "follows" | "reposts" | "reels_avg_watch_time_ms" | "reels_video_view_total_time_ms" | "reels_skip_rate" | "engagement_rate";

/** Every `InstagramAltPostMetric`, in declaration order. */
export const INSTAGRAM_ALT_POST_METRIC = ["impressions", "reach", "likes", "comments", "shares", "saves", "clicks", "views", "follows", "reposts", "reels_avg_watch_time_ms", "reels_video_view_total_time_ms", "reels_skip_rate", "engagement_rate"] as const satisfies readonly InstagramAltPostMetric[];
