// This file was generated by tapir. Do not edit this file manually.
import type { InstagramCarouselItem } from "./InstagramCarouselItem";
import type { InstagramUserTag } from "../meta/InstagramUserTag";
import type { MediaRef } from "./MediaRef";

export type InstagramMedia = {
  "kind": "image",
  image: MediaRef,
  user_tags: Array<InstagramUserTag>,
  alt_text: string | null,
} | {
  "kind": "carousel",
  items: Array<InstagramCarouselItem>,
} | {
  "kind": "reel",
  video: MediaRef,
  /**
   * Also show the reel in the profile feed grid (defaults to Meta's own
   * default when omitted).
   */
  share_to_feed: boolean | null,
  /**
   * A custom cover image.
   */
  cover: MediaRef | null,
} | {
  "kind": "story",
  image: MediaRef | null,
  video: MediaRef | null,
};
