// This file was generated by tapir. Do not edit this file manually.

/**
 * Which dialog opens an Instagram grant on the alternate channel.
 */
export type InstagramLogin = "instagram_login" | "facebook_login";

/** Every `InstagramLogin`, in declaration order. */
export const INSTAGRAM_LOGIN = ["instagram_login", "facebook_login"] as const satisfies readonly InstagramLogin[];
