// This file was generated by tapir. Do not edit this file manually.
import type { InsightPoint } from "./InsightPoint";
import type { InstagramAltAccountMetric } from "./InstagramAltAccountMetric";

/**
 * One metric as a day-by-day series.
 */
export type InstagramAltAccountSeries = {
  metric: InstagramAltAccountMetric,
  points: Array<InsightPoint>,
};
