// This file was generated by tapir. Do not edit this file manually.

/**
 * The kinds an Instagram media can be, as the hub published it.
 */
export type InstagramMediaKind = "image" | "carousel" | "reel" | "story";

/** Every `InstagramMediaKind`, in declaration order. */
export const INSTAGRAM_MEDIA_KIND = ["image", "carousel", "reel", "story"] as const satisfies readonly InstagramMediaKind[];
