// This file was generated by tapir. Do not edit this file manually.
import type { GatewayMediaType } from "./GatewayMediaType";

export type InstagramAltSocialPost = {
  media_type: GatewayMediaType | null,
};
