// This file was generated by tapir. Do not edit this file manually.
import type { InsightPoint } from "./InsightPoint";
import type { InstagramPostMetric } from "./InstagramPostMetric";

/**
 * One metric as a day-by-day series.
 */
export type InstagramPostSeries = {
  metric: InstagramPostMetric,
  points: Array<InsightPoint>,
};
