// This file was generated by tapir. Do not edit this file manually.
import type { InsightPoint } from "./InsightPoint";
import type { InstagramAccountMetric } from "./InstagramAccountMetric";

/**
 * One metric as a day-by-day series.
 */
export type InstagramAccountSeries = {
  metric: InstagramAccountMetric,
  points: Array<InsightPoint>,
};
