// This file was generated by tapir. Do not edit this file manually.
import type { InstagramUserTag } from "../meta/InstagramUserTag";
import type { MediaRef } from "./MediaRef";

/**
 * One carousel item: exactly one of `image` / `video`.
 */
export type InstagramCarouselItem = {
  image: MediaRef | null,
  video: MediaRef | null,
  user_tags: Array<InstagramUserTag>,
};
