// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type IssueScreenshot = {
  uid: Uid,
  filename: string,
  content_type: string,
  size: number,
};
