// This file was generated by tapir. Do not edit this file manually.
import type { IssueCategory } from "./IssueCategory";
import type { IssueDetails } from "./IssueDetails";
import type { IssueScreenshots } from "./IssueScreenshots";
import type { IssueSeverity } from "./IssueSeverity";
import type { IssueStatus } from "./IssueStatus";
import type { Text0_8000 } from "../primitives/Text0_8000";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Issue = {
  id: number,
  uid: Uid,
  category: IssueCategory,
  severity: IssueSeverity,
  status: IssueStatus,
  description: Text0_8000,
  details: IssueDetails,
  screenshots: IssueScreenshots,
  reported_by: Uid,
  created_at: Timestamp,
  updated_at: Timestamp,
};
