// This file was generated by tapir. Do not edit this file manually.
import type { Text0_2048 } from "../primitives/Text0_2048";
import type { Text0_255 } from "../primitives/Text0_255";
import type { Text0_8000 } from "../primitives/Text0_8000";

/**
 * Per-category detail payload. The shape is strict (the variant is keyed on
 * `category` and known fields are typed), but submission is lenient: every
 * field is optional and the `extra` object holds any additional keys the
 * reporter wants to attach — "as much detail as he wants".
 */
export type IssueDetails = {
  "category": "bug",
  page_url: Text0_2048 | null,
  steps_to_reproduce: Text0_8000 | null,
  expected: Text0_8000 | null,
  actual: Text0_8000 | null,
  extra: Record<string, unknown>,
} | {
  "category": "performance",
  page_url: Text0_2048 | null,
  duration_ms: number | null,
  extra: Record<string, unknown>,
} | {
  "category": "suggestion",
  page_url: Text0_2048 | null,
  extra: Record<string, unknown>,
} | {
  "category": "ui",
  page_url: Text0_2048 | null,
  component: Text0_255 | null,
  extra: Record<string, unknown>,
} | {
  "category": "other",
  extra: Record<string, unknown>,
};
