// This file was generated by tapir. Do not edit this file manually.

export type IssueStatus = "open" | "triaged" | "resolved" | "wont_fix";

/** Every `IssueStatus`, in declaration order. */
export const ISSUE_STATUS = ["open", "triaged", "resolved", "wont_fix"] as const satisfies readonly IssueStatus[];
