// This file was generated by tapir. Do not edit this file manually.
import type { IssueCategory } from "./IssueCategory";
import type { IssueSeverity } from "./IssueSeverity";
import type { IssueStatus } from "./IssueStatus";
import type { Text0_2048 } from "../primitives/Text0_2048";
import type { Text0_8000 } from "../primitives/Text0_8000";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Issue = {
  id: number,
  uid: Uid,
  category: IssueCategory,
  severity: IssueSeverity,
  status: IssueStatus,
  description: Text0_8000,
  /**
   * The page the reporter was on, when they chose to name one.
   */
  url: Text0_2048 | null,
  /**
   * The screenshots attached at report time, as hosted media.
   */
  screenshots: Array<Uid>,
  reported_by: Uid,
  created_at: Timestamp,
  updated_at: Timestamp,
};
