// This file was generated by tapir. Do not edit this file manually.

/**
 * A reaction attached to a message. `reactor_id` is the platform participant
 * id (or the page/account id when the reaction came from the business side).
 */
export type MessageReaction = {
  reactor_id: string,
  /**
   * Meta's reaction name (e.g. `love`).
   */
  reaction: string | null,
  /**
   * The unicode emoji, when Meta provides it.
   */
  emoji: string | null,
};
