// This file was generated by tapir. Do not edit this file manually.

export type MessageDirection = "in" | "out";

/** Every `MessageDirection`, in declaration order. */
export const MESSAGE_DIRECTION = ["in", "out"] as const satisfies readonly MessageDirection[];
