// This file was generated by tapir. Do not edit this file manually.
import type { MessageTag } from "../meta/MessageTag";
import type { MessengerContent } from "./MessengerContent";
import type { QuickReply } from "./QuickReply";

/**
 * Messenger/Instagram DM payload (Send API). Attachments carry no captions;
 * quick replies may attach to any content.
 */
export type MessengerSend = {
  content: MessengerContent,
  /**
   * A message tag that lifts the response window where the channel honors
   * it (`GET /channel`, `response_window.lift`); refused on any other
   * channel.
   */
  tag: MessageTag | null,
  /**
   * Up to 13 quick-reply chips.
   */
  quick_replies: Array<QuickReply> | null,
};
