// This file was generated by tapir. Do not edit this file manually.
import type { MediaRef } from "./MediaRef";
import type { TemplateButton } from "./TemplateButton";
import type { TemplateCard } from "./TemplateCard";

export type MessengerContent = {
  "kind": "text",
  text: string,
} | {
  "kind": "image",
  media: MediaRef,
} | {
  "kind": "audio",
  media: MediaRef,
} | {
  "kind": "video",
  media: MediaRef,
} | {
  "kind": "file",
  media: MediaRef,
} | {
  "kind": "buttons",
  text: string,
  buttons: Array<TemplateButton>,
} | {
  "kind": "cards",
  cards: Array<TemplateCard>,
};
