// This file was generated by tapir. Do not edit this file manually.

/**
 * Which sound a new message plays in the operator's browser, if any. The
 * sounds themselves ship with the frontend; the choice is personal to the
 * operator and follows them across devices.
 */
export type MessageChime = "sound_one" | "sound_two" | "sound_three" | "sound_four" | "off";

/** Every `MessageChime`, in declaration order. */
export const MESSAGE_CHIME = ["sound_one", "sound_two", "sound_three", "sound_four", "off"] as const satisfies readonly MessageChime[];
