// This file was generated by tapir. Do not edit this file manually.

/**
 * A reaction attached to a message. `reactor_id` is the platform participant
 * id (or the page/account id when the reaction came from the business side).
 */
export type MessageReaction = {
  reactor_id: string,
  /**
   * The unicode emoji; a Meta reaction name (e.g. `love`) is stored as its
   * glyph. `None` when the platform sent neither a glyph nor a known name.
   */
  emoji: string | null,
};
