// This file was generated by tapir. Do not edit this file manually.
import type { NativeContent } from "./NativeContent";
import type { Uid } from "../primitives/Uid";

/**
 * Native (whatsmeow) payload: text, media, locations and one contact card —
 * the bridge sends no interactive shapes.
 */
export type NativeSend = {
  content: NativeContent,
  /**
   * Send as a reply to this message (must belong to the same conversation).
   */
  reply_to_uid: Uid | null,
};
