// This file was generated by tapir. Do not edit this file manually.
import type { PostContent } from "./PostContent";
import type { PostStatus } from "./PostStatus";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Post = {
  uid: Uid,
  social_account_uid: Uid,
  content: PostContent,
  status: PostStatus,
  error: string | null,
  /**
   * Hub-side schedule instant for `scheduled` posts.
   */
  scheduled_at: Timestamp | null,
  /**
   * Instagram media container awaiting Meta-side processing.
   */
  container_id: string | null,
  /**
   * Carousel child containers (comma-separated) still processing.
   */
  container_children: string | null,
  external_id: string | null,
  permalink: string | null,
  created_by: Uid | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
