// This file was generated by tapir. Do not edit this file manually.

/**
 * How a native whatsapp account announces itself online. An online presence
 * silences the paired phone's notifications and stamps every delivery
 * receipt as active, so the default follows the people actually looking.
 */
export type PresencePolicy = "follows_operator" | "always_invisible";

/** Every `PresencePolicy`, in declaration order. */
export const PRESENCE_POLICY = ["follows_operator", "always_invisible"] as const satisfies readonly PresencePolicy[];
