// This file was generated by tapir. Do not edit this file manually.

/**
 * Every kind of account the hub connects — the account registry's axis.
 * Distinct from [`Channel`], which is the *messaging-domain* discriminator
 * carried by conversations, messages, and posts: every messaging provider
 * projects onto a channel, while non-messaging providers (calendar) have
 * none — so messaging payloads can never name them.
 *
 * Adding an integration = a variant here + its connect flow + its
 * capability module; the registry (table, CRUD, listing UI) is shared.
 */
export type Provider = "facebook" | "instagram" | "whatsapp" | "whatsapp_stevo" | "whatsapp_native" | "google";

/** Every `Provider`, in declaration order. */
export const PROVIDER = ["facebook", "instagram", "whatsapp", "whatsapp_stevo", "whatsapp_native", "google"] as const satisfies readonly Provider[];
