// This file was generated by tapir. Do not edit this file manually.

export type PulseDiskMetricRow = {
  recorded_at: number,
  name: string,
  available_bytes: number,
  usage_percent: number,
  read_bytes_per_sec: number,
  written_bytes_per_sec: number,
  read_iops: number,
  write_iops: number,
  temp_max_celsius: number | null,
};
