// This file was generated by tapir. Do not edit this file manually.

/**
 * What one bucket stands for: the thing a rule counts against, one counter
 * per distinct value. A rule may draw from several — a login attempt spends
 * from the caller's IP bucket *and* the e-mail's bucket, and is refused when
 * either runs dry.
 */
export type RateLimitBucket = "ip" | "user" | "api_key" | "email" | "user_mfa_token" | "social_account" | "group" | "platform";

/** Every `RateLimitBucket`, in declaration order. */
export const RATE_LIMIT_BUCKET = ["ip", "user", "api_key", "email", "user_mfa_token", "social_account", "group", "platform"] as const satisfies readonly RateLimitBucket[];
