// This file was generated by tapir. Do not edit this file manually.

/**
 * Whether a reaction was added or taken back. Platforms report both through
 * one event; the emoji is present only on a `react`.
 */
export type ReactionAction = "react" | "unreact";

/** Every `ReactionAction`, in declaration order. */
export const REACTION_ACTION = ["react", "unreact"] as const satisfies readonly ReactionAction[];
