// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * One account's share of the queue.
 */
export type RecipientLoad = {
  social_account_uid: Uid,
  /**
   * Queued rows assigned to the account.
   */
  pending: number,
  /**
   * Of those, the numbers it has no conversation with yet — each one is a
   * discovery (a number check and a new thread) before the send.
   */
  new_conversations: number,
};
