// This file was generated by tapir. Do not edit this file manually.

/**
 * How a query folds the days of a bucket: add them (counts that arrive per
 * day) or keep the last (running totals such as followers).
 */
export type Roll = "sum" | "last";

/** Every `Roll`, in declaration order. */
export const ROLL = ["sum", "last"] as const satisfies readonly Roll[];
