// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type ServerUptimeStats = {
  count: number,
  total_uptime_ms: number,
  since: Timestamp,
  until: Timestamp,
};
