// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type ServerUptime = {
  id: number,
  started_at: Timestamp,
  last_heartbeat_at: Timestamp,
};
