// This file was generated by tapir. Do not edit this file manually.

/**
 * Which behaviour earned a temporary ban, as the platform reported it.
 *
 * The single most actionable thing whatsapp says about a ban — it names the
 * pattern to change, so it is typed rather than left inside the free-text
 * detail. Only ever set alongside [`SessionIncidentKind::TemporaryBan`].
 */
export type SessionBanReason = "sent_to_too_many_people" | "blocked_by_users" | "created_too_many_groups" | "sent_too_many_same_message" | "broadcast_list" | "unknown";

/** Every `SessionBanReason`, in declaration order. */
export const SESSION_BAN_REASON = ["sent_to_too_many_people", "blocked_by_users", "created_too_many_groups", "sent_too_many_same_message", "broadcast_list", "unknown"] as const satisfies readonly SessionBanReason[];
