// This file was generated by tapir. Do not edit this file manually.

/**
 * A run of snippet text; `hit` runs are the matched terms.
 */
export type SnippetPart = {
  text: string,
  hit: boolean,
};
