// This file was generated by tapir. Do not edit this file manually.

/**
 * Totals over the platform posts in scope, deleted ones excluded.
 */
export type SocialPostSummary = {
  posts: number,
  /**
   * Comments across them, each post counting the larger of the platform's
   * number and the hub's.
   */
  comments: number,
  /**
   * Root comments of third parties the account has not answered.
   */
  unanswered: number,
};
