// This file was generated by tapir. Do not edit this file manually.
import type { SocialPostDetail } from "./SocialPostDetail";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * A post as it stands on its platform, published through the hub or not.
 * `unanswered_count` is the number of visible third-party root comments with
 * no public reply from the account; `last_comment_at` the newest comment.
 */
export type SocialPost = {
  uid: Uid,
  social_account_uid: Uid,
  /**
   * The platform's post / media id.
   */
  external_id: string,
  /**
   * The hub post it came from, when it was published through the hub.
   */
  post_uid: Uid | null,
  caption: string | null,
  /**
   * The hosted thumbnail (`media.serve`).
   */
  picture_uid: Uid | null,
  picture_source: string | null,
  permalink: string | null,
  published_at: Timestamp | null,
  /**
   * The platform's own count or the comments the hub holds, whichever is
   * larger: the platform's count lags behind a comment the webhook delivered.
   */
  comment_count: number,
  like_count: number,
  detail: SocialPostDetail,
  /**
   * When the gateway last described the post. `None` marks a post the hub
   * knows only through its comments: the listings never reached it.
   */
  synced_at: Timestamp | null,
  /**
   * When the whole comment thread of such a post was read by post id.
   */
  thread_imported_at: Timestamp | null,
  insight_refreshed_at: Timestamp | null,
  insight_next_at: Timestamp | null,
  /**
   * When the gateway found the post gone from the platform; a deleted post
   * leaves the list and its metrics stop being read.
   */
  deleted_at: Timestamp | null,
  created_at: Timestamp,
  updated_at: Timestamp,
  unanswered_count: number,
  last_comment_at: Timestamp | null,
};
