// This file was generated by tapir. Do not edit this file manually.
import type { FacebookAltSocialPost } from "./FacebookAltSocialPost";
import type { FacebookSocialPost } from "./FacebookSocialPost";
import type { InstagramAltSocialPost } from "./InstagramAltSocialPost";
import type { InstagramSocialPost } from "./InstagramSocialPost";

/**
 * What a channel knows about a post on its platform beyond the columns every
 * channel shares. Channel-tagged like `PostContent`: each variant is owned by
 * its channel and evolves alone.
 */
export type SocialPostDetail = {
  "channel": "facebook"
} & FacebookSocialPost | {
  "channel": "instagram"
} & InstagramSocialPost | {
  "channel": "facebook_alt"
} & FacebookAltSocialPost | {
  "channel": "instagram_alt"
} & InstagramAltSocialPost;
