// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { PresencePolicy } from "./PresencePolicy";
import type { Provider } from "./Provider";
import type { SessionBanReason } from "./SessionBanReason";
import type { SessionIncidentKind } from "./SessionIncidentKind";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type SocialAccount = {
  uid: Uid,
  group_uid: Uid,
  /**
   * The account's kind — the registry's axis. Messaging providers project
   * onto a [`Channel`] via [`Self::channel`]; non-messaging ones (calendar)
   * onto none.
   */
  provider: Provider,
  /**
   * Platform identity webhooks address: page id (facebook), ig user id
   * (instagram), or the provider's stable subject. Unique together with
   * `provider`.
   */
  external_id: string,
  /**
   * The number behind a session-backed whatsapp account, once known: native
   * pairing states it, stevo hides it behind the api key until the gateway
   * echoes one of the account's own messages. `None` until then.
   */
  phone: string | null,
  /**
   * Backing Facebook Page — the send/publish path for both channels.
   */
  page_id: string,
  /**
   * What the platform calls this account, refreshed from the platform. Never
   * operator-supplied — that is [`Self::alias`].
   */
  name: string,
  /**
   * An operator's own label for the account, when they set one. Independent
   * of [`Self::name`]: renaming the account on the platform does not disturb
   * it, and clearing it falls back to the platform name.
   */
  alias: Name | null,
  /**
   * The account's own picture, as the platform serves it.
   */
  avatar_url: string | null,
  /**
   * When [`Self::name`] and [`Self::avatar_url`] were last read from the
   * platform. `None` means never — which the refresh sweep treats as due now.
   */
  profile_refreshed_at: Timestamp | null,
  username: string | null,
  /**
   * OAuth-refresh providers only: scopes actually granted on the last connect.
   */
  scope: string | null,
  /**
   * The stored grant died (revoked or expired) — the account must be
   * reconnected; cleared by a reconnect. Set for the OAuth-refresh providers
   * when a refresh is rejected, and for the page-grant providers when the
   * connect review probes a token and finds it dead.
   */
  needs_reauth: boolean,
  enabled: boolean,
  /**
   * How the account announces itself online; only the native whatsapp
   * channel acts on it.
   */
  presence_policy: PresencePolicy,
  /**
   * Why this account's session last stopped working, for the session-backed
   * whatsapp channels. Survives restarts and outlives the live connection
   * state, which only ever reports the socket as it is right now — an
   * operator needs to know the account was banned an hour ago, not just that
   * it is currently down. Cleared on a successful (re)connect.
   */
  session_incident: SessionIncidentKind | null,
  /**
   * When [`Self::session_incident`] happened.
   */
  session_incident_at: Timestamp | null,
  /**
   * The platform's technical detail behind the incident — for operators and
   * logs, never a user-facing message.
   */
  session_incident_detail: string | null,
  /**
   * When a temporary ban lifts, as the platform reported it; `None` for every
   * other incident.
   */
  session_incident_expires_at: Timestamp | null,
  /**
   * Which behaviour earned a temporary ban; `None` for every other incident.
   */
  session_incident_ban_reason: SessionBanReason | null,
  /**
   * Most conversations the hub may open on this account in any 24 hours,
   * whoever asks for them (inbox, api key, campaign, import, GoHighLevel);
   * `None` leaves it unlimited. Only the session-backed whatsapp channels
   * enforce it.
   */
  daily_conversation_cap: Number1_100000 | null,
  connected_by: Uid,
  created_at: Timestamp,
  updated_at: Timestamp,
};
