// This file was generated by tapir. Do not edit this file manually.
import type { ContactCard } from "./ContactCard";
import type { QuickReply } from "./QuickReply";
import type { TemplateButton } from "./TemplateButton";

export type StevoContent = {
  "kind": "text",
  text: string,
} | {
  "kind": "quick_replies",
  text: string,
  quick_replies: Array<QuickReply>,
} | {
  "kind": "image",
  url: string,
  caption: string | null,
} | {
  "kind": "audio",
  url: string,
} | {
  "kind": "video",
  url: string,
  caption: string | null,
} | {
  "kind": "file",
  url: string,
  caption: string | null,
  filename: string | null,
} | {
  "kind": "location",
  latitude: number,
  longitude: number,
  name: string | null,
  address: string | null,
} | {
  "kind": "contact",
  contact: ContactCard,
} | {
  "kind": "buttons",
  text: string,
  buttons: Array<TemplateButton>,
};
