// This file was generated by tapir. Do not edit this file manually.
import type { MediaRef } from "./MediaRef";
import type { TemplateButton } from "./TemplateButton";

/**
 * One card of a generic template carousel.
 */
export type TemplateCard = {
  title: string,
  subtitle: string | null,
  image: MediaRef | null,
  buttons: Array<TemplateButton>,
};
