// This file was generated by tapir. Do not edit this file manually.

/**
 * How the hub reaches a channel's platform.
 */
export type Transport = "meta" | "gateway" | "native";

/** Every `Transport`, in declaration order. */
export const TRANSPORT = ["meta", "gateway", "native"] as const satisfies readonly Transport[];
