// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipRole } from "./MembershipRole";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";
import type { UserInviteEmailStatus } from "./UserInviteEmailStatus";

/**
 * `group_uid` and `role` are a tied pair the DB CHECK enforces: both set means
 * accepting joins that group with that role, both NULL means a platform invite
 * that lands the new user in no group at all.
 */
export type UserInvite = {
  uid: Uid,
  email: Email,
  invited_by: Uid,
  group_uid: Uid | null,
  role: MembershipRole | null,
  expires_at: Timestamp,
  accepted_at: Timestamp | null,
  email_status: UserInviteEmailStatus,
  created_at: Timestamp,
};
