// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type User = {
  uid: Uid,
  email: Email,
  name: Name,
  enabled: boolean,
  super_admin: boolean,
  last_seen: Timestamp | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
