// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "./Channel";
import type { EventKind } from "./EventKind";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type Webhook = {
  uid: Uid,
  group_uid: Uid,
  url: string,
  /**
   * Event kinds delivered to this subscription; `None` = everything.
   */
  events: Array<EventKind> | null,
  /**
   * Channels delivered to this subscription; `None` = everything.
   */
  channels: Array<Channel> | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
