// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";
import type { WhatsappContent } from "./WhatsappContent";

/**
 * Official WhatsApp payload (Cloud API). Free-form content requires an
 * inbound message within 24h; `template` is the only window-independent
 * content and the only conversation opener.
 */
export type WhatsappSend = {
  content: WhatsappContent,
  /**
   * Send as a reply to this message (must belong to the same conversation).
   */
  reply_to_uid: Uid | null,
};
