// This file was generated by tapir. Do not edit this file manually.
import type { MessageTag } from "../meta/MessageTag";

/**
 * What a send may carry to pass a closed [`ResponseWindow`].
 */
export type WindowLift = {
  "kind": "none"
} | {
  "kind": "template"
} | {
  "kind": "tag",
  tag: MessageTag,
  hours: number,
};
