// This file was generated by tapir. Do not edit this file manually.
import type { MembershipRole } from "../domain/MembershipRole";
import type { Uid } from "../primitives/Uid";

export type AddGroupMemberRequest = {
  /**
   * An existing user; onboarding a new address goes through an invite.
   */
  user_uid: Uid,
  role: MembershipRole,
};
