// This file was generated by tapir. Do not edit this file manually.
import type { Email } from "../primitives/Email";
import type { MembershipRole } from "../types/MembershipRole";
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One membership, carrying the identity fields needed to recognize the person
 * behind it — never the user record itself, which answers to `ViewUsers` and
 * is platform staff's alone.
 */
export type GroupMemberResponse = {
  user_uid: Uid,
  email: Email,
  name: Name,
  enabled: boolean,
  last_seen: Timestamp | null,
  role: MembershipRole,
  member_since: Timestamp,
};
