// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type GroupResponse = {
  /**
   * Present only with `with_counts`, and only for a caller holding
   * `ViewApiKeys` in this group; `null` says the count is out of reach, never
   * that the group has no keys.
   */
  api_key_count: number | null,
  /**
   * Present only with `with_counts`, and only for a caller holding
   * `ViewMembers` in this group; `null` says the count is out of reach, never
   * that the group has no members.
   */
  member_count: number | null,
  /**
   * Present only with `with_counts`, and only for a caller holding
   * `ViewSocialAccounts` in this group; `null` says the count is out of
   * reach, never that the group has no accounts.
   */
  social_account_count: number | null,
  uid: Uid,
  name: Name,
  enabled: boolean,
  logo_content_type: string | null,
  created_at: Timestamp,
  updated_at: Timestamp,
};
