// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type SetGroupLogoResponse = {
  /**
   * The stored logo, now `Group.logo_uid`.
   */
  logo_uid: Uid,
};
