// This file was generated by tapir. Do not edit this file manually.
import type { MembershipRole } from "../domain/MembershipRole";

export type SetGroupMemberRoleRequest = {
  role: MembershipRole,
};
