// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { EmailQueueItem } from "../../types/domain/EmailQueueItem";
import type { EmailQueueListQuery } from "../../types/mailing/EmailQueueListQuery";

export const mailQueue = {
  /**
   * List queued emails, optionally filtered by delivery status.
   *
   * Requires `ManageEmailQueue`, which only platform staff hold.
   */
  list: Tapi.get<{ query: EmailQueueListQuery; response: Array<EmailQueueItem> }>()({
    endpoint: "/mail-queue",
  }),
  /**
   * Remove a queued email from the delivery queue. An email that carried a
   * subscriber and had not been sent flips that record's email status to
   * failed. An email already handed to the mail server is refused — it settles
   * on its own.
   *
   * Requires `ManageEmailQueue`, which only platform staff hold.
   */
  remove: Tapi.delete<{ path: { id: number }; response: null }>()({
    endpoint: "/mail-queue/:id",
  }),
  /**
   * Reset a failed queued email so the worker attempts delivery again. A
   * subscriber record goes back to pending-send.
   *
   * Requires `ManageEmailQueue`, which only platform staff hold.
   */
  retry: Tapi.post<{ path: { id: number }; response: null }>()({
    endpoint: "/mail-queue/:id/retry",
  }),
};
