// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { ActionRateLimitRule } from "../../../types/database/ActionRateLimitRule";
import type { CreateActionRateLimitRequest } from "../../../types/rate_limit/CreateActionRateLimitRequest";
import type { CreateActionRateLimitResponse } from "../../../types/rate_limit/CreateActionRateLimitResponse";
import type { Uid } from "../../../types/primitives/Uid";
import type { UpdateActionRateLimitRequest } from "../../../types/rate_limit/UpdateActionRateLimitRequest";

export const action = {
  /**
   * Create a platform-wide action rate-limit rule for a given limited action.
   *
   * Requires `CreateRateLimits`, which only platform staff hold.
   */
  create: Tapi.post<{ body: CreateActionRateLimitRequest; response: CreateActionRateLimitResponse }>()({
    endpoint: "/rate-limit/action",
  }),
  /**
   * Delete an action rate-limit rule by uid.
   *
   * Requires `DeleteRateLimits`, which only platform staff hold.
   */
  delete: Tapi.delete<{ path: { rule_uid: Uid }; response: null }>()({
    endpoint: "/rate-limit/action/:rule_uid",
  }),
  /**
   * Fetch a single action rate-limit rule by uid.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { rule_uid: Uid }; response: ActionRateLimitRule }>()({
    endpoint: "/rate-limit/action/:rule_uid",
  }),
  /**
   * List all action rate-limit rules.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<ActionRateLimitRule> }>()({
    endpoint: "/rate-limit/action",
  }),
  /**
   * Update the limits of an existing action rate-limit rule.
   *
   * Requires `UpdateRateLimits`, which only platform staff hold.
   */
  update: Tapi.put<{ path: { rule_uid: Uid }; body: UpdateActionRateLimitRequest; response: null }>()({
    endpoint: "/rate-limit/action/:rule_uid",
  }),
};
