// This file was generated by tapir. Do not edit this file manually.
import type { AudienceOrder } from "../types/AudienceOrder";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Uid } from "../primitives/Uid";

/**
 * An audience to resolve — what `build` freezes as the ledger and what
 * `add` appends to it.
 */
export type AudienceRequest = {
  /**
   * Shuffle the resolved order once — the default, because a strict file
   * order reads machine-like. An append shuffles only the appended batch.
   */
  shuffle: boolean | null,
} & ({
  "source": "accounts",
  order: AudienceOrder | null,
  limit: Number1_100000 | null,
} | {
  "source": "contact_import",
  import_uid: Uid,
} | {
  "source": "conversations",
  conversation_uids: Array<Uid>,
});
