// This file was generated by tapir. Do not edit this file manually.
import type { Campaign } from "../domain/Campaign";
import type { CampaignCounts } from "./CampaignCounts";
import type { RecipientLoad } from "../domain/RecipientLoad";
import type { Uid } from "../primitives/Uid";

/**
 * One campaign with what its list row and page header render.
 */
export type CampaignDetail = {
  campaign: Campaign,
  social_account_uids: Array<Uid>,
  template_count: number,
  counts: CampaignCounts,
  /**
   * Each account's share of the queue, and how much of it is numbers the
   * account has never spoken to (a new conversation each).
   */
  loads: Array<RecipientLoad>,
};
