// This file was generated by tapir. Do not edit this file manually.

/**
 * Recipient counts by status — always derived from the ledger.
 */
export type CampaignCounts = {
  total: number,
  pending: number,
  sent: number,
  failed: number,
  skipped: number,
  canceled: number,
};
