// This file was generated by tapir. Do not edit this file manually.
import type { CampaignRecipientStatus } from "../domain/CampaignRecipientStatus";
import type { MessageStatus } from "../domain/MessageStatus";

/**
 * One recipient-status × message-status cell of the stats join.
 */
export type CampaignStatRow = {
  recipient_status: CampaignRecipientStatus,
  /**
   * The pointed message's own status; `null` for never-dispatched rows.
   */
  message_status: MessageStatus | null,
  count: number,
};
