// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { OutboundContent } from "../types/OutboundContent";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * A template as the API shows it: the stored JSON decoded into its parts.
 */
export type CampaignTemplateResponse = {
  uid: Uid,
  campaign_uid: Uid,
  /**
   * The linear rotation order.
   */
  position: number,
  label: Name | null,
  parts: Array<OutboundContent>,
  created_at: Timestamp,
};
