// This file was generated by tapir. Do not edit this file manually.
import type { CampaignStatRow } from "./CampaignStatRow";

export type CampaignStats = {
  rows: Array<CampaignStatRow>,
  /**
   * Conversations that answered after their campaign send.
   */
  replies: number,
};
