// This file was generated by tapir. Do not edit this file manually.
import type { CampaignRecipientStatus } from "../domain/CampaignRecipientStatus";
import type { Number1_500 } from "../primitives/Number1_500";

export type ListRecipientsQuery = {
  status: CampaignRecipientStatus | null,
  /**
   * Keyset cursor: only rows with `id` strictly greater are returned.
   */
  after_id: number | null,
  limit: Number1_500 | null,
};
