// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * Why a start would refuse, as codes the frontend labels.
 */
export type PreflightError = {
  "kind": "no_templates"
} | {
  "kind": "no_accounts"
} | {
  "kind": "no_recipients"
} | {
  "kind": "unassigned"
} | {
  "kind": "ended"
} | {
  "kind": "account_disabled",
  social_account_uid: Uid,
} | {
  "kind": "account_session_down",
  social_account_uid: Uid,
} | {
  "kind": "template_invalid",
  template_uid: Uid,
};
