// This file was generated by tapir. Do not edit this file manually.

/**
 * Queued recipients to drop. Rows that already ran (sent, failed, skipped,
 * canceled) are history and stay.
 */
export type RemoveRecipientsRequest = {
  recipient_ids: Array<number>,
};
