// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";
import type { OutboundContent } from "../types/OutboundContent";

/**
 * A spoke for the template wheel: the sequence of messages one recipient
 * receives as a unit. Every part is the channel-agnostic sendable payload
 * (a text, an image…) — which whatsapp flavor carries it is decided per
 * recipient by the account it was assigned to, so every part must be one
 * every campaign channel can send. `{{nome}}` and `{{telefone}}` substitute
 * per recipient, and `{a|b|c}` spintax varies the wording per send.
 */
export type TemplateRequest = {
  label: Name | null,
  /**
   * The sequence, in send order: 1–10 parts of text, image/video/file
   * (caption optional) or audio.
   */
  parts: Array<OutboundContent>,
};
