// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type TestSendRequest = {
  template_uid: Uid,
  /**
   * A conversation of the campaign's group, on a whatsapp account, to
   * receive the rendered template, now, outside any schedule.
   */
  conversation_uid: Uid,
};
