// This file was generated by tapir. Do not edit this file manually.
import type { Date } from "./Date";
import type { HourlyCallMetrics } from "./HourlyCallMetrics";
import type { WeekdayCallMetrics } from "./WeekdayCallMetrics";

export type AggregateCallMetrics = {
  missedCallsCount: number,
  answeredCallsCount: number,
  hourlyMetrics?: Array<HourlyCallMetrics>,
  weekdayMetrics?: Array<WeekdayCallMetrics>,
  startDate: Date | null,
  endDate: Date | null,
};
