// This file was generated by tapir. Do not edit this file manually.
import type { QandaAuthor } from "./QandaAuthor";

export type Answer = {
  /**
   * Resource name, `locations/{l}/questions/{q}/answers/{a}`.
   */
  name: string | null,
  text: string | null,
  author: QandaAuthor | null,
  upvoteCount?: number | null,
  createTime: string | null,
  updateTime: string | null,
};
