// This file was generated by tapir. Do not edit this file manually.

/**
 * A Business Profile account (`accounts/{id}`) — personal, location group or
 * organization. The account is the v4 path root for reviews/posts/media.
 */
export type BusinessAccount = {
  /**
   * Resource name, `accounts/{account_id}`.
   */
  name: string,
  accountName: string | null,
  type: string | null,
  role: string | null,
  verificationState: string | null,
};
