// This file was generated by tapir. Do not edit this file manually.
import type { AggregateCallMetrics } from "./AggregateCallMetrics";

/**
 * Call History insights for a location — only populated where the merchant
 * enabled Call History on the profile.
 */
export type BusinessCallsInsights = {
  name: string | null,
  metricType: string | null,
  aggregateMetrics: AggregateCallMetrics | null,
};
