// This file was generated by tapir. Do not edit this file manually.

export type CalendarListEntry = {
  id: string,
  summary: string | null,
  primary: boolean | null,
  accessRole: string | null,
  timeZone: string | null,
};
