// This file was generated by tapir. Do not edit this file manually.

/**
 * Post button: `action_type` is `BOOK`, `ORDER`, `SHOP`, `LEARN_MORE`,
 * `SIGN_UP` or `CALL` (the latter needs no url).
 */
export type CallToAction = {
  actionType: string | null,
  url: string | null,
};
