// This file was generated by tapir. Do not edit this file manually.
import type { BusinessCallsInsights } from "./BusinessCallsInsights";

export type CallInsightsPage = {
  businessCallsInsights: Array<BusinessCallsInsights>,
  nextPageToken?: string | null,
};
