// This file was generated by tapir. Do not edit this file manually.

/**
 * A business category. `name` is the stable id (`categories/gcid:…`) and is
 * what a PATCH must send; `display_name` is localized.
 */
export type Category = {
  name: string | null,
  displayName: string | null,
};
