// This file was generated by tapir. Do not edit this file manually.
import type { Category } from "./Category";

export type Categories = {
  primaryCategory: Category | null,
  additionalCategories?: Array<Category>,
};
