// This file was generated by tapir. Do not edit this file manually.
import type { DatedValue } from "./DatedValue";

/**
 * One metric's day-by-day series, flattened from Google's nested envelope.
 */
export type DailyMetricSeries = {
  dailyMetric: string,
  datedValues: Array<DatedValue>,
};
