// This file was generated by tapir. Do not edit this file manually.
import type { Date } from "./Date";

/**
 * One day's value; int64 arrives as a string, absent means no data.
 */
export type DatedValue = {
  date: Date | null,
  value: string | null,
};
