// This file was generated by tapir. Do not edit this file manually.

/**
 * Calendar date (proto3 `google.type.Date`): zero-valued components are
 * omitted from the JSON, hence the defaults.
 */
export type Date = {
  year: number,
  month: number,
  day: number,
};
