// This file was generated by tapir. Do not edit this file manually.
import type { EventAttendee } from "./EventAttendee";
import type { EventDateTime } from "./EventDateTime";
import type { ExtendedProperties } from "./ExtendedProperties";

/**
 * A Google Calendar event (response shape). Most fields are optional because
 * Google omits them depending on event kind and the caller's access.
 */
export type Event = {
  id: string | null,
  status: string | null,
  summary: string | null,
  description: string | null,
  location: string | null,
  htmlLink: string | null,
  hangoutLink: string | null,
  start: EventDateTime | null,
  end: EventDateTime | null,
  attendees: Array<EventAttendee> | null,
  extendedProperties: ExtendedProperties | null,
};
