// This file was generated by tapir. Do not edit this file manually.
import type { Event } from "./Event";

/**
 * One page of events. `next_page_token` present means there is more —
 * pass it back to continue.
 */
export type EventPage = {
  items: Array<Event>,
  nextPageToken?: string | null,
};
