// This file was generated by tapir. Do not edit this file manually.

/**
 * A calendar event's start/end. Google uses `dateTime` (RFC3339) for timed
 * events and `date` (YYYY-MM-DD) for all-day events; `timeZone` is an IANA name.
 */
export type EventDateTime = {
  dateTime: string | null,
  date: string | null,
  timeZone: string | null,
};
