// This file was generated by tapir. Do not edit this file manually.

/**
 * App-private key/value labels carried on an event. `private` is visible only
 * to the connected account's grant, so it is where a caller stamps its own
 * identifier for whoever booked the event — that label can then be filtered
 * server-side, making Google the source of truth instead of a local mirror.
 */
export type ExtendedProperties = {
  private?: {
    [key in string]: string
  },
  shared?: {
    [key in string]: string
  },
};
