// This file was generated by tapir. Do not edit this file manually.
import type { Menu } from "./Menu";

/**
 * The location's structured menus — the category-specific dataset food
 * businesses get; `metadata.can_have_food_menus` says whether it applies.
 */
export type FoodMenus = {
  /**
   * Resource name, `accounts/{a}/locations/{l}/foodMenus`.
   */
  name: string | null,
  menus?: Array<Menu>,
};
