// This file was generated by tapir. Do not edit this file manually.

/**
 * A search term that surfaced the profile. Low-volume terms report only a
 * `threshold` floor instead of an exact `value` (both stringified int64).
 */
export type InsightsValue = {
  value: string | null,
  threshold: string | null,
};
