// This file was generated by tapir. Do not edit this file manually.
import type { BusinessHours } from "./BusinessHours";
import type { BusinessProfile } from "./BusinessProfile";
import type { Categories } from "./Categories";
import type { LatLng } from "./LatLng";
import type { LocationMetadata } from "./LocationMetadata";
import type { OpenInfo } from "./OpenInfo";
import type { PhoneNumbers } from "./PhoneNumbers";
import type { PostalAddress } from "./PostalAddress";
import type { SpecialHours } from "./SpecialHours";

/**
 * A business location, thinned to the fields the read mask requests.
 */
export type Location = {
  /**
   * Resource name, `locations/{location_id}` — no account prefix on v1.
   */
  name: string | null,
  title: string | null,
  phoneNumbers: PhoneNumbers | null,
  storefrontAddress: PostalAddress | null,
  websiteUri: string | null,
  regularHours: BusinessHours | null,
  specialHours: SpecialHours | null,
  categories: Categories | null,
  openInfo: OpenInfo | null,
  profile: BusinessProfile | null,
  latlng: LatLng | null,
  metadata: LocationMetadata | null,
};
