// This file was generated by tapir. Do not edit this file manually.
import type { TimeInterval } from "./TimeInterval";

/**
 * Event window for `EVENT`/`OFFER` posts.
 */
export type LocalPostEvent = {
  title: string | null,
  schedule: TimeInterval | null,
};
