// This file was generated by tapir. Do not edit this file manually.
import type { Location } from "./Location";

export type LocationPage = {
  locations: Array<Location>,
  nextPageToken?: string | null,
};
