// This file was generated by tapir. Do not edit this file manually.

/**
 * Where a media item shows on the profile: `category` is `COVER`, `PROFILE`,
 * `LOGO`, `EXTERIOR`, `INTERIOR`, `PRODUCT`, `AT_WORK`, `FOOD_AND_DRINK`,
 * `MENU`, `COMMON_AREA`, `ROOMS`, `TEAMS` or `ADDITIONAL`.
 */
export type LocationAssociation = {
  category: string | null,
};
