// This file was generated by tapir. Do not edit this file manually.
import type { LocationAssociation } from "./LocationAssociation";
import type { MediaDimensions } from "./MediaDimensions";
import type { MediaInsights } from "./MediaInsights";

/**
 * A photo/video on the profile. On create, send `media_format: PHOTO` (or
 * `VIDEO`), `location_association` and a publicly fetchable `source_url`.
 */
export type MediaItem = {
  /**
   * Resource name, `accounts/{a}/locations/{l}/media/{m}`.
   */
  name: string | null,
  mediaFormat: string | null,
  locationAssociation: LocationAssociation | null,
  sourceUrl: string | null,
  googleUrl: string | null,
  thumbnailUrl: string | null,
  description: string | null,
  dimensions: MediaDimensions | null,
  insights: MediaInsights | null,
  createTime: string | null,
};
