// This file was generated by tapir. Do not edit this file manually.
import type { MediaItem } from "./MediaItem";

export type MediaPage = {
  mediaItems: Array<MediaItem>,
  totalMediaItemCount?: number | null,
  nextPageToken?: string | null,
};
