// This file was generated by tapir. Do not edit this file manually.
import type { MenuItem } from "./MenuItem";
import type { MenuLabel } from "./MenuLabel";

export type MenuSection = {
  labels?: Array<MenuLabel>,
  items?: Array<MenuItem>,
};
