// This file was generated by tapir. Do not edit this file manually.

/**
 * Localized display text used across menus, sections and items.
 */
export type MenuLabel = {
  displayName: string | null,
  description: string | null,
  languageCode: string | null,
};
