// This file was generated by tapir. Do not edit this file manually.
import type { FoodItemAttributes } from "./FoodItemAttributes";
import type { MenuLabel } from "./MenuLabel";

export type MenuItem = {
  labels?: Array<MenuLabel>,
  attributes: FoodItemAttributes | null,
};
