// This file was generated by tapir. Do not edit this file manually.

/**
 * Price (proto `google.type.Money`): `units` is a stringified int64.
 */
export type Money = {
  currencyCode: string | null,
  units: string | null,
  nanos: number,
};
