// This file was generated by tapir. Do not edit this file manually.

/**
 * Open/closed status: `OPEN`, `CLOSED_PERMANENTLY` or `CLOSED_TEMPORARILY`.
 */
export type OpenInfo = {
  status: string | null,
};
