// This file was generated by tapir. Do not edit this file manually.

/**
 * Media attached to a post — on create, `media_format: PHOTO` plus a public
 * `source_url`; responses add the Google-hosted copy.
 */
export type PostMedia = {
  name: string | null,
  mediaFormat: string | null,
  sourceUrl: string | null,
  googleUrl: string | null,
};
