// This file was generated by tapir. Do not edit this file manually.

/**
 * Storefront address, thinned from `google.type.PostalAddress`.
 */
export type PostalAddress = {
  regionCode: string | null,
  postalCode: string | null,
  administrativeArea: string | null,
  locality: string | null,
  addressLines?: Array<string>,
};
