// This file was generated by tapir. Do not edit this file manually.

/**
 * Storefront address (`google.type.PostalAddress`). Every data-carrying field
 * is modelled: a PATCH masking `storefrontAddress` replaces the message
 * wholesale, so anything missing here would be cleared on the profile. Only
 * `revision` is omitted — Google pins it to 0.
 */
export type PostalAddress = {
  regionCode: string | null,
  languageCode: string | null,
  postalCode: string | null,
  sortingCode: string | null,
  administrativeArea: string | null,
  locality: string | null,
  sublocality: string | null,
  addressLines?: Array<string>,
  recipients?: Array<string>,
  organization: string | null,
};
