// This file was generated by tapir. Do not edit this file manually.

/**
 * Who wrote a question or answer. `author_type` distinguishes `MERCHANT`
 * (the business itself) from `REGULAR_USER`/`LOCAL_GUIDE`.
 */
export type QandaAuthor = {
  displayName: string | null,
  profilePhotoUri: string | null,
  type: string | null,
};
