// This file was generated by tapir. Do not edit this file manually.

/**
 * The merchant's public reply on a review.
 */
export type ReviewReply = {
  comment: string | null,
  updateTime: string | null,
};
