// This file was generated by tapir. Do not edit this file manually.
import type { Review } from "./Review";

export type ReviewPage = {
  reviews: Array<Review>,
  averageRating?: number | null,
  totalReviewCount?: number | null,
  nextPageToken?: string | null,
};
