// This file was generated by tapir. Do not edit this file manually.
import type { InsightsValue } from "./InsightsValue";

export type SearchKeywordCount = {
  searchKeyword: string | null,
  insightsValue: InsightsValue | null,
};
