// This file was generated by tapir. Do not edit this file manually.
import type { SearchKeywordCount } from "./SearchKeywordCount";

export type SearchKeywordPage = {
  searchKeywordsCounts: Array<SearchKeywordCount>,
  nextPageToken?: string | null,
};
