// This file was generated by tapir. Do not edit this file manually.
import type { Date } from "./Date";
import type { TimeOfDay } from "./TimeOfDay";

/**
 * A dated exception to regular hours — closed, or different hours.
 */
export type SpecialHourPeriod = {
  startDate: Date | null,
  endDate: Date | null,
  openTime: TimeOfDay | null,
  closeTime: TimeOfDay | null,
  closed: boolean | null,
};
