// This file was generated by tapir. Do not edit this file manually.
import type { TimeOfDay } from "./TimeOfDay";

/**
 * One weekly open interval. Days are `MONDAY`…`SUNDAY`; a span crossing
 * midnight has `close_day` ≠ `open_day`.
 */
export type TimePeriod = {
  openDay: string | null,
  openTime: TimeOfDay | null,
  closeDay: string | null,
  closeTime: TimeOfDay | null,
};
