// This file was generated by tapir. Do not edit this file manually.
import type { Date } from "./Date";
import type { TimeOfDay } from "./TimeOfDay";

export type TimeInterval = {
  startDate: Date | null,
  startTime: TimeOfDay | null,
  endDate: Date | null,
  endTime: TimeOfDay | null,
};
