// This file was generated by tapir. Do not edit this file manually.

/**
 * Time of day (proto3 `google.type.TimeOfDay`): midnight serializes as `{}`.
 */
export type TimeOfDay = {
  hours: number,
  minutes: number,
};
