// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ChannelRule } from "../../types/social_account/ChannelRule";

export const channel = {
  /**
   * List every channel with the platform rules the hub enforces on it, so a
   * client offers only what a send will pass.
   *
   * Any authenticated caller; no permission or scope applies.
   */
  list: Tapi.get<{ response: Array<ChannelRule> }>()({
    endpoint: "/channel",
  }),
};
