// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { WebhookVerifyQuery } from "../../../types/message/WebhookVerifyQuery";

export const meta = {
  /**
   * Meta webhook receiver: verifies the payload signature, stores normalized
   * messages (deduplicating redeliveries), and enqueues CRM fan-out events.
   *
   * Public — no authentication required; authorization comes from the `X-Hub-Signature-256` HMAC over the raw body.
   */
  receive: Tapi.post<{ response: null }>()({
    endpoint: "/webhook/meta",
  }),
  /**
   * Meta webhook verification handshake: echoes `hub.challenge` when
   * `hub.verify_token` matches the configured token.
   *
   * Public — no authentication required; authorization comes from the configured webhook verify token.
   */
  verify: Tapi.get<{ query: WebhookVerifyQuery; response: string }>()({
    endpoint: "/webhook/meta",
  }),
};
