// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { SearchHit } from "../../types/database/SearchHit";
import type { SearchQuery } from "../../types/search/SearchQuery";

export const search = {
  /**
   * Search groups and users in one ranked result set.
   *
   * Any authenticated user; the results cover the caller's own groups and the people sharing them, and every group and user for platform staff.
   */
  global: Tapi.get<{ query: SearchQuery; response: Array<SearchHit> }>()({
    endpoint: "/search",
  }),
};
