// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { MessageSearchHit } from "../../types/domain/MessageSearchHit";
import type { MessageSearchQuery } from "../../types/search/MessageSearchQuery";
import type { SearchHit } from "../../types/domain/SearchHit";
import type { SearchQuery } from "../../types/search/SearchQuery";

export const search = {
  /**
   * Search groups, users, contacts and messages: up to `limit` hits of each requested kind, kinds in a fixed order, groups and users ranked, contacts and messages newest first. A preview — the entity lists page the full answers.
   *
   * Any authenticated user; groups and users cover the caller's own groups and the people sharing them (every group and user for platform staff); contacts and messages cover the accounts of every group where the caller holds `ViewMessages` (every account for platform staff, none for a caller holding it nowhere).
   */
  global: Tapi.get<{ query: SearchQuery; response: Array<SearchHit> }>()({
    endpoint: "/search",
  }),
  /**
   * Search message text, newest first; `before_id` pages older hits. `conversation_uid` searches inside one conversation; otherwise every conversation of the filtered accounts. Each hit carries a snippet split into plain and matched runs.
   *
   * Requires `ViewMessages`; the hits cover only messages of groups where the caller holds it, and a conversation outside them reads as not found.
   */
  message: Tapi.get<{ query: MessageSearchQuery; response: Array<MessageSearchHit> }>()({
    endpoint: "/search/message",
  }),
};
