// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { Uid } from "../../../types/primitives/Uid";
import type { UserMfaAdminResetResponse } from "../../../types/user_mfa/UserMfaAdminResetResponse";

export const admin = {
  /**
   * Remove all MFA factors for another user as an administrative recovery action.
   *
   * Requires `ResetUserMfa`, which only platform staff hold; resetting your own factors is forbidden.
   */
  reset: Tapi.post<{ path: { user_uid: Uid }; response: UserMfaAdminResetResponse }>()({
    endpoint: "/user/:user_uid/mfa/reset",
  }),
};
