// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type UserMfaMgmtEmailStartResponse = {
  enrollment_token: Uid,
  expiry_minutes: number,
};
