// This file was generated by tapir. Do not edit this file manually.
import type { Pin6 } from "../primitives/Pin6";
import type { Uid } from "../primitives/Uid";
import type { UserMfaKind } from "../types/UserMfaKind";

export type UserMfaVerifyRequest = {
  mfa_token: Uid,
  factor: UserMfaKind,
  code: Pin6,
};
