// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { UserMfaKind } from "../domain/UserMfaKind";

export type UserMfaFactorRow = {
  kind: UserMfaKind,
  confirmed_at: Timestamp | null,
  last_used_at: Timestamp | null,
};
