// This file was generated by tapir. Do not edit this file manually.
import type { Pin6 } from "../primitives/Pin6";
import type { Uid } from "../primitives/Uid";

export type UserMfaEnrollConfirmRequest = {
  enrollment_token: Uid,
  code: Pin6,
};
