// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";
import type { UserMfaKind } from "../types/UserMfaKind";

export type UserMfaDispatchRequest = {
  mfa_token: Uid,
  factor: UserMfaKind,
};
