// This file was generated by tapir. Do not edit this file manually.
import type { AuditAction } from "../types/AuditAction";
import type { AuditResource } from "../types/AuditResource";
import type { Number1_10000 } from "../primitives/Number1_10000";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type AuditLogQuery = {
  group_uid: Uid | null,
  user_uid: Uid | null,
  action: AuditAction | null,
  resource: AuditResource | null,
  resource_uid: string | null,
} & ({
  "window": "range",
  since: Timestamp,
  until: Timestamp,
} | {
  "window": "latest",
  count: Number1_10000,
});
