// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";

export const gateway = {
  /**
   * Alternate-gateway webhook receiver for the alt channels: verifies the
   * payload signature, stores normalized messages (deduplicating
   * redeliveries), applies receipts, reactions, edits and revokes, flags
   * accounts whose grant died, and enqueues CRM fan-out events.
   *
   * Public — no authentication required; authorization comes from the gateway's signature header, an HMAC over the raw body.
   */
  receive: Tapi.post<{ response: null }>()({
    endpoint: "/webhook/gateway",
  }),
};
