// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type CreateUploadUrlResponse = {
  upload_url: string,
  expires_at: Timestamp,
  max_bytes: number,
};
