// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type CreateUploadUrlRequest = {
  /**
   * Required for users and platform keys; group-bound keys imply their group.
   */
  group_uid: Uid | null,
  filename: string | null,
  content_type: string | null,
};
