// This file was generated by tapir. Do not edit this file manually.

/**
 * A signed grant on the media URL: the hub mints one for a platform that has
 * to fetch a file it is about to deliver. Absent on an ordinary fetch.
 */
export type MediaGrantQuery = {
  exp: number | null,
  sig: string | null,
};
