// This file was generated by tapir. Do not edit this file manually.
import type { MediaKind } from "../domain/MediaKind";
import type { Uid } from "../primitives/Uid";

export type UploadMediaResponse = {
  uid: Uid,
  /**
   * Public URL Meta (and CRMs) can fetch — usable anywhere the send/publish
   * APIs take a media URL.
   */
  url: string,
  kind: MediaKind,
  content_type: string,
  size: number,
};
