// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Email = string & { readonly __brand: "Email" };

const SPEC: ValidationSpec = { preprocess: "trim_lowercase", constraints: [{ kind: "minLen", min: 5 }, { kind: "maxLen", max: 254 }, { kind: "regex", source: "^[a-zA-Z0-9_%+-]+(\\.[a-zA-Z0-9_%+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.[a-zA-Z]{2,}$", hint: null }] };

export const Email = {
  /** The only producer of a `Email`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Email | Violation => check(SPEC, value) ?? (value as Email),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
