// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Name = string & { readonly __brand: "Name" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "minLen", min: 2 }, { kind: "maxLen", max: 100 }, { kind: "noControlChars" }] };

export const Name = {
  /** The only producer of a `Name`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Name | Violation => check(SPEC, value) ?? (value as Name),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
