// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

/**
 * A bounded integer. `MIN`/`MAX` are inclusive `i64` bounds (width-agnostic, so
 * they flow to the frontend as one `number(min, max)` spec regardless of `B`);
 * `B` is the backing primitive the value is stored as and (de)serialized through
 * — pick it to match the DB column so the newtype is the type end-to-end.
 */
export type Number1_500 = number & { readonly __brand: "Number1_500" };

const SPEC: ValidationSpec = { preprocess: "none", constraints: [{ kind: "min", value: 1 }, { kind: "max", value: 500 }] };

export const Number1_500 = {
  /** The only producer of a `Number1_500`: validates input, returns the branded value or the first violation. */
  parse: (value: number): Number1_500 | Violation => check(SPEC, value) ?? (value as Number1_500),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: number): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
