// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Password8_128_F_F_T_F = string & { readonly __brand: "Password8_128_F_F_T_F" };

const SPEC: ValidationSpec = { preprocess: "none", constraints: [{ kind: "minLen", min: 8 }, { kind: "maxLen", max: 128 }, { kind: "requireDigit" }] };

export const Password8_128_F_F_T_F = {
  /** The only producer of a `Password8_128_F_F_T_F`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Password8_128_F_F_T_F | Violation => check(SPEC, value) ?? (value as Password8_128_F_F_T_F),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
