// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Phone = string & { readonly __brand: "Phone" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "minDigits", min: 7 }, { kind: "maxDigits", max: 15 }, { kind: "regex", source: "^\\+[1-9]\\d{6,14}$", hint: "esperado E.164: +<código do país><número>" }] };

export const Phone = {
  /** The only producer of a `Phone`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Phone | Violation => check(SPEC, value) ?? (value as Phone),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
