// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Pin6 = string & { readonly __brand: "Pin6" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "exactLen", len: 6 }, { kind: "asciiDigitsOnly" }] };

export const Pin6 = {
  /** The only producer of a `Pin6`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Pin6 | Violation => check(SPEC, value) ?? (value as Pin6),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
