// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Text255 = string & { readonly __brand: "Text255" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "maxLen", max: 255 }] };

export const Text255 = {
  /** The only producer of a `Text255`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Text255 | Violation => check(SPEC, value) ?? (value as Text255),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
