// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

/**
 * Free text with its length bounds in the type, read as a range: `Text<2, 8000>`
 * is "2..=8000", matching [`crate::Number`]'s parameter order. Neither bound
 * defaults — an unbounded-below field spells its `0` — so a length is never
 * silently the wrong end of the range. Both reach the emitted TypeScript
 * through [`Validated`], so a consumer sees the same rule the server enforces.
 */
export type Text0_2048 = string & { readonly __brand: "Text0_2048" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "minLen", min: 0 }, { kind: "maxLen", max: 2048 }] };

export const Text0_2048 = {
  /** The only producer of a `Text0_2048`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Text0_2048 | Violation => check(SPEC, value) ?? (value as Text0_2048),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
