// This file was generated by tapir. Do not edit this file manually.
import { check, checkAll, type Violation, type ValidationSpec } from "../validate";

export type Text8000 = string & { readonly __brand: "Text8000" };

const SPEC: ValidationSpec = { preprocess: "trim", constraints: [{ kind: "maxLen", max: 8000 }] };

export const Text8000 = {
  /** The only producer of a `Text8000`: validates input, returns the branded value or the first violation. */
  parse: (value: string): Text8000 | Violation => check(SPEC, value) ?? (value as Text8000),
  /** Every unmet rule — for a live checklist / strength meter. Empty ⇒ valid. */
  parseAll: (value: string): Violation[] => checkAll(SPEC, value),
  /** The rules themselves, so a UI can render them. */
  spec: SPEC,
};
