// This file was generated by tapir. Do not edit this file manually.
import type { ValidationSpec } from "../validate";

export type Timestamp = number & { readonly __brand: "Timestamp" };

const SPEC: ValidationSpec = { preprocess: "none", constraints: [] };

export const Timestamp = {
  /** The only producer of a `Timestamp`. Nothing to validate — the brand names the domain, it does not prove membership. */
  parse: (value: number): Timestamp => value as Timestamp,
  /** No rules to be unmet — present so a `Timestamp` reads as the newtype it is. */
  parseAll: (_value: number): [] => [],
  /** Present so a branded and a validated newtype share one interface. */
  spec: SPEC,
};
