// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { UserMfaDispatchRequest } from "../../types/user_mfa/UserMfaDispatchRequest";
import type { UserMfaVerifyRequest } from "../../types/user_mfa/UserMfaVerifyRequest";
import type { UserMfaVerifyResponse } from "../../types/user_mfa/UserMfaVerifyResponse";
import { admin } from "./admin";
import { enroll } from "./enroll";
import { factor } from "./factor";

export const userMfa = {
  /**
   * Dispatch a login MFA challenge for the chosen factor, emailing a one-time code for the email factor.
   *
   * Public — no authentication required; the request is gated solely by the ephemeral login MFA token in the body.
   */
  dispatch: Tapi.post<{ body: UserMfaDispatchRequest; response: null }>()({
    endpoint: "/user-session/mfa/dispatch",
  }),
  /**
   * Verify a login MFA code and, on success, mint a user session token.
   *
   * Public — no authentication required; the request is gated solely by the ephemeral login MFA token in the body.
   */
  verify: Tapi.post<{ body: UserMfaVerifyRequest; response: UserMfaVerifyResponse }>()({
    endpoint: "/user-session/mfa/verify",
  }),
  admin,
  enroll,
  factor,
};
