// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateRateLimitRuleRequest } from "../../types/rate_limit/CreateRateLimitRuleRequest";
import type { CreateRateLimitRuleResponse } from "../../types/rate_limit/CreateRateLimitRuleResponse";
import type { RateLimitRule } from "../../types/database/RateLimitRule";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateRateLimitRuleRequest } from "../../types/rate_limit/UpdateRateLimitRuleRequest";

export const rateLimit = {
  /**
   * Create a rate-limit rule for any target kind (HTTP scope, action, email dispatch, or channel pacing).
   *
   * Requires `CreateRateLimits`, which only platform staff hold.
   */
  create: Tapi.post<{ body: CreateRateLimitRuleRequest; response: CreateRateLimitRuleResponse }>()({
    endpoint: "/rate-limit",
  }),
  /**
   * Delete a rate-limit rule by uid.
   *
   * Requires `DeleteRateLimits`, which only platform staff hold.
   */
  delete: Tapi.delete<{ path: { rule_uid: Uid }; response: null }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
  /**
   * Fetch a single rate-limit rule by uid.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { rule_uid: Uid }; response: RateLimitRule }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
  /**
   * List every rate-limit rule.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<RateLimitRule> }>()({
    endpoint: "/rate-limit",
  }),
  /**
   * Update an existing rate-limit rule's budget; the rule's target is immutable.
   *
   * Requires `UpdateRateLimits`, which only platform staff hold.
   */
  update: Tapi.put<{ path: { rule_uid: Uid }; body: UpdateRateLimitRuleRequest; response: null }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
};
