// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateRateLimitRuleRequest } from "../../types/rate_limit/CreateRateLimitRuleRequest";
import type { CreateRateLimitRuleResponse } from "../../types/rate_limit/CreateRateLimitRuleResponse";
import type { ListRateLimitRulesQuery } from "../../types/rate_limit/ListRateLimitRulesQuery";
import type { RateLimitRuleResponse } from "../../types/rate_limit/RateLimitRuleResponse";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateRateLimitRuleRequest } from "../../types/rate_limit/UpdateRateLimitRuleRequest";

export const rateLimit = {
  /**
   * Create a rate-limit rule in a tier: one bucket shared by the whole
   * platform, the per-caller global default, a staff override for one group,
   * or a group's own (tighter) limit.
   *
   * Requires `CreateRateLimits` — platform-wide for `shared`, `global` and
   * `override`, in the group for `own`.
   */
  create: Tapi.post<{ body: CreateRateLimitRuleRequest; response: CreateRateLimitRuleResponse }>()({
    endpoint: "/rate-limit",
  }),
  /**
   * Delete a rate-limit rule by uid.
   *
   * Requires `DeleteRateLimits` in the rule's tier.
   */
  delete: Tapi.delete<{ path: { rule_uid: Uid }; response: null }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
  /**
   * Fetch a single rate-limit rule by uid.
   *
   * Requires `ViewRateLimits` — anywhere for a shared or global rule, in the
   * group for a group tier.
   */
  get: Tapi.get<{ path: { rule_uid: Uid }; response: RateLimitRuleResponse }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
  /**
   * List rate-limit rules across every tier the caller may see.
   *
   * Requires `ViewRateLimits`.
   */
  list: Tapi.get<{ query: ListRateLimitRulesQuery; response: Array<RateLimitRuleResponse> }>()({
    endpoint: "/rate-limit",
  }),
  /**
   * Update an existing rate-limit rule's budget; the rule's target and tier
   * are immutable.
   *
   * Requires `UpdateRateLimits` in the rule's tier.
   */
  update: Tapi.put<{ path: { rule_uid: Uid }; body: UpdateRateLimitRuleRequest; response: null }>()({
    endpoint: "/rate-limit/:rule_uid",
  }),
};
