// This file was generated by tapi. Do not edit manually.

import { action } from "./action";
import { http } from "./http";
import { pacing } from "./pacing";

export const rateLimit = {
  action,
  http,
  pacing,
};
