// This file was generated by tapir. Do not edit this file manually.
import type { MetaBackfill } from "./MetaBackfill";

/**
 * Channel-tagged backfill request — Meta's Conversations API covers the
 * page-backed inboxes only, so no other channel's shape deserializes. The
 * `channel` must match the named account's.
 */
export type BackfillRequest = {
  "channel": "facebook"
} & MetaBackfill | {
  "channel": "instagram"
} & MetaBackfill;
