// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100 } from "../primitives/Number1_100";
import type { Number1_200 } from "../primitives/Number1_200";
import type { Uid } from "../primitives/Uid";

export type BackfillRequest = {
  social_account_uid: Uid,
  /**
   * How many conversations to import (newest first); defaults to 50.
   */
  conversations: Number1_200 | null,
  /**
   * How many messages per conversation (newest first); defaults to 50.
   */
  messages_per_conversation: Number1_100 | null,
};
