// This file was generated by tapir. Do not edit this file manually.
import type { MessageContentKind } from "../domain/MessageContentKind";

export type ConversationMessageCountQuery = {
  /**
   * Only messages of these content kinds — the same narrowing as the list.
   */
  kinds: Array<MessageContentKind> | null,
};
