// This file was generated by tapir. Do not edit this file manually.
import type { MessageContentKind } from "../types/MessageContentKind";
import type { Number1_200 } from "../primitives/Number1_200";

export type ConversationMessagesQuery = {
  /**
   * Scrollback cursor: only messages with `id` strictly smaller are returned.
   */
  before_id: number | null,
  /**
   * Forward cursor: the oldest `limit` messages with `id` strictly greater,
   * returned newest-first — each page continues upward from the last.
   * Exclusive with `before_id`.
   */
  after_id: number | null,
  limit: Number1_200 | null,
  /**
   * Only messages of these content kinds. A media gallery pages
   * `image, video, gif, sticker, audio, file` without loading the text
   * between them; absent or empty means every kind.
   */
  kinds: Array<MessageContentKind> | null,
};
