// This file was generated by tapir. Do not edit this file manually.
import type { PresenceSignal } from "./PresenceSignal";
import type { SelfClearingPresenceSignal } from "./SelfClearingPresenceSignal";

/**
 * A presence signal, tagged by channel so a signal the channel has no call
 * for does not deserialize. The `channel` must match the conversation's
 * account.
 */
export type ConversationActionRequest = {
  "channel": "facebook"
} & PresenceSignal | {
  "channel": "instagram"
} & PresenceSignal | {
  "channel": "whatsapp"
} & SelfClearingPresenceSignal | {
  "channel": "whatsapp_native"
} & PresenceSignal | {
  "channel": "facebook_alt"
} & SelfClearingPresenceSignal | {
  "channel": "instagram_alt"
} & SelfClearingPresenceSignal | {
  "channel": "whatsapp_alt"
} & SelfClearingPresenceSignal;
