// This file was generated by tapir. Do not edit this file manually.
import type { Phone } from "../primitives/Phone";
import type { Uid } from "../primitives/Uid";

/**
 * Channel-tagged conversation creation — only the channels that can verify
 * a number on the platform can initiate, so no other channel's shape
 * deserializes.
 */
export type CreateConversationRequest = {
  "channel": "whatsapp_stevo",
  /**
   * A whatsapp_stevo social account.
   */
  social_account_uid: Uid,
  /**
   * The recipient's phone in E.164 (`+<country code><number>`).
   */
  phone: Phone,
} | {
  "channel": "whatsapp_native",
  /**
   * A whatsapp_native social account.
   */
  social_account_uid: Uid,
  /**
   * The recipient's phone in E.164 (`+<country code><number>`).
   */
  phone: Phone,
};
