// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";
import type { WhatsappTemplateCategory } from "../meta/WhatsappTemplateCategory";
import type { WhatsappTemplateComponent } from "../meta/WhatsappTemplateComponent";

export type CreateTemplateRequest = {
  /**
   * Any whatsapp account of the WABA whose templates are managed.
   */
  social_account_uid: Uid,
  /**
   * Lowercase letters, digits and underscores (Meta's rule), e.g.
   * `order_update`.
   */
  name: string,
  /**
   * Locale code, e.g. `pt_BR`.
   */
  language: string,
  category: WhatsappTemplateCategory,
  /**
   * The template's blocks. Meta validates the assembled definition and owns
   * the verdict — a rejection comes back as its own message.
   */
  components: Array<WhatsappTemplateComponent>,
};
