// This file was generated by tapir. Do not edit this file manually.

export type CreateTemplateResponse = {
  id: string,
  /**
   * Usually `pending` — templates go through Meta review before turning
   * `approved` and sendable.
   */
  status: string | null,
  category: string | null,
};
