// This file was generated by tapir. Do not edit this file manually.
import type { Phone } from "../primitives/Phone";
import type { TemplateOpener } from "./TemplateOpener";
import type { Uid } from "../primitives/Uid";

/**
 * Channel-tagged conversation creation — whatsapp_native verifies the
 * number on the platform and opens the thread silently; whatsapp and
 * whatsapp_alt open it by sending an approved template, the only content
 * those channels accept before the recipient writes. No other channel's
 * shape deserializes.
 */
export type CreateConversationRequest = {
  "channel": "whatsapp_native",
  /**
   * A whatsapp_native social account.
   */
  social_account_uid: Uid,
  /**
   * The recipient's phone in E.164 (`+<country code><number>`).
   */
  phone: Phone,
} | {
  "channel": "whatsapp",
  /**
   * A whatsapp social account.
   */
  social_account_uid: Uid,
  /**
   * The recipient's phone in E.164 (`+<country code><number>`).
   */
  phone: Phone,
  /**
   * The approved template that opens the thread, queued as its first send.
   */
  template: TemplateOpener,
} | {
  "channel": "whatsapp_alt",
  /**
   * A whatsapp_alt social account.
   */
  social_account_uid: Uid,
  /**
   * The recipient's phone in E.164 (`+<country code><number>`).
   */
  phone: Phone,
  /**
   * The approved template that opens the thread, queued as its first send.
   */
  template: TemplateOpener,
};
