// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type DeleteTemplateQuery = {
  /**
   * Any whatsapp account of the WABA whose templates are managed.
   */
  social_account_uid: Uid,
  name: string,
  /**
   * Delete only this template id; omitted, every language of `name` goes.
   */
  hsm_id: string | null,
};
