// This file was generated by tapir. Do not edit this file manually.
import type { MessageEdit } from "./MessageEdit";

/**
 * Channel-tagged edit payload — only native WhatsApp exposes a platform
 * edit call, so no other channel's shape deserializes. The `channel` must
 * match the message's.
 */
export type EditMessageRequest = {
  "channel": "whatsapp_native"
} & MessageEdit;
