// This file was generated by tapir. Do not edit this file manually.
import type { ForwardRejection } from "./ForwardRejection";
import type { MessageWithContext } from "./MessageWithContext";
import type { Uid } from "../primitives/Uid";

/**
 * What forwarding did for one target. Tagged rather than a nullable pair: a
 * queued forward carries its message and a refused one carries why, and
 * neither shape can express the other.
 */
export type ForwardOutcome = {
  "outcome": "queued",
  conversation_uid: Uid,
  message: MessageWithContext,
} | {
  "outcome": "rejected",
  conversation_uid: Uid,
  reason: ForwardRejection,
};
