// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * Forward one message into other conversations. Each target is re-sent as an
 * ordinary message: the hub owns forwarding, so nothing marks the copy as
 * forwarded on the platform or in storage.
 */
export type ForwardMessageRequest = {
  /**
   * The conversations to forward into (≤20). Each is answered separately in
   * the response; one refused target never blocks the others.
   */
  targets: Array<Uid>,
};
