// This file was generated by tapir. Do not edit this file manually.

/**
 * Why one target was refused. A closed set the caller renders — per-target
 * prose never rides a success body.
 */
export type ForwardRejection = "unreachable" | "account_disabled" | "unsupported_content" | "window_expired" | "failed";

/** Every `ForwardRejection`, in declaration order. */
export const FORWARD_REJECTION = ["unreachable", "account_disabled", "unsupported_content", "window_expired", "failed"] as const satisfies readonly ForwardRejection[];
