// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * Forward one message into other conversations. Each target is re-sent as a
 * message of its own that the hub marks as forwarded; native whatsapp shows
 * the recipient the forwarded label, the other channels have no such marker.
 */
export type ForwardMessageRequest = {
  /**
   * The conversations to forward into (≤5). Each is answered separately in
   * the response; one refused target never blocks the others.
   */
  targets: Array<Uid>,
};
