// This file was generated by tapir. Do not edit this file manually.
import type { Number1_500 } from "../primitives/Number1_500";
import type { Uid } from "../primitives/Uid";

export type ListMessagesQuery = {
  group_uid: Uid | null,
  social_account_uid: Uid | null,
  /**
   * Poll cursor: only messages with `id` strictly greater are returned.
   */
  since_id: number,
  limit: Number1_500 | null,
};
