// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ListTemplatesQuery = {
  /**
   * Any whatsapp account of the WABA whose templates are managed.
   */
  social_account_uid: Uid,
};
