// This file was generated by tapir. Do not edit this file manually.
import type { MessageTag } from "../meta/MessageTag";
import type { MessengerContent } from "./MessengerContent";
import type { QuickReply } from "../types/QuickReply";

/**
 * Messenger/Instagram DM payload (Send API). Attachments carry no captions;
 * quick replies may attach to any content.
 */
export type MessengerSend = {
  content: MessengerContent,
  /**
   * Lifts the standard 24h response window (`human_agent` = 7 days; the
   * Meta app must hold the `human_agent` permission).
   */
  tag: MessageTag | null,
  /**
   * Up to 13 quick-reply chips.
   */
  quick_replies: Array<QuickReply> | null,
};
