// This file was generated by tapir. Do not edit this file manually.
import type { ContactCard } from "../types/ContactCard";

export type NativeContent = {
  "kind": "text",
  text: string,
} | {
  "kind": "image",
  url: string,
  caption: string | null,
} | {
  "kind": "audio",
  url: string,
  voice: boolean,
} | {
  "kind": "video",
  url: string,
  caption: string | null,
} | {
  "kind": "gif",
  url: string,
} | {
  "kind": "file",
  url: string,
  caption: string | null,
  filename: string | null,
} | {
  "kind": "location",
  latitude: number,
  longitude: number,
  name: string | null,
  address: string | null,
} | {
  "kind": "contact",
  contact: ContactCard,
};
