// This file was generated by tapir. Do not edit this file manually.
import type { SenderAction } from "../meta/SenderAction";

/**
 * Presence on a channel with a real typing state: `typing_off` is a signal
 * of its own.
 */
export type PresenceSignal = {
  action: SenderAction,
};
