// This file was generated by tapir. Do not edit this file manually.

export type SelfClearingSenderAction = "mark_seen" | "typing_on";

/** Every `SelfClearingSenderAction`, in declaration order. */
export const SELF_CLEARING_SENDER_ACTION = ["mark_seen", "typing_on"] as const satisfies readonly SelfClearingSenderAction[];
