// This file was generated by tapir. Do not edit this file manually.
import type { SelfClearingSenderAction } from "./SelfClearingSenderAction";

/**
 * Official whatsapp and the gateway channels have no `typing_off` call —
 * their indicator clears on its own — so the shape cannot express one.
 */
export type SelfClearingPresenceSignal = {
  action: SelfClearingSenderAction,
};
