// This file was generated by tapir. Do not edit this file manually.
import type { MessengerSend } from "./MessengerSend";
import type { NativeSend } from "./NativeSend";
import type { StevoSend } from "./StevoSend";
import type { WhatsappSend } from "./WhatsappSend";

export type SendMessageRequest = {
  /**
   * Client dedup key, unique per conversation. Retrying with the same key
   * never duplicates history: a failed row is retried in place, any other
   * row (sent, pending, canceled) is returned as-is without a new send.
   */
  idempotency_key: string | null,
} & ({
  "channel": "facebook"
} & MessengerSend | {
  "channel": "instagram"
} & MessengerSend | {
  "channel": "whatsapp"
} & WhatsappSend | {
  "channel": "whatsapp_stevo"
} & StevoSend | {
  "channel": "whatsapp_native"
} & NativeSend);
