// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappTemplateSendComponent } from "../meta/WhatsappTemplateSendComponent";

/**
 * An approved template reference, the same shape the `template` send
 * content takes: `components` fills the approved definition's placeholders.
 */
export type TemplateOpener = {
  name: string,
  language: string,
  components: Array<WhatsappTemplateSendComponent> | null,
};
