// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappTemplateCategory } from "../meta/WhatsappTemplateCategory";
import type { WhatsappTemplateComponent } from "../meta/WhatsappTemplateComponent";
import type { WhatsappTemplateStatus } from "../meta/WhatsappTemplateStatus";

export type TemplateResponse = {
  id: string,
  name: string,
  language: string,
  category: WhatsappTemplateCategory,
  /**
   * Only `approved` templates are sendable.
   */
  status: WhatsappTemplateStatus,
  components: Array<WhatsappTemplateComponent>,
};
