// This file was generated by tapir. Do not edit this file manually.

export type WebhookVerifyQuery = {
  "hub.mode": string | null,
  "hub.verify_token": string | null,
  "hub.challenge": string | null,
};
