// This file was generated by tapir. Do not edit this file manually.
import type { WhatsappSenderAction } from "./WhatsappSenderAction";

/**
 * Official whatsapp has no `typing_off` call — its indicator clears on its
 * own — so the shape cannot express one.
 */
export type WhatsappPresenceSignal = {
  action: WhatsappSenderAction,
};
