// This file was generated by tapir. Do not edit this file manually.

export type WhatsappSenderAction = "mark_seen" | "typing_on";

/** Every `WhatsappSenderAction`, in declaration order. */
export const WHATSAPP_SENDER_ACTION = ["mark_seen", "typing_on"] as const satisfies readonly WhatsappSenderAction[];
