// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Uid } from "../../types/primitives/Uid";
import type { UserInvite } from "../../types/database/UserInvite";
import type { UserInviteAcceptRequest } from "../../types/user_invite/UserInviteAcceptRequest";
import type { UserInviteAcceptResponse } from "../../types/user_invite/UserInviteAcceptResponse";
import type { UserInviteSendRequest } from "../../types/user_invite/UserInviteSendRequest";
import type { UserInviteSendResponse } from "../../types/user_invite/UserInviteSendResponse";

export const userInvite = {
  /**
   * Accept an invitation by its token, creating the user account with the chosen
   * password and, in the same transaction, the membership the invitation carries.
   *
   * Public — no authentication required; authorization comes from the invitation token in the request body.
   */
  accept: Tapi.post<{ body: UserInviteAcceptRequest; response: UserInviteAcceptResponse }>()({
    endpoint: "/user-invite/accept",
  }),
  /**
   * Count pending (unaccepted) user invitations.
   *
   * Requires `ViewInvites`; the count covers only invites into groups where the caller holds it, and platform invites only for platform staff.
   */
  count: Tapi.get<{ response: number }>()({
    endpoint: "/user-invite/count",
  }),
  /**
   * List pending (unaccepted) user invitations.
   *
   * Requires `ViewInvites`; the list covers only invites into groups where the caller holds it, and platform invites only for platform staff.
   */
  list: Tapi.get<{ response: Array<UserInvite> }>()({
    endpoint: "/user-invite",
  }),
  /**
   * Refresh a pending user invitation's expiry and re-send its email.
   *
   * Requires `InviteUsers` in the invitation's group plus a role there that may hand out the invited one, or `OperatePlatformScope` for an invitation naming no group.
   */
  resend: Tapi.post<{ path: { invite_uid: Uid }; response: null }>()({
    endpoint: "/user-invite/:invite_uid/resend",
  }),
  /**
   * Revoke a pending user invitation so its registration link can no longer be used.
   *
   * Requires `InviteUsers` in the invitation's group plus a role there that may hand out the invited one, or `OperatePlatformScope` for an invitation naming no group.
   */
  revoke: Tapi.delete<{ path: { invite_uid: Uid }; response: null }>()({
    endpoint: "/user-invite/:invite_uid",
  }),
  /**
   * Send an invitation that lets the recipient register a user account, joining
   * the named group with the named role once accepted. Naming neither invites to
   * the platform alone; naming only one of the two is refused.
   *
   * Requires `InviteUsers` in the named group plus a role there that may hand out the named one, or `OperatePlatformScope` when no group is named.
   */
  send: Tapi.post<{ body: UserInviteSendRequest; response: UserInviteSendResponse }>()({
    endpoint: "/user-invite",
  }),
};
