// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { SetUserNotificationRequest } from "../../types/user/SetUserNotificationRequest";
import type { UserNotificationResponse } from "../../types/user/UserNotificationResponse";

export const userNotification = {
  /**
   * Get the caller's own notification choices that are not tied to one account: the sound a new message plays. Defaults stand until the caller changes them.
   *
   * Authenticated user acting on their own account.
   */
  get: Tapi.get<{ response: UserNotificationResponse }>()({
    endpoint: "/user/me/notification",
  }),
  /**
   * Change the caller's own notification choices that are not tied to one account.
   *
   * Authenticated user acting on their own account.
   */
  set: Tapi.put<{ body: SetUserNotificationRequest; response: null }>()({
    endpoint: "/user/me/notification",
  }),
};
