// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { VersionResponse } from "../../types/version/VersionResponse";

export const version = {
  /**
   * The release the server runs. A client generated from another release is
   * outside its contract; the frontend reloads itself once the build being
   * served matches this number.
   *
   * Public — no authentication required; the release number is no secret, the served frontend already states it.
   */
  get: Tapi.get<{ response: VersionResponse }>()({
    endpoint: "/version",
  }),
};
