// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Uid } from "../../types/primitives/Uid";
import type { UserMembershipResponse } from "../../types/user/UserMembershipResponse";

export const userMembership = {
  /**
   * List the groups another user belongs to, each carrying the role that membership holds there.
   *
   * Requires `ViewUsers`, which only platform staff hold.
   */
  list: Tapi.get<{ path: { user_uid: Uid }; response: Array<UserMembershipResponse> }>()({
    endpoint: "/user/:user_uid/membership",
  }),
};
