// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CampaignTemplateResponse } from "../../types/campaign/CampaignTemplateResponse";
import type { TemplateRequest } from "../../types/campaign/TemplateRequest";
import type { Uid } from "../../types/primitives/Uid";

export const campaignTemplate = {
  /**
   * Append a template to the wheel. Draft, paused and done only.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  add: Tapi.post<{ path: { campaign_uid: Uid }; body: TemplateRequest; response: CampaignTemplateResponse }>()({
    endpoint: "/campaign/:campaign_uid/template",
  }),
  /**
   * Remove a template from the wheel. Draft, paused and done only.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  delete: Tapi.delete<{ path: { campaign_uid: Uid; template_uid: Uid }; response: null }>()({
    endpoint: "/campaign/:campaign_uid/template/:template_uid",
  }),
  /**
   * The template wheel, in rotation order.
   *
   * Requires `ViewCampaigns` in the campaign's group.
   */
  list: Tapi.get<{ path: { campaign_uid: Uid }; response: Array<CampaignTemplateResponse> }>()({
    endpoint: "/campaign/:campaign_uid/template",
  }),
  /**
   * Rewrite a template in place, keeping its position in the wheel. Draft,
   * paused and done only; the same checks as adding one.
   *
   * Requires `ManageCampaigns` in the campaign's group.
   */
  update: Tapi.put<{ path: { campaign_uid: Uid; template_uid: Uid }; body: TemplateRequest; response: CampaignTemplateResponse }>()({
    endpoint: "/campaign/:campaign_uid/template/:template_uid",
  }),
};
