// This file was generated by tapir. Do not edit this file manually.

/**
 * One catalog entry, in the renditions the composer needs.
 */
export type Gif = {
  id: string,
  title: string,
  /**
   * The picker tile: an animated webp, or a gif when Giphy has no webp.
   */
  preview_url: string,
  preview_width: number,
  preview_height: number,
  /**
   * The clip the bubble plays — sent as `gif` natively and as a plain video
   * on the channels without a gif shape.
   */
  mp4_url: string,
  /**
   * The .gif itself, for the channels that animate an image attachment.
   */
  gif_url: string,
};
