// This file was generated by tapir. Do not edit this file manually.
import type { Gif } from "./Gif";
import type { Number0_4999 } from "../primitives/Number0_4999";

export type GifSearchResponse = {
  items: Array<Gif>,
  /**
   * The `offset` of the page after this one; absent on the last page.
   */
  next_offset: Number0_4999 | null,
};
