// This file was generated by tapir. Do not edit this file manually.
import type { Number0_4999 } from "../primitives/Number0_4999";
import type { Text0_50 } from "../primitives/Text0_50";

export type SearchGifsQuery = {
  /**
   * Search terms; blank or absent lists the trending feed instead.
   */
  q: Text0_50 | null,
  /**
   * Where the page starts — the previous page's `next_offset`; 0 when absent.
   */
  offset: Number0_4999 | null,
};
