// This file was generated by tapir. Do not edit this file manually.

/**
 * GoHighLevel's `ProviderOutboundMessage` delivery payload (SMS shape): one
 * message a location placed on our conversation provider, to be sent out on
 * the whatsapp account it is linked to.
 *
 * A delivery also carries `contactId` and `userId` (the GHL user who sent it,
 * absent when a workflow did). Neither names anything on this side — the
 * destination is the phone, and the attribution the bridge stores is the
 * location — so both are left to serde's unknown fields.
 */
export type GhlDeliveryPayload = {
  locationId: string,
  /**
   * GoHighLevel's id for the message, and the seed of the idempotency keys
   * that make its retries harmless.
   */
  messageId: string,
  /**
   * The provider module the message rode; only `SMS` reaches whatsapp.
   */
  type: string,
  /**
   * The destination in `+`-prefixed E.164 — the shape a conversation opens
   * from.
   */
  phone: string | null,
  message: string | null,
  /**
   * Attachment urls, sent as their own messages after the text.
   */
  attachments: Array<string>,
};
