// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

/**
 * Channel-tagged link target — a GHL send names a bare phone number, so only
 * the whatsapp flavor that can open a conversation from one can back a
 * location; no other channel's shape deserializes.
 */
export type LinkGhlRequest = {
  "channel": "whatsapp_native",
  /**
   * The whatsapp_native account to bridge — same group as the location.
   */
  target_account_uid: Uid,
};
