// This file was generated by tapir. Do not edit this file manually.
import type { Name } from "../primitives/Name";

/**
 * The contact tag the bridge adds when a human answers; `None` turns the
 * handoff off.
 */
export type SetGhlHandoffTagRequest = {
  tag: Name | null,
};
