// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../types/Channel";
import type { Number0_3600000 } from "../primitives/Number0_3600000";
import type { Number0_600000 } from "../primitives/Number0_600000";
import type { Number1_100000 } from "../primitives/Number1_100000";

/**
 * Outbound send pacing for one channel. Every send on the channel waits a
 * random delay in `[min_delay_ms, max_delay_ms]` behind the previous one, and
 * after every `batch_size` sends the queue pauses `batch_pause_ms`.
 *
 * Randomized (never fixed) spacing is the point: mechanically even intervals
 * are themselves an automation signal on the unofficial WhatsApp channels.
 * `batch_size` and `batch_pause_ms` are set together or not at all.
 */
export type CreateChannelPacingRequest = {
  /**
   * The channel this rule paces. One rule per channel.
   */
  channel: Channel,
  min_delay_ms: Number0_600000,
  max_delay_ms: Number0_600000,
  /**
   * Sends per batch before the long pause; omit for no batch pause.
   */
  batch_size: Number1_100000 | null,
  /**
   * Pause after each batch; `0` with no `batch_size` means no batch pause.
   */
  batch_pause_ms: Number0_3600000,
};
