// This file was generated by tapir. Do not edit this file manually.
import type { RateLimitRuleKind } from "../domain/RateLimitRuleKind";
import type { RateLimitScope } from "../domain/RateLimitScope";

export type CreateRateLimitRuleRequest = {
  /**
   * The tier the rule sits in. `shared`, `global` and `override` need
   * platform standing; `own` needs `CreateRateLimits` in that group, and the
   * rule must stay within the ceiling that applies to the group (its
   * override, else the global default).
   */
  scope: RateLimitScope,
  /**
   * Target and budget. Only targets whose caller belongs to a group accept a
   * group tier; only request budgets (not pacing) accept `shared`, and email
   * dispatch accepts nothing else.
   */
  rule: RateLimitRuleKind,
};
