// This file was generated by tapir. Do not edit this file manually.
import type { RateLimitRuleKind } from "../types/RateLimitRuleKind";

export type CreateRateLimitRuleRequest = {
  rule: RateLimitRuleKind,
};
