// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_3600 } from "../primitives/Number1_3600";
import type { RateLimitAction } from "../types/RateLimitAction";

export type CreateActionRateLimitRequest = {
  action: RateLimitAction,
  max_requests: Number1_100000,
  window_seconds: Number1_3600,
};
