// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type ListRateLimitRulesQuery = {
  /**
   * Narrow to the rules that reach one group: the shared buckets, the
   * global defaults and that group's override and own tiers. Without it, platform staff get every
   * rule and everyone else the rules reaching the groups where they may view
   * limits.
   */
  group_uid: Uid | null,
};
