// This file was generated by tapir. Do not edit this file manually.
import type { RateLimitBucket } from "../domain/RateLimitBucket";
import type { RateLimitRuleKind } from "../domain/RateLimitRuleKind";
import type { RateLimitScope } from "../domain/RateLimitScope";
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

/**
 * One rule as the API shows it: the row plus what its buckets stand for,
 * so a consumer never has to derive that from tier and target.
 */
export type RateLimitRuleResponse = {
  uid: Uid,
  scope: RateLimitScope,
  rule: RateLimitRuleKind,
  /**
   * What the rule counts against, one counter per distinct value of each.
   * An attempt draws from every bucket listed that applies to it and is
   * refused when any runs dry.
   */
  buckets: Array<RateLimitBucket>,
  created_at: Timestamp,
  updated_at: Timestamp,
};
