// This file was generated by tapir. Do not edit this file manually.
import type { RateLimitRuleKind } from "../domain/RateLimitRuleKind";

export type UpdateRateLimitRuleRequest = {
  /**
   * Replacement rule payload — target *and* budget, so it is sent whole
   * rather than as a field mask. Must keep the same target (`kind` plus its
   * identity fields); only the budget may change. The tier is immutable.
   */
  rule: RateLimitRuleKind,
};
