// This file was generated by tapir. Do not edit this file manually.
import type { Number0_3600000 } from "../primitives/Number0_3600000";
import type { Number0_600000 } from "../primitives/Number0_600000";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { OptionalUpdate } from "../axumy/OptionalUpdate";

export type UpdateChannelPacingRequest = {
  min_delay_ms: OptionalUpdate<Number0_600000>,
  max_delay_ms: OptionalUpdate<Number0_600000>,
  batch_size: OptionalUpdate<Number1_100000 | null>,
  batch_pause_ms: OptionalUpdate<Number0_3600000>,
};
