// This file was generated by tapir. Do not edit this file manually.
import type { Number1024_107374182400 } from "../primitives/Number1024_107374182400";
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_3600 } from "../primitives/Number1_3600";
import type { OptionalUpdate } from "../axumy/OptionalUpdate";

export type UpdateHttpRateLimitRequest = {
  max_requests: OptionalUpdate<Number1_100000>,
  max_bytes_in: OptionalUpdate<Number1024_107374182400 | null>,
  max_bytes_out: OptionalUpdate<Number1024_107374182400 | null>,
  window_seconds: OptionalUpdate<Number1_3600>,
};
