// This file was generated by tapir. Do not edit this file manually.
import type { Number1_100000 } from "../primitives/Number1_100000";
import type { Number1_3600 } from "../primitives/Number1_3600";
import type { OptionalUpdate } from "../axumy/OptionalUpdate";

export type UpdateActionRateLimitRequest = {
  max_requests: OptionalUpdate<Number1_100000>,
  window_seconds: OptionalUpdate<Number1_3600>,
};
