// This file was generated by tapir. Do not edit this file manually.
import type { PulseDiskInventoryRow } from "../domain/PulseDiskInventoryRow";
import type { PulseGpuInventoryRow } from "../domain/PulseGpuInventoryRow";
import type { PulseNetworkInventoryRow } from "../domain/PulseNetworkInventoryRow";

export type PulseInventoryResponse = {
  disks: Array<PulseDiskInventoryRow>,
  networks: Array<PulseNetworkInventoryRow>,
  gpus: Array<PulseGpuInventoryRow>,
};
