// This file was generated by tapir. Do not edit this file manually.
import type { PulseDiskInventoryRow } from "../database/PulseDiskInventoryRow";
import type { PulseGpuInventoryRow } from "../database/PulseGpuInventoryRow";
import type { PulseNetworkInventoryRow } from "../database/PulseNetworkInventoryRow";

export type PulseInventoryResponse = {
  disks: Array<PulseDiskInventoryRow>,
  networks: Array<PulseNetworkInventoryRow>,
  gpus: Array<PulseGpuInventoryRow>,
};
