// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";

export type PulseHistoryQuery = {
  since: Timestamp,
  until: Timestamp,
};
