// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ApiKey } from "../../types/database/ApiKey";
import type { CreateApiKeyRequest } from "../../types/api_key/CreateApiKeyRequest";
import type { CreateApiKeyResponse } from "../../types/api_key/CreateApiKeyResponse";
import type { ListApiKeysQuery } from "../../types/api_key/ListApiKeysQuery";
import type { RotateApiKeyResponse } from "../../types/api_key/RotateApiKeyResponse";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateApiKeyPermissionsRequest } from "../../types/api_key/UpdateApiKeyPermissionsRequest";
import type { UpdateApiKeyRequest } from "../../types/api_key/UpdateApiKeyRequest";

export const apiKey = {
  /**
   * Count API keys, optionally filtered by group.
   *
   * Requires `ViewApiKeys`; the count covers only keys of groups where the caller holds it, and platform keys only for platform staff.
   */
  count: Tapi.get<{ query: ListApiKeysQuery; response: number }>()({
    endpoint: "/api-key/count",
  }),
  /**
   * Create an API key bound to a group or to the platform. A platform key (no
   * group) automatically carries `operate_platform_scope`; a group-bound key may
   * never carry it. Every granted permission must be one the caller itself holds
   * in the key's scope, and must bring along whatever that permission requires.
   *
   * Requires `CreateApiKeys` and `GrantApiKeyPermissions` in the named group, or `OperatePlatformScope` plus both when no group is named.
   */
  create: Tapi.post<{ body: CreateApiKeyRequest; response: CreateApiKeyResponse }>()({
    endpoint: "/api-key",
  }),
  /**
   * Fetch a single API key by uid.
   *
   * Requires `ViewApiKeys` in the key's group, or `OperatePlatformScope` plus `ViewApiKeys` for a platform key.
   */
  get: Tapi.get<{ path: { api_key_uid: Uid }; response: ApiKey }>()({
    endpoint: "/api-key/:api_key_uid",
  }),
  /**
   * List API keys, optionally filtered by group.
   *
   * Requires `ViewApiKeys`; the list covers only keys of groups where the caller holds it, and platform keys only for platform staff.
   */
  list: Tapi.get<{ query: ListApiKeysQuery; response: Array<ApiKey> }>()({
    endpoint: "/api-key",
  }),
  /**
   * Revoke an API key, permanently disabling it.
   *
   * Requires `RevokeApiKeys` in the key's group, or `OperatePlatformScope` plus `RevokeApiKeys` for a platform key.
   */
  revoke: Tapi.post<{ path: { api_key_uid: Uid }; response: null }>()({
    endpoint: "/api-key/:api_key_uid/revoke",
  }),
  /**
   * Rotate an API key's secret, returning the new key.
   *
   * Requires `RotateApiKeys` in the key's group, or `OperatePlatformScope` plus `RotateApiKeys` for a platform key.
   */
  rotate: Tapi.post<{ path: { api_key_uid: Uid }; response: RotateApiKeyResponse }>()({
    endpoint: "/api-key/:api_key_uid/rotate",
  }),
  /**
   * Update an API key's name or enabled flag.
   *
   * Requires `UpdateApiKeys` in the key's group, or `OperatePlatformScope` plus `UpdateApiKeys` for a platform key.
   */
  update: Tapi.put<{ path: { api_key_uid: Uid }; body: UpdateApiKeyRequest; response: null }>()({
    endpoint: "/api-key/:api_key_uid",
  }),
  /**
   * Replace the granted permission set of an API key. `operate_platform_scope`
   * stays bound to the key's group binding and cannot be granted to a group key;
   * every other granted permission must be one the caller itself holds in the
   * key's scope, and must bring along whatever that permission requires.
   *
   * Requires `GrantApiKeyPermissions` in the key's group, or `OperatePlatformScope` plus `GrantApiKeyPermissions` for a platform key.
   */
  updatePermissions: Tapi.put<{ path: { api_key_uid: Uid }; body: UpdateApiKeyPermissionsRequest; response: null }>()({
    endpoint: "/api-key/:api_key_uid/permission",
  }),
};
