// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";

export const test = {
  /**
   * Return a 400 — probe for the client's bad-request handling.
   *
   * Public — no authentication required.
   */
  badRequest: Tapi.get<{ response: null }>()({
    endpoint: "/test/bad-request",
  }),
  /**
   * Return a 409 — probe for the client's conflict handling.
   *
   * Public — no authentication required.
   */
  conflict: Tapi.get<{ response: null }>()({
    endpoint: "/test/conflict",
  }),
  /**
   * Return a 403 — probe for the client's permission-denied handling.
   *
   * Public — no authentication required.
   */
  forbidden: Tapi.get<{ response: null }>()({
    endpoint: "/test/forbidden",
  }),
  /**
   * Return a 500 — probe for the client's server-error handling.
   *
   * Public — no authentication required.
   */
  internal: Tapi.get<{ response: null }>()({
    endpoint: "/test/internal",
  }),
  /**
   * Return a 404 — probe for the client's missing-resource handling.
   *
   * Public — no authentication required.
   */
  notFound: Tapi.get<{ response: null }>()({
    endpoint: "/test/not-found",
  }),
  /**
   * Return a success envelope — the happy-path probe for client error handling.
   *
   * Public — no authentication required.
   */
  ok: Tapi.get<{ response: string }>()({
    endpoint: "/test/ok",
  }),
  /**
   * Panic — probe that the panic layer answers 500 instead of dropping the connection.
   *
   * Public — no authentication required.
   */
  panic: Tapi.get<{ response: null }>()({
    endpoint: "/test/panic",
  }),
  /**
   * Return a 401 — probe for the client's session-expiry handling.
   *
   * Public — no authentication required.
   */
  unauthorized: Tapi.get<{ response: null }>()({
    endpoint: "/test/unauthorized",
  }),
  /**
   * Return a 503 — probe for the client's outage handling.
   *
   * Public — no authentication required.
   */
  unavailable: Tapi.get<{ response: null }>()({
    endpoint: "/test/unavailable",
  }),
};
