// This file was generated by tapi. Do not edit manually.

import Tapi from "../../../runtime";
import type { CreateHttpRateLimitRequest } from "../../../types/rate_limit/CreateHttpRateLimitRequest";
import type { CreateHttpRateLimitResponse } from "../../../types/rate_limit/CreateHttpRateLimitResponse";
import type { HttpRateLimitRule } from "../../../types/database/HttpRateLimitRule";
import type { Uid } from "../../../types/primitives/Uid";
import type { UpdateHttpRateLimitRequest } from "../../../types/rate_limit/UpdateHttpRateLimitRequest";

export const http = {
  /**
   * Create an HTTP rate-limit rule scoped to a group or to the whole platform.
   *
   * Requires `CreateRateLimits`, which only platform staff hold; a group rule must name its group, a global or anonymous rule must not.
   */
  create: Tapi.post<{ body: CreateHttpRateLimitRequest; response: CreateHttpRateLimitResponse }>()({
    endpoint: "/rate-limit/http",
  }),
  /**
   * Delete an HTTP rate-limit rule by uid.
   *
   * Requires `DeleteRateLimits`, which only platform staff hold.
   */
  delete: Tapi.delete<{ path: { rule_uid: Uid }; response: null }>()({
    endpoint: "/rate-limit/http/:rule_uid",
  }),
  /**
   * Fetch a single HTTP rate-limit rule by uid.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { rule_uid: Uid }; response: HttpRateLimitRule }>()({
    endpoint: "/rate-limit/http/:rule_uid",
  }),
  /**
   * List all HTTP rate-limit rules.
   *
   * Requires `ViewRateLimits`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<HttpRateLimitRule> }>()({
    endpoint: "/rate-limit/http",
  }),
  /**
   * Update the limits of an existing HTTP rate-limit rule.
   *
   * Requires `UpdateRateLimits`, which only platform staff hold.
   */
  update: Tapi.put<{ path: { rule_uid: Uid }; body: UpdateHttpRateLimitRequest; response: null }>()({
    endpoint: "/rate-limit/http/:rule_uid",
  }),
};
