// This file was generated by tapir. Do not edit this file manually.
import type { CallVideoAction } from "../domain/CallVideoAction";

/**
 * Client → server control frames. Everything that decides *whether* a call
 * exists — placing, answering, refusing, ending — stays on REST, where it is
 * audited and permission-checked; this socket only carries what a call in
 * progress needs.
 */
export type CallClientMsg = {
  "type": "video",
  action: CallVideoAction,
} | {
  "type": "video_enabled",
  enabled: boolean,
} | {
  "type": "orientation",
  orientation: number,
} | {
  "type": "reaction",
  emoji: string,
};
