// This file was generated by tapir. Do not edit this file manually.
import type { Number1_200 } from "../primitives/Number1_200";

export type ConversationCallsQuery = {
  /**
   * Scrollback cursor: only calls with `id` strictly smaller are returned.
   */
  before_id: number | null,
  limit: Number1_200 | null,
};
