// This file was generated by tapir. Do not edit this file manually.

/**
 * Channel-tagged call placement — only whatsapp_native carries calls, so no
 * other channel's shape deserializes.
 */
export type PlaceCallRequest = {
  "channel": "whatsapp_native",
  /**
   * Start the call with video. An audio call can still be upgraded later,
   * over the media socket.
   */
  video: boolean,
};
