// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";
import type { UserMfaKind } from "../domain/UserMfaKind";

export type UserSessionLoginResponse = {
  "outcome": "user_session",
  token: Uid,
} | {
  "outcome": "user_mfa_required",
  mfa_token: Uid,
  factors: Array<UserMfaKind>,
} | {
  "outcome": "enrollment_required",
  enrollment_token: Uid,
};
