// This file was generated by tapir. Do not edit this file manually.
import type { Timestamp } from "../primitives/Timestamp";
import type { Uid } from "../primitives/Uid";

export type UserSessionRow = {
  uid: Uid,
  ip: string | null,
  user_agent: string | null,
  country: string | null,
  city: string | null,
  last_seen_at: Timestamp | null,
  expires_at: Timestamp,
  created_at: Timestamp,
  current: boolean,
};
