// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateUserRequest } from "../../types/user/CreateUserRequest";
import type { CreateUserResponse } from "../../types/user/CreateUserResponse";
import type { SetUserSuperAdminRequest } from "../../types/user/SetUserSuperAdminRequest";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateUserRequest } from "../../types/user/UpdateUserRequest";
import type { UpdateUserSelfRequest } from "../../types/user/UpdateUserSelfRequest";
import type { User } from "../../types/domain/User";
import type { UserChangePasswordRequest } from "../../types/user/UserChangePasswordRequest";
import type { UserSelfResponse } from "../../types/user/UserSelfResponse";

export const user = {
  /**
   * Reactivate another user, re-enabling their account.
   *
   * Requires `ActivateUsers`, which only platform staff hold.
   */
  activate: Tapi.post<{ path: { user_uid: Uid }; response: null }>()({
    endpoint: "/user/:user_uid/activate",
  }),
  /**
   * Change the authenticated user's own password and revoke their other sessions.
   *
   * Authenticated user acting on their own account.
   */
  changePassword: Tapi.put<{ body: UserChangePasswordRequest; response: null }>()({
    endpoint: "/user/me/password",
  }),
  /**
   * Count all users.
   *
   * Requires `ViewUsers`, which only platform staff hold.
   */
  count: Tapi.get<{ response: number }>()({
    endpoint: "/user/count",
  }),
  /**
   * Create a user, who starts out belonging to no group.
   *
   * Requires `ProvisionUsers`, which only platform staff hold.
   */
  create: Tapi.post<{ body: CreateUserRequest; response: CreateUserResponse }>()({
    endpoint: "/user",
  }),
  /**
   * Deactivate another user, disabling their account while preserving sessions.
   *
   * Requires `ActivateUsers`, which only platform staff hold; you cannot deactivate yourself.
   */
  deactivate: Tapi.post<{ path: { user_uid: Uid }; response: null }>()({
    endpoint: "/user/:user_uid/deactivate",
  }),
  /**
   * Delete another user.
   *
   * Requires `DeleteUsers`, which only platform staff hold; you cannot delete yourself.
   */
  delete: Tapi.delete<{ path: { user_uid: Uid }; response: null }>()({
    endpoint: "/user/:user_uid",
  }),
  /**
   * Get a single user by uid.
   *
   * Requires `ViewUsers`, which only platform staff hold.
   */
  get: Tapi.get<{ path: { user_uid: Uid }; response: User }>()({
    endpoint: "/user/:user_uid",
  }),
  /**
   * Get the authenticated user's own account, along with the permissions and memberships every gating decision reads.
   *
   * Authenticated user acting on their own account.
   */
  getSelf: Tapi.get<{ response: UserSelfResponse }>()({
    endpoint: "/user/me",
  }),
  /**
   * List all users.
   *
   * Requires `ViewUsers`, which only platform staff hold.
   */
  list: Tapi.get<{ response: Array<User> }>()({
    endpoint: "/user",
  }),
  /**
   * Grant or revoke another user's platform staff standing.
   *
   * Requires `SetSuperAdmin`, which only platform staff hold; you can never change your own flag.
   */
  setSuperAdmin: Tapi.put<{ path: { user_uid: Uid }; body: SetUserSuperAdminRequest; response: null }>()({
    endpoint: "/user/:user_uid/super-admin",
  }),
  /**
   * Update another user's profile.
   *
   * Requires `UpdateUsers`, which only platform staff hold.
   */
  update: Tapi.put<{ path: { user_uid: Uid }; body: UpdateUserRequest; response: null }>()({
    endpoint: "/user/:user_uid",
  }),
  /**
   * Update the authenticated user's own profile.
   *
   * Authenticated user acting on their own account.
   */
  updateSelf: Tapi.put<{ body: UpdateUserSelfRequest; response: null }>()({
    endpoint: "/user/me",
  }),
};
