// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { Answer } from "../../types/google/Answer";
import type { AnswerBusinessQuestionRequest } from "../../types/google_account/AnswerBusinessQuestionRequest";
import type { BusinessAccountPage } from "../../types/google/BusinessAccountPage";
import type { BusinessCallsQuery } from "../../types/google_account/BusinessCallsQuery";
import type { BusinessKeywordsQuery } from "../../types/google_account/BusinessKeywordsQuery";
import type { BusinessMenusQuery } from "../../types/google_account/BusinessMenusQuery";
import type { BusinessPerformanceQuery } from "../../types/google_account/BusinessPerformanceQuery";
import type { BusinessPerformanceResponse } from "../../types/google_account/BusinessPerformanceResponse";
import type { CallInsightsPage } from "../../types/google/CallInsightsPage";
import type { CreateBusinessMediaRequest } from "../../types/google_account/CreateBusinessMediaRequest";
import type { CreateBusinessPostRequest } from "../../types/google_account/CreateBusinessPostRequest";
import type { DeleteBusinessAnswerQuery } from "../../types/google_account/DeleteBusinessAnswerQuery";
import type { DeleteBusinessMediaQuery } from "../../types/google_account/DeleteBusinessMediaQuery";
import type { DeleteBusinessPostQuery } from "../../types/google_account/DeleteBusinessPostQuery";
import type { DeleteBusinessReplyQuery } from "../../types/google_account/DeleteBusinessReplyQuery";
import type { FoodMenus } from "../../types/google/FoodMenus";
import type { ListBusinessAccountsQuery } from "../../types/google_account/ListBusinessAccountsQuery";
import type { ListBusinessLocationsQuery } from "../../types/google_account/ListBusinessLocationsQuery";
import type { ListBusinessMediaQuery } from "../../types/google_account/ListBusinessMediaQuery";
import type { ListBusinessPostsQuery } from "../../types/google_account/ListBusinessPostsQuery";
import type { ListBusinessQuestionsQuery } from "../../types/google_account/ListBusinessQuestionsQuery";
import type { ListBusinessReviewsQuery } from "../../types/google_account/ListBusinessReviewsQuery";
import type { LocalPost } from "../../types/google/LocalPost";
import type { LocalPostPage } from "../../types/google/LocalPostPage";
import type { Location } from "../../types/google/Location";
import type { LocationPage } from "../../types/google/LocationPage";
import type { MediaItem } from "../../types/google/MediaItem";
import type { MediaPage } from "../../types/google/MediaPage";
import type { QuestionPage } from "../../types/google/QuestionPage";
import type { ReplyBusinessReviewRequest } from "../../types/google_account/ReplyBusinessReviewRequest";
import type { ReviewPage } from "../../types/google/ReviewPage";
import type { ReviewReply } from "../../types/google/ReviewReply";
import type { SearchKeywordPage } from "../../types/google/SearchKeywordPage";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateBusinessLocationRequest } from "../../types/google_account/UpdateBusinessLocationRequest";
import type { UpdateBusinessMenusRequest } from "../../types/google_account/UpdateBusinessMenusRequest";
import type { UpdateBusinessPostRequest } from "../../types/google_account/UpdateBusinessPostRequest";

export const business = {
  /**
   * Create or replace the business's answer on a question (one per account —
   * answering again overwrites).
   *
   * Requires `ManageBusiness` in the account's group.
   */
  answerQuestion: Tapi.put<{ path: { social_account_uid: Uid }; body: AnswerBusinessQuestionRequest; response: Answer }>()({
    endpoint: "/business/:social_account_uid/question/answer",
  }),
  /**
   * Call History insights for a location (answered/missed counts, hourly and
   * weekday breakdowns) — populated only where the merchant enabled Call
   * History.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  calls: Tapi.get<{ path: { social_account_uid: Uid }; query: BusinessCallsQuery; response: CallInsightsPage }>()({
    endpoint: "/business/:social_account_uid/call",
  }),
  /**
   * Attach a photo/video to the profile from a publicly fetchable URL, placed
   * under the chosen category (`COVER`, `LOGO`, `INTERIOR`, `ADDITIONAL`, …).
   *
   * Requires `ManageBusiness` in the account's group.
   */
  createMedia: Tapi.post<{ path: { social_account_uid: Uid }; body: CreateBusinessMediaRequest; response: MediaItem }>()({
    endpoint: "/business/:social_account_uid/media",
  }),
  /**
   * Publish a local post on a location — `STANDARD`, `EVENT`, `OFFER` or
   * `ALERT`, optionally with a call-to-action button and photos (public URLs).
   *
   * Requires `ManageBusiness` in the account's group.
   */
  createPost: Tapi.post<{ path: { social_account_uid: Uid }; body: CreateBusinessPostRequest; response: LocalPost }>()({
    endpoint: "/business/:social_account_uid/post",
  }),
  /**
   * Remove the business's answer from a question.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  deleteAnswer: Tapi.delete<{ path: { social_account_uid: Uid }; query: DeleteBusinessAnswerQuery; response: null }>()({
    endpoint: "/business/:social_account_uid/question/answer",
  }),
  /**
   * Remove a media item from the profile.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  deleteMedia: Tapi.delete<{ path: { social_account_uid: Uid }; query: DeleteBusinessMediaQuery; response: null }>()({
    endpoint: "/business/:social_account_uid/media",
  }),
  /**
   * Delete a local post.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  deletePost: Tapi.delete<{ path: { social_account_uid: Uid }; query: DeleteBusinessPostQuery; response: null }>()({
    endpoint: "/business/:social_account_uid/post",
  }),
  /**
   * Remove the merchant reply from a review.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  deleteReviewReply: Tapi.delete<{ path: { social_account_uid: Uid }; query: DeleteBusinessReplyQuery; response: null }>()({
    endpoint: "/business/:social_account_uid/review/reply",
  }),
  /**
   * The location's structured food menus (food businesses only —
   * `metadata.can_have_food_menus` on the location says whether it applies).
   *
   * Requires `ViewBusiness` in the account's group.
   */
  getMenus: Tapi.get<{ path: { social_account_uid: Uid }; query: BusinessMenusQuery; response: FoodMenus }>()({
    endpoint: "/business/:social_account_uid/menu",
  }),
  /**
   * Monthly search keywords that surfaced the profile, by impression volume.
   * Low-volume keywords report a threshold floor instead of an exact value.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  keywords: Tapi.get<{ path: { social_account_uid: Uid }; query: BusinessKeywordsQuery; response: SearchKeywordPage }>()({
    endpoint: "/business/:social_account_uid/keyword",
  }),
  /**
   * List the Business Profile accounts the connected Google user manages —
   * the roots the other business endpoints' resource names hang under.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listAccounts: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessAccountsQuery; response: BusinessAccountPage }>()({
    endpoint: "/business/:social_account_uid/account",
  }),
  /**
   * List an account's business locations with their info (title, address,
   * phones, hours, categories, status, links).
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listLocations: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessLocationsQuery; response: LocationPage }>()({
    endpoint: "/business/:social_account_uid/location",
  }),
  /**
   * List a location's profile media (photos/videos) with view counts.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listMedia: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessMediaQuery; response: MediaPage }>()({
    endpoint: "/business/:social_account_uid/media",
  }),
  /**
   * List a location's local posts, newest first.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listPosts: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessPostsQuery; response: LocalPostPage }>()({
    endpoint: "/business/:social_account_uid/post",
  }),
  /**
   * List the questions customers asked on a location, each with its top
   * answers.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listQuestions: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessQuestionsQuery; response: QuestionPage }>()({
    endpoint: "/business/:social_account_uid/question",
  }),
  /**
   * List a location's reviews (newest update first by default), with the
   * running average and total.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  listReviews: Tapi.get<{ path: { social_account_uid: Uid }; query: ListBusinessReviewsQuery; response: ReviewPage }>()({
    endpoint: "/business/:social_account_uid/review",
  }),
  /**
   * Daily performance series for a location — impressions by surface,
   * conversations, direction requests, call and website clicks — over an
   * inclusive date range.
   *
   * Requires `ViewBusiness` in the account's group.
   */
  performance: Tapi.get<{ path: { social_account_uid: Uid }; query: BusinessPerformanceQuery; response: BusinessPerformanceResponse }>()({
    endpoint: "/business/:social_account_uid/performance",
  }),
  /**
   * Create or replace the public merchant reply on a review.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  replyReview: Tapi.put<{ path: { social_account_uid: Uid }; body: ReplyBusinessReviewRequest; response: ReviewReply }>()({
    endpoint: "/business/:social_account_uid/review/reply",
  }),
  /**
   * Update a location's business info: exactly the masked fields are written.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  updateLocation: Tapi.patch<{ path: { social_account_uid: Uid }; body: UpdateBusinessLocationRequest; response: Location }>()({
    endpoint: "/business/:social_account_uid/location",
  }),
  /**
   * Replace the location's food menus wholesale.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  updateMenus: Tapi.put<{ path: { social_account_uid: Uid }; body: UpdateBusinessMenusRequest; response: FoodMenus }>()({
    endpoint: "/business/:social_account_uid/menu",
  }),
  /**
   * Update a local post: exactly the masked fields are written.
   *
   * Requires `ManageBusiness` in the account's group.
   */
  updatePost: Tapi.patch<{ path: { social_account_uid: Uid }; body: UpdateBusinessPostRequest; response: LocalPost }>()({
    endpoint: "/business/:social_account_uid/post",
  }),
};
