// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { BackfillRequest } from "../../types/message/BackfillRequest";
import type { BackfillResponse } from "../../types/message/BackfillResponse";
import type { EditMessageRequest } from "../../types/message/EditMessageRequest";
import type { ListMessagesQuery } from "../../types/message/ListMessagesQuery";
import type { Message } from "../../types/database/Message";
import type { MessageWithContext } from "../../types/message/MessageWithContext";
import type { ReactToMessageRequest } from "../../types/message/ReactToMessageRequest";
import type { SendMessageRequest } from "../../types/message/SendMessageRequest";
import type { Uid } from "../../types/primitives/Uid";

export const message = {
  /**
   * Import conversation history from Meta's Conversations API for an account
   * — DMs that predate the account's connection (facebook/instagram only;
   * whatsapp exposes no history). Runs only when explicitly invoked;
   * already-imported messages dedup by platform mid.
   *
   * Requires `ManageMessages` in the account's group.
   */
  backfill: Tapi.post<{ body: BackfillRequest; response: BackfillResponse }>()({
    endpoint: "/message/backfill",
  }),
  /**
   * Cancel a queued (`pending`) message before it reaches the platform, and
   * with it **every message queued after it in the same conversation** —
   * cancels cascade forward because a conversation's queued messages are one
   * ordered thought: dropping one mid-sequence would deliver the rest out of
   * context. Given messages 1, 2 and 3 queued in one conversation, canceling 2
   * also cancels 3, and canceling 1 cancels 1, 2 and 3. Messages queued for
   * *other* conversations on the same account are never touched and keep
   * sending.
   *
   * Only a message still waiting in the queue can be canceled: once it has been
   * handed to the platform there is nothing left to stop, and the call fails
   * with "mensagem não está na fila de envio". Every send passes through
   * `pending`, but without a pacing rule on the channel the queue drains
   * immediately — the window to cancel is real only while a rule holds sends
   * back.
   *
   * Returns the canceled message uids in send order, the named message first.
   * Each also emits a `message_canceled` event (`cascaded` false for the named
   * one, true for the messages that went with it).
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  cancel: Tapi.post<{ path: { conversation_uid: Uid; message_uid: Uid }; response: Array<Uid> }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/cancel",
  }),
  /**
   * Revoke an own sent message for everyone ("apagar para todos") —
   * whatsapp_stevo and whatsapp_native only; the row stays with `deleted_at`
   * set.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  delete: Tapi.delete<{ path: { conversation_uid: Uid; message_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid",
  }),
  /**
   * Edit an own sent message's text (or media caption) on the platform —
   * whatsapp_stevo and whatsapp_native only; the platform enforces its
   * ~15 minute edit window.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  edit: Tapi.put<{ path: { conversation_uid: Uid; message_uid: Uid }; body: EditMessageRequest; response: Message }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid",
  }),
  /**
   * Poll the unified message feed across channels: messages with `id` greater
   * than `since_id`, oldest first, optionally filtered by group or account.
   *
   * Requires `ViewMessages`; the feed covers only messages of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListMessagesQuery; response: Array<MessageWithContext> }>()({
    endpoint: "/message",
  }),
  /**
   * React to a message through the platform. The payload is channel-tagged
   * and must match the message's channel; Messenger has no reaction API and
   * no payload variant.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  react: Tapi.post<{ path: { conversation_uid: Uid; message_uid: Uid }; body: ReactToMessageRequest; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/reaction",
  }),
  /**
   * Send a message into a conversation. The payload is channel-tagged and
   * must match the conversation's channel — each variant accepts exactly the
   * fields and content kinds its channel can deliver. Official WhatsApp
   * free-form sends require an inbound message within 24h; outside the window
   * only `template` content passes (the unofficial flavors have no window).
   *
   * Sends are always queued: the message comes back as `pending`, nothing has
   * reached the platform yet, and a `message_queued` event fires. A per-account
   * drainer dispatches it in order — immediately, or spaced by the channel's
   * send-pacing rule when one exists — and only then does it become `sent`
   * (`message_sent`) or `failed` (`message_failed`). A pending message can be
   * called off with `message.cancel` until it goes out.
   *
   * An `idempotency_key` makes the send retry-safe: the same key never
   * duplicates history — a failed row is re-queued in place (same `uid`,
   * re-announced via `message_queued`), any other row is returned as-is
   * without a new send.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  send: Tapi.post<{ body: SendMessageRequest; response: MessageWithContext }>()({
    endpoint: "/message",
  }),
  /**
   * Remove the account's reaction from a message (Instagram and the WhatsApp
   * flavors — Messenger has no reaction API).
   *
   * Requires `SendMessages` in the conversation's group.
   */
  unreact: Tapi.delete<{ path: { conversation_uid: Uid; message_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/reaction",
  }),
};
