// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { BackfillRequest } from "../../types/message/BackfillRequest";
import type { BackfillResponse } from "../../types/message/BackfillResponse";
import type { EditMessageRequest } from "../../types/message/EditMessageRequest";
import type { ForwardMessageRequest } from "../../types/message/ForwardMessageRequest";
import type { ForwardOutcome } from "../../types/message/ForwardOutcome";
import type { ListMessagesQuery } from "../../types/message/ListMessagesQuery";
import type { Message } from "../../types/domain/Message";
import type { MessageWithContext } from "../../types/domain/MessageWithContext";
import type { ReactToMessageRequest } from "../../types/message/ReactToMessageRequest";
import type { SendMessageRequest } from "../../types/message/SendMessageRequest";
import type { Uid } from "../../types/primitives/Uid";

export const message = {
  /**
   * Import conversation history for an account — DMs that predate the
   * account's connection: Meta's Conversations API for facebook and
   * instagram, the gateway's replayed history for facebook_alt and
   * instagram_alt. The payload is channel-tagged and must match the
   * account's channel; no other channel's shape deserializes. Runs only when
   * explicitly invoked; already-imported messages dedup by platform mid.
   *
   * Requires `ManageMessages` in the account's group.
   */
  backfill: Tapi.post<{ body: BackfillRequest; response: BackfillResponse }>()({
    endpoint: "/message/backfill",
  }),
  /**
   * Cancel a queued (`pending`) message before it reaches the platform, and
   * with it **every message queued after it in the same conversation** —
   * cancels cascade forward because a conversation's queued messages are one
   * ordered thought: dropping one mid-sequence would deliver the rest out of
   * context. Given messages 1, 2 and 3 queued in one conversation, canceling 2
   * also cancels 3, and canceling 1 cancels 1, 2 and 3. Messages queued for
   * *other* conversations on the same account are never touched and keep
   * sending.
   *
   * Only a message still waiting in the queue can be canceled: once it has been
   * handed to the platform there is nothing left to stop, and the call fails
   * with "mensagem não está na fila de envio". Every send passes through
   * `pending`, but without a pacing rule on the channel the queue drains
   * immediately — the window to cancel is real only while a rule holds sends
   * back.
   *
   * Returns the canceled message uids in send order, the named message first.
   * Each also emits a `message_canceled` event (`cascaded` false for the named
   * one, true for the messages that went with it).
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  cancel: Tapi.post<{ path: { conversation_uid: Uid; message_uid: Uid }; response: Array<Uid> }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/cancel",
  }),
  /**
   * Revoke an own sent message for everyone ("apagar para todos") —
   * whatsapp_native only; the row stays with `deleted_at` set.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  delete: Tapi.delete<{ path: { conversation_uid: Uid; message_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid",
  }),
  /**
   * Edit an own sent message's text (or media caption) on the platform. The
   * payload is channel-tagged and must match the message's channel — only
   * whatsapp_native exposes an edit call, so no other channel's shape
   * deserializes; the platform enforces its ~15 minute edit window.
   *
   * Requires `ManageMessages` in the conversation's group.
   */
  edit: Tapi.put<{ path: { conversation_uid: Uid; message_uid: Uid }; body: EditMessageRequest; response: Message }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid",
  }),
  /**
   * Forward a message into other conversations. Each target re-sends the
   * stored content as a queued message of its own, marked as forwarded: native
   * whatsapp shows the recipient the forwarded label, the other channels carry
   * no such marker and read it as a message the account just wrote.
   *
   * The content is re-shaped per target channel, so a forward crosses channels
   * (a whatsapp photo into an instagram thread); a gif lands as a plain video
   * anywhere but native whatsapp. Targets are answered one by one and
   * independently: a target the caller cannot send in, whose channel cannot
   * express the content, or whose 24h window has lapsed comes back `rejected`
   * while the rest still queue. At most five targets per call.
   *
   * Requires `ViewMessages` in the source conversation's group, and
   * `SendMessages` in each target's — a target failing that is `rejected`, not
   * an error.
   */
  forward: Tapi.post<{ path: { conversation_uid: Uid; message_uid: Uid }; body: ForwardMessageRequest; response: Array<ForwardOutcome> }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/forward",
  }),
  /**
   * Poll the unified message feed across channels: messages with `id` greater
   * than `since_id`, oldest first, optionally filtered by groups or accounts.
   * `uids` instead returns exactly those messages (≤200, order unspecified),
   * for resolving rows the caller already holds by uid; not combinable with
   * `since_id`.
   *
   * Requires `ViewMessages`; the feed covers only messages of groups where the caller holds it.
   */
  list: Tapi.get<{ query: ListMessagesQuery; response: Array<MessageWithContext> }>()({
    endpoint: "/message",
  }),
  /**
   * React to a message through the platform. The payload is channel-tagged
   * and must match the message's channel; Instagram takes Meta's reaction
   * name, every other channel the emoji itself.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  react: Tapi.post<{ path: { conversation_uid: Uid; message_uid: Uid }; body: ReactToMessageRequest; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/reaction",
  }),
  /**
   * Send a message into a conversation. The payload is channel-tagged and
   * must match the conversation's channel — each variant accepts exactly the
   * fields and content kinds its channel can deliver. Free-form sends must fall
   * inside the channel's response window (`GET /channel`): an inbound message
   * within the window's hours, or past that only what the window lifts by — a
   * `template` on official and alt WhatsApp, a `tag` on a channel whose window
   * honors it. Beyond that the send is refused as `window_expired`; a `tag` the
   * channel does not honor is refused (400) before anything reaches the
   * platform. The native flavor has no window.
   *
   * Sends are always queued: the message comes back as `pending`, nothing has
   * reached the platform yet, and a `message_queued` event fires. A per-account
   * drainer dispatches it in order — immediately, or spaced by the channel's
   * send-pacing rule when one exists — and only then does it become `sent`
   * (`message_sent`) or `failed` (`message_failed`). A pending message can be
   * called off with `message.cancel` until it goes out.
   *
   * An `idempotency_key` makes the send retry-safe: the same key never
   * duplicates history — a failed row is re-queued in place (same `uid`,
   * re-announced via `message_queued`), any other row is returned as-is
   * without a new send.
   *
   * Requires `SendMessages` in the conversation's group.
   */
  send: Tapi.post<{ path: { conversation_uid: Uid }; body: SendMessageRequest; response: MessageWithContext }>()({
    endpoint: "/conversation/:conversation_uid/message",
  }),
  /**
   * Remove the account's reaction from a message (Instagram, the WhatsApp
   * flavors and the alt channels — Messenger has no reaction API).
   *
   * Requires `SendMessages` in the conversation's group.
   */
  unreact: Tapi.delete<{ path: { conversation_uid: Uid; message_uid: Uid }; response: null }>()({
    endpoint: "/conversation/:conversation_uid/message/:message_uid/reaction",
  }),
};
