// This file was generated by tapir. Do not edit this file manually.
import type { ResumeCursor } from "./ResumeCursor";
import type { RosterFilter } from "./RosterFilter";
import type { Uid } from "../primitives/Uid";

/**
 * Client → server protocol frames.
 */
export type ClientMsg = {
  "type": "hello",
  resume: ResumeCursor | null,
  roster: RosterFilter | null,
} | {
  "type": "set_roster",
  roster: RosterFilter,
} | {
  "type": "set_focus",
  conversation_uids: Array<Uid>,
};
