// This file was generated by tapir. Do not edit this file manually.

/**
 * Where a previous connection stopped: the `epoch` from its `welcome` and
 * the `seq` of the last processed `event` frame.
 */
export type ResumeCursor = {
  epoch: string,
  seq: number,
};
