// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../domain/Channel";
import type { EventKind } from "../domain/EventKind";
import type { Uid } from "../primitives/Uid";

/**
 * The connection's base subscription. Every list is OR within itself, AND
 * across fields; omitted lists don't filter. The caller's permissions and
 * group scope always apply on top.
 */
export type RosterFilter = {
  group_uids: Array<Uid> | null,
  social_account_uids: Array<Uid> | null,
  channels: Array<Channel> | null,
  events: Array<EventKind> | null,
};
