// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../types/Channel";
import type { Uid } from "../primitives/Uid";

export type SetWebhookRequest = {
  /**
   * Required for users and platform keys; group-bound keys imply their group.
   */
  group_uid: Uid | null,
  url: string,
  /**
   * Event kinds (and/or family aliases: `message`, `presence`, `comment`,
   * `mention`, `post`, `conversation`, `account`, `review`) delivered to this
   * subscription; omit for everything. Presence kinds are accepted but never
   * delivered here — they are live-stream-only by construction, so a webhook
   * filtered to presence alone receives nothing.
   */
  events: Array<string> | null,
  /**
   * Channels delivered to this subscription; omit for everything.
   */
  channels: Array<Channel> | null,
};
