// This file was generated by tapir. Do not edit this file manually.
import type { Channel } from "../domain/Channel";
import type { EventKind } from "../domain/EventKind";
import type { Uid } from "../primitives/Uid";

export type SetWebhookRequest = {
  /**
   * Required for users and platform keys; group-bound keys imply their group.
   */
  group_uid: Uid | null,
  url: string,
  /**
   * Event kinds delivered to this subscription; omit for everything. The
   * live-only kinds (the presence kinds), which reach only the event socket,
   * are refused here.
   */
  events: Array<EventKind> | null,
  /**
   * Channels delivered to this subscription; omit for everything.
   */
  channels: Array<Channel> | null,
};
