// This file was generated by tapir. Do not edit this file manually.
import type { Uid } from "../primitives/Uid";

export type SetWebhookResponse = {
  uid: Uid,
  /**
   * HMAC secret for `X-Integro-Signature` — shown only here; rotated on every
   * reconfiguration.
   */
  secret: string,
};
