// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { UploadMediaForm } from "../../types/media/UploadMediaForm";
import type { UploadMediaResponse } from "../../types/media/UploadMediaResponse";

export const media = {
  /**
   * Serve a hub-hosted media file. The uid may carry a cosmetic extension
   * suffix (`{uid}.m4a`) — generated URLs include one as a format signal for
   * external fetchers; it is stripped before lookup. A uid nothing names any
   * more answers 404: the file went with its last referrer.
   *
   * Public — no authentication required; the unguessable uid is the capability.
   */
  serve: Tapi.get<{ path: { media_uid: string }; response: Blob }>()({
    endpoint: "/media/:media_uid",
  }),
  /**
   * Upload a media file to the hub; the returned public URL can be used in any
   * message or post payload (Meta fetches it from the hub). Bytes the hub
   * already holds come back as the existing file — same uid, same URL. The
   * URL stays valid while a message, post or campaign template names it, and
   * for 24 hours after this upload otherwise; a third party handed the URL
   * copies what it needs while it resolves.
   *
   * Requires `UploadMedia` in the target group; group-scoped API keys upload into their own group, others must name it. A human caller is additionally rejected when they trip the per-user file-upload throttle.
   */
  upload: Tapi.post<{ formData: UploadMediaForm; response: UploadMediaResponse }>()({
    endpoint: "/media",
  }),
};
