// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { UploadMediaForm } from "../../types/media/UploadMediaForm";
import type { UploadMediaResponse } from "../../types/media/UploadMediaResponse";

export const media = {
  /**
   * Delete a hub-hosted media file. The uid may carry the same cosmetic
   * extension suffix the serve route accepts, so the URL handed back by upload
   * can be deleted verbatim. Platform posts/messages already published with it
   * keep working (Meta copies media on ingestion), but new sends referencing
   * the URL will fail.
   *
   * Requires `DeleteMedia` in the media's group.
   */
  delete: Tapi.delete<{ path: { media_uid: string }; response: null }>()({
    endpoint: "/media/:media_uid",
  }),
  /**
   * Public — no authentication required; the unguessable uid is the capability.
   */
  serve: Tapi.get<{ path: { media_uid: string }; response: Blob }>()({
    endpoint: "/media/:media_uid",
  }),
  /**
   * Upload a media file to the hub; the returned public URL can be used in any
   * message or post payload (Meta fetches it from the hub).
   *
   * Requires `UploadMedia` in the target group; group-scoped API keys upload into their own group, others must name it. A human caller is additionally rejected when they trip the per-user file-upload throttle.
   */
  upload: Tapi.post<{ formData: UploadMediaForm; response: UploadMediaResponse }>()({
    endpoint: "/media",
  }),
};
