// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { CreateGroupForm } from "../../types/group/CreateGroupForm";
import type { CreateGroupResponse } from "../../types/group/CreateGroupResponse";
import type { GroupQuery } from "../../types/group/GroupQuery";
import type { GroupResponse } from "../../types/group/GroupResponse";
import type { SetGroupEnabledRequest } from "../../types/group/SetGroupEnabledRequest";
import type { SetGroupLogoForm } from "../../types/group/SetGroupLogoForm";
import type { Uid } from "../../types/primitives/Uid";
import type { UpdateGroupRequest } from "../../types/group/UpdateGroupRequest";

export const group = {
  /**
   * Count groups.
   *
   * Requires `ViewGroups`; the count covers only groups where the caller holds it.
   */
  count: Tapi.get<{ response: number }>()({
    endpoint: "/group/count",
  }),
  /**
   * Create a group, optionally with a logo image.
   *
   * Requires `CreateGroups`, which is only ever held platform-wide — no group exists yet to scope it to. Rejected — when a logo is attached — when the caller trips the per-user file-upload throttle.
   */
  create: Tapi.post<{ formData: CreateGroupForm; response: CreateGroupResponse }>()({
    endpoint: "/group",
  }),
  /**
   * Delete a group that has no API keys and no social accounts.
   *
   * Requires `DeleteGroups` in the group itself; fails while the group still has API keys or social accounts.
   */
  delete: Tapi.delete<{ path: { group_uid: Uid }; response: null }>()({
    endpoint: "/group/:group_uid",
  }),
  /**
   * Fetch a single group, optionally enriched with per-group counts.
   *
   * Requires `ViewGroups` in the group itself; each count is filled only when the caller also holds that count's own permission there — `ViewApiKeys` for `api_key_count`, `ViewMembers` for `member_count`, `ViewSocialAccounts` for `social_account_count` — and is `null` otherwise.
   */
  get: Tapi.get<{ path: { group_uid: Uid }; query: GroupQuery; response: GroupResponse }>()({
    endpoint: "/group/:group_uid",
  }),
  /**
   * Serve a group's logo image.
   *
   * Requires `ViewGroups` in the group itself.
   */
  getLogo: Tapi.get<{ path: { group_uid: Uid }; response: Blob }>()({
    endpoint: "/group/:group_uid/logo",
  }),
  /**
   * List groups, optionally enriched with per-group counts.
   *
   * Requires `ViewGroups`; the list covers only groups where the caller holds it, and each count is filled only for those where it also holds that count's own permission — `ViewApiKeys` for `api_key_count`, `ViewMembers` for `member_count`, `ViewSocialAccounts` for `social_account_count` — `null` everywhere else.
   */
  list: Tapi.get<{ query: GroupQuery; response: Array<GroupResponse> }>()({
    endpoint: "/group",
  }),
  /**
   * Remove a group's logo image.
   *
   * Requires `UpdateGroups` in the group itself.
   */
  removeLogo: Tapi.delete<{ path: { group_uid: Uid }; response: null }>()({
    endpoint: "/group/:group_uid/logo",
  }),
  /**
   * Enable or disable a group; API keys bound to a disabled group are rejected.
   *
   * Requires `ToggleGroupEnabled` in the group itself.
   */
  setEnabled: Tapi.put<{ path: { group_uid: Uid }; body: SetGroupEnabledRequest; response: null }>()({
    endpoint: "/group/:group_uid/enabled",
  }),
  /**
   * Upload or replace a group's logo image.
   *
   * Requires `UpdateGroups` in the group itself, and is rejected when the caller trips the per-user file-upload throttle.
   */
  setLogo: Tapi.post<{ path: { group_uid: Uid }; formData: SetGroupLogoForm; response: null }>()({
    endpoint: "/group/:group_uid/logo",
  }),
  /**
   * Update a group's mutable fields such as its name.
   *
   * Requires `UpdateGroups` in the group itself.
   */
  update: Tapi.put<{ path: { group_uid: Uid }; body: UpdateGroupRequest; response: null }>()({
    endpoint: "/group/:group_uid",
  }),
};
