// This file was generated by tapi. Do not edit manually.

import Tapi from "../../runtime";
import type { ServerUptime } from "../../types/database/ServerUptime";
import type { ServerUptimeRangeQuery } from "../../types/uptime/ServerUptimeRangeQuery";
import type { ServerUptimeStats } from "../../types/database/ServerUptimeStats";

export const uptime = {
  /**
   * Get the most recent server uptime record.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  getLatest: Tapi.get<{ response: ServerUptime | null }>()({
    endpoint: "/uptime/latest",
  }),
  /**
   * Compute aggregate server uptime statistics within a time range.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  getStats: Tapi.get<{ query: ServerUptimeRangeQuery; response: ServerUptimeStats }>()({
    endpoint: "/uptime/stat",
  }),
  /**
   * List server uptime records within a time range.
   *
   * Requires `ViewPulse`, which only platform staff hold.
   */
  list: Tapi.get<{ query: ServerUptimeRangeQuery; response: Array<ServerUptime> }>()({
    endpoint: "/uptime",
  }),
};
